CFLAGS=-O
FOBJ=faces.o file.o request.o error.o
TOBJ=scaffold.o file.o error.o

all:V: faced faces

faced:	faced.o
	$CC -o faced $LDFLAGS faced.o -lnetb -lipc

faces:  $FOBJ
	$CC -o faces $LDFLAGS $FOBJ -lipc

a.out: $TOBJ
	$CC $LDFLAGS $TOBJ

faced.o file.o request.o: faceproto.h
faces.o file.o request.o: faces.h
