SRC = /n/bowell/usr/src/cmd/map
LIBS = -lport -lF77 -lI77

map:	loxodromic.o index.o 
	cc $prereq $SRC/map.o $SRC/symbol.o $SRC/libmap.a $LIBS -o map

loxodromic.o: loxodromic.c
	cc -c -I$SRC loxodromic.c

index.o: $SRC/index.c
	cc -c -Df77 -I$SRC $prereq

lox:	lox.c
	cc lox.c $LIBS -o lox
