.EQ
delim $$
.EN
.EQ
tdefine ciplus % "\(O+" %
ndefine ciplus % O+ %
tdefine citimes % "\(Ox" %
ndefine citimes % Ox %
tdefine =wig % "\fS\v'-.2m'\z\(ap\v'.3m'=\v'-.1m'\fP" %
ndefine =wig % ="~" %
tdefine bigstar % "\s+2\fS\(**\fP\s-2" %
ndefine bigstar % X|- %
tdefine =dot % "\z\(eq\v'-.6m'\h'.2m'\s+2.\s-2\v'.6m'\h'.1m'" %
ndefine =dot % = dot %
tdefine orsign % "\fS\(or\fP" %
ndefine orsign % \e/ %
tdefine andsign % "\fS^\fP" %
ndefine andsign % /\e %
tdefine =del % "\fS\v'-.4m'\s-2\z\(*D\s+2\h'-.05m'\v'.5m'=\v'-.1m'\fP" %
ndefine =del % = to DELTA %
tdefine oppA % "\(fa" %
ndefine oppA % V- %
tdefine oppE %"\(te" %
ndefine oppE % E/ %
tdefine incl % "\s-5\h'-.1m'\v'-.1m'\z|\s+2\h'.2m'\v'-.35m'\z\(em\v'.7m'\z\(em\v'.2m'\(em\v'-.45m'\s+3" %
ndefine incl % C_ %
tdefine nomem % "\fS\h'.2m'\v'.05m'\z\(sl\v'-.05m'\h'-.2m'\(mo\fP" %
ndefine nomem % C-/ %
tdefine angstrom % "\fR\zA\v'-.3m'\h'.2m'\(de\v'.3m'\fP\h'.2m'" %
ndefine angstrom % A to o %
tdefine star % "\(**" %
ndefine star % * %
tdefine <wig % "\z<\v'.4m'\(ap\v'-.4m'" %
ndefine <wig %{ < from "~" }%
tdefine >wig % "\z>\v'.4m'\(ap\v'-.4m'" %
ndefine >wig %{ > from "~" }%
tdefine langle % "\fS\N'225'\fP" %
ndefine langle %<%
tdefine rangle % "\fS\N'241'\fP" %
ndefine rangle %>%
tdefine hbar % "\v'.2m'\s+3\N'194'\s-3\v'-.2m'\h'-.3m'h" %
ndefine hbar % h\u-\d %
ndefine ppd % _| %
tdefine ppd % "\fS\N'94'\fP" %
tdefine <-> % "\fS\N'171'\fP" %
ndefine <-> % "<-->" %
tdefine <=> % "\fS\N'219'\fP" %
ndefine <=> % "<=>" %
tdefine |< % "\o'<|'" %
ndefine |< % <| %
tdefine |> % "\o'>|'" %
ndefine |> % |> %
tdefine ang % "\fS\N'208'\fP" %
ndefine ang % /_ %
tdefine rang % "\s-3\fS\h'-.2m'\v'-.1m'\z|\s+3\h'.2m'\v'.1m'\(ru\fP" %
ndefine rang % L %
tdefine 3dot % "\v'-.8m'\z.\v'.5m'\z.\v'.5m'.\v'-.2m'" %
ndefine 3dot % .\u.\u.\d\d %
tdefine thf % "\fS\N'92'\fP" %
ndefine thf % ..\u.\d %
tdefine quarter % "\f1\s-3\u1\d\s+2\(sl\s-2\&4\s+3\fP" %
ndefine quarter % 1/4 %
tdefine 3quarter % "\f1\s-3\u3\d\s+2\(sl\s-2\&4\s+3\fP" %
ndefine 3quarter % 3/4 %
tdefine degree % \(de %
ndefine degree % nothing sup o %
tdefine square % \(sq %
ndefine square % [] %
tdefine circle % \(ci %
ndefine circle % O %
tdefine blot % "\(bx" %
ndefine blot % HIX %
tdefine bullet % \(bu %
ndefine bullet % oxe %
tdefine -wig % "\(~=" %
ndefine -wig % - to "~" %
tdefine wig % \(ap %
ndefine wig % "~" %
tdefine prop % \(pt %
ndefine prop % oc %
tdefine empty % \(es %
ndefine empty % O/ %
tdefine member % \(mo %
ndefine member % C- %
tdefine scrL % "\f(ZD\(Sl\fP" %
ndefine scrL % (/ %
define cap % \(ca %
tdefine cup % \(cu %
ndefine cup % U %
define subset % \(sb %
define supset % \(sp %
define !subset % \(ib %
define !supset % \(ip %
define not % \(no %
.EN
.TH EQNCHAR 6
.CT 1 writing_troff
.SH NAME
eqnchar \- special character definitions for eqn
.SH SYNOPSIS
.B eqn /usr/pub/eqnchar
[
.I file ...
]
.B | troff
[
.I option ...
]
.PP
.B neqn /usr/pub/eqnchar
[
.I file ...
]
.B | nroff
[
.I option ...
]
.SH DESCRIPTION
.I Eqnchar
contains
.I nroff
and
.IR troff (1)
character definitions for constructing characters that are not
available on standard fonts.
These definitions are primarily intended for use with
.I neqn
and
.IR eqn (1).
It contains
definitions for the following characters.
.if t .ig
WARNING to users of the on-line manual.
Unless your terminal has half-spacing, these examples
will be almost unreadable.
To get a well printed copy, execute
.BR "man -t eqnchar | lp" .
.PP
.nf
.ft5
.ta \w'angstrom  'u \n(.lu/3u +\w'angstrom  'u \n(.lu*2u/3u +\w'angstrom  'u
.ftR
\f5ciplus\fP	$ciplus$	\f5||\fP	$||$	\f5square\fP	$square$
\f5citimes\fP	$citimes$	\f5langle\fP	$langle$	\f5circle\fP	$circle$
\f5wig\fP	$wig$	\f5rangle\fP	$rangle$	\f5blot\fP	$blot$
\f5-wig\fP	$-wig$	\f5hbar\fP	$hbar$	\f5bullet\fP	$bullet$
\f5>wig\fP	$>wig$	\f5ppd\fP	$ppd$	\f5prop\fP	$prop$
\f5<wig\fP	$<wig$	\f5<->\fP	$<->$	\f5empty\fP	$empty$
\f5=wig\fP	$=wig$	\f5<=>\fP	$<=>$	\f5member\fP	$member$
\f5star\fP	$star$	\f5|<\fP	$|<$	\f5nomem\fP	$nomem$
\f5bigstar\fP	$bigstar$	\f5|>\fP	$|>$	\f5cup\fP	$cup$
\f5=dot\fP	$=dot$	\f5ang\fP	$ang$	\f5cap\fP	$cap$
\f5orsign\fP	$orsign$	\f5rang\fP	$rang$	\f5incl\fP	$incl$
\f5andsign\fP	$andsign$	\f53dot\fP	$3dot$	\f5subset\fP	$subset$
\f5=del\fP	$=del$	\f5thf\fP	$thf$	\f5supset\fP	$supset$
\f5oppA\fP	$oppA$	\f5quarter\fP	$quarter$	\f5!subset\fP	$!subset$
\f5oppE\fP	$oppE$	\f53quarter\fP	$3quarter$	\f5!supset\fP	$!supset$
\f5angstrom\fP	$angstrom$	\f5degree\fP	$degree$
.fi
.PP
Different
.I eqnchar
definitions may be needed for different output devices.
Alternative files, which are named according to the 
.BI -T dest
option of
.I troff,
are listed below.
.SH FILES
.nf
.F /usr/pub/eqnchar
.F /usr/pub/202eqnchar
.F /usr/pub/apseqnchar
.F /usr/pub/i300eqnchar
.F /usr/pub/posteqnchar
.fi
.SH SEE ALSO
.IR troff (1), 
.IR eqn (1)
.EQ
delim off
.EN
