|associate(sp;;;
	[|;; text "|"]
	[|s;; text "|\^"]
	[\;; text "\e"]
	[.;; text "\."]
	[space;; text "\ "]
	[digit space;; text "\0"]
	[narrow space;; text "\|\&"]
	[half narrow space;; text "\^"]
	[zero width space;; text "\&"]
	[hyphenation;; text "\%"]
	[leader;; text ""]
	[interrupt text processing;; text "\c"]
	[down;; text "\d"]
	[break and spread;; text "\p"]
	[reverse;; text "\r"]
	[tab;; text "\t"]
	[up;; text "\u"]
	[conceal new line;; text "\"]
	[close quote;; text "'"]
	[open quote;; text "`"]
	[Em dash;; text "\(em"]
	[hyphen or;; text "-"]
	[hyphen;; text "\(hy"]
	[minus;; text "\-"]
	[bullet;; text "\(bu"]
	[square;; text "\(sq"]
	[rule;; text "\(ru"]
	[quarter;; text "\(14"]
	[half;; text "\(12"]
	[3quarter;; text "\(34"]
	[fi;; text "\(fi"]
	[fl;; text "\(fl"]
	[ff;; text "\(ff"]
	[ffi;; text "\(Fi"]
	[ffl;; text "\(Fl"]
	[degree;; text "\(de"]
	[dagger;; text "\(dg"]
	[footmark;; text "\(fm"]
	[cent;; text "\(ct"]
	[registered;; text "\(rg"]
	[copyright;; text "\(co"]
	[=;; text "\(eq"]
	[+;; text "\(pl"]
	[-;; text "\(mi"]
	[*;; text "\(**"]
	[section;; text "\(sc"]
	[acute;; text "\(aa"]
	[grave;; text "\(ga"]
	[underrule;; text "\(ul"]
	[/;; text "\(sl"]
	[alpha;; text "\(*a"]
	[beta;; text "\(*b"]
	[gamma;; text "\(*g"]
	[delta;; text "\(*d"]
	[epsilon;; text "\(*e"]
	[zeta;; text "\(*z"]
	[eta;; text "\(*y"]
	[theta;; text "\(*h"]
	[iota;; text "\(*i"]
	[kappa;; text "\(*k"]
	[lambda;; text "\(*l"]
	[mu;; text "\(*m"]
	[nu;; text "\(*n"]
	[xi;; text "\(*c"]
	[omicron;; text "\(*o"]
	[pi;; text "\(*p"]
	[rho;; text "\(*r"]
	[sigma;; text "\(*s"]
	[terminal sigma;; text "\(ts"]
	[tau;; text "\(*t"]
	[upsilon;; text "\(*u"]
	[phi;; text "\(*f"]
	[chi;; text "\(*x"]
	[psi;; text "\(*q"]
	[omega;; text "\(*w"]
	[ALPHA;; text "\(*A"]
	[BETA;; text "\(*B"]
	[GAMMA;; text "\(*G"]
	[DELTA;; text "\(*D"]
	[EPSILON;; text "\(*E"]
	[ZETA;; text "\(*Z"]
	[ETA;; text "\(*Y"]
	[THETA;; text "\(*H"]
	[IOTA;; text "\(*I"]
	[KAPPA;; text "\(*K"]
	[LAMBDA;; text "\(*L"]
	[MU;; text "\(*M"]
	[NU;; text "\(*N"]
	[XI;; text "\(*C"]
	[OMICRON;; text "\(*O"]
	[PI;; text "\(*P"]
	[RHO;; text "\(*R"]
	[SIGMA;; text "\(*S"]
	[TAU;; text "\(*T"]
	[UPSILON;; text "\(*U"]
	[PHI;; text "\(*F"]
	[CHI;; text "\(*X"]
	[PSI;; text "\(*Q"]
	[OMEGA;; text "\(*W"]
	[>=;; text "\(>="]
	[<=;; text "\(<="]
	[==;; text "\(=="]
	[-wig;; text "\(~="]
	[wig;; text "\(ap"]
	[!=;; text "\(!="]
	[->;; text "\(->"]
	[<-;; text "\(<-"]
	[uarrow;; text "\(ua"]
	[darrow;; text "\(da"]
	[times;; text "\(mu"]
	[divide;; text "\(di"]
	[+-;; text "\(+-"]
	[cup;; text "\(cu"]
	[cap;; text "\(ca"]
	[subset;; text "\(sb"]
	[superset;; text "\(sp"]
	[isubset;; text "\(ib"]
	[isuperset;; text "\(ip"]
	[inf;; text "\(if"]
	[partial;; text "\(pd"]
	[del;; text "\(gr"]
	[not;; text "\(no"]
	[integral;; text "\(is"]
	[prop;; text "\(pt"]
	[empty;; text "\(es"]
	[member;; text "\(mo"]
	[box vertical rule;; text "\(br"]
	[double dagger;; text "\(dd"]
	[rhand;; text "\(rh"]
	[lhand;; text "\(lh"]
	[ATT logo;; text "\*(LO"]
	[or;; text "\(or"]
	[circle;; text "\(ci"]
	[bold vertical;; text "\(bv"]
	[lfloor;; text "\(lf"]
	[rfloor;; text "\(rf"]
	[lceil;; text "\(lc"]
	[rceil;; text "\(rc"]
	[lower case grave;; text "\*`"]
	[lower case acute;; text "\*'"]
	[upper case acute;; text "\*+"]
	[circumflex;; text "\*^"]
	[tilde;; text "\*~"]
	[cedilla;; text "\*,"]
	[lower case umlaut;; text "\*:"]
	[upper case umlaut;; text "\*;"]
	[nasal;; text "\*-"]
	[slashed;; text "\*/"]
	[TEX;; text "\s-1T\v'.17m'\h'-.12m'E\h'-.12m'\v'-.17m'X\s+1"]
	[LATEX;; text "\s-1L\h'-.12m'\v'-.17m'A\v'.17m'\h'-.12m'T\v'.17m'\h'-.12m'E\h'-.12m'\v'-.17m'X\s+1"]
	[TM;; text "\v'-0.5m'\s-4TM\s+4\v'0.5m'"])
	|comment<summary: sp (special characters)>
