.id NOTICE-NOT TO BE DISCLOSED OUTSIDE BELL SYS EXCEPT UNDER WRITTEN AGRMT
.id Writer's Workbench version 2.1, January 1981
.TH CHUNK 1
.SH NAME
chunk \- segment text into phrase units
.SH SYNOPSIS
.B chunk
[
.B \-flags
][
.B \-ver
]
[file ...]
.SH DESCRIPTION
.I Chunk
segments text into phrase units
by beginning a new line at the end of each unit it identifies.
.PP
Two options give information about the program:
.RS 5
.TP 7
.B \-flags
print the command synopsis line (see above)
showing command flags and options,
then exit.
.TP
.B \-ver
print the Writer's Workbench version number of the command, then exit.
.RE
.SH USES
This program is useful for reading research,
and it can be used to reformat text files for easier editing.
Additionally, editors may find it easier to edit a text whose microstructure
is typographically clear.
.SH BUGS
Since 
.I chunk
runs
.IR deroff (1)
on the input text,
formatting commands (and thus paragraph and heading structures) are lost
in the output.
.PP
.I Chunk
will think unfamiliar abbreviations are the end of a sentence,
and hence the end of the chunk.
.SH SUPPORT
.IR "COMPONENT NAME:  " "Writer's Workbench"
.br
.IR "APPROVAL AUTHORITY:  " "Div 452"
.br
.IR "STATUS:  " Standard
.br
.IR "SUPPLIER:  " "Dept 45271"
.br
.IR "USER INTERFACE:  " "Stacey Keenan, Dept 45271, PY x3733"
.br
.IR "SUPPORT LEVEL: " "Class B - unqualified support other than Div 452"
