.id NOTICE-NOT TO BE DISCLOSED OUTSIDE BELL SYS EXCEPT UNDER WRITTEN AGRMT
.id Writer's Workbench version 2.1, January 1981
.TH DOUBLE 1
.SH NAME
double \- double word finder
.SH SYNOPSIS
.B double
[
.B \-flags
][
.B \-ver
]
[file ...]
.SH DESCRIPTION
.I Double
searches text for consecutive occurrences of words.
It skips text contained in tables formatted with 
.IR tbl (1)
and ignores consecutive occurrences of any single character
except
.IR a .
When
.I double
finds two words in a row,
it prints them with the line number of the first one.
.PP
.I Double 
is one of the programs run under the
.IR proofr (1)
and
.IR wwb (1)
commands.
.PP
Two options give information about the program:
.RS 5
.TP 7
.B \-flags
print the command synopsis line (see above)
showing command flags and options,
then exit.
.TP
.B \-ver
print the Writer's Workbench version number of the command, then exit.
.RE
.SH SEE ALSO
proofr(1),
wwb(1),
tbl(1).
.SH SUPPORT
.IR "COMPONENT NAME:  " "Writer's Workbench"
.br
.IR "APPROVAL AUTHORITY:  " "Div 452"
.br
.IR "STATUS:  " Standard
.br
.IR "SUPPLIER:  " "Dept 45271"
.br
.IR "USER INTERFACE:  " "Stacey Keenan, Dept 45271, PY x3733"
.br
.IR "SUPPORT LEVEL: " "Class B - unqualified support other than Div 452"
