.id NOTICE-NOT TO BE DISCLOSED OUTSIDE BELL SYS EXCEPT UNDER WRITTEN AGRMT
.id Writer's Workbench version 2.1, January 1981
.TH GRAM (1)
.SH NAME
gram \- find split infinitives and incorrect indefinite articles
.br
splitrules \- print information about split infinitives
.SH SYNOPSIS
.B gram
[
.B \-flags
][
.B \-ver
]
[file ...]
.PP
.B splitrules
[
.B \-flags
][
.B \-ver
]
.SH DESCRIPTION
.I Gram
uses the 
.IR parts (1)
(part of speech assignment) program
to look for infinitives that are split by one or more adverbs.
It also checks for incorrect indefinite articles.
.PP
Grammatical information about split infinitives 
can be obtained by typing:
.BR splitrules .
.PP
Two options, which apply to both programs,
give information about the programs:
.RS 5
.TP 7
.B \-flags
print the command synopsis line (see above)
showing command flags and options,
then exit.
.TP
.B \-ver
print the Writer's Workbench version number of the command, then exit.
.RE
.PP
.I Gram
is one of the programs run under the 
.IR proofr (1)
and
.IR wwb (1)
commands.
.SH FILES
.TP 21
/tmp/$$
temporary files
.SH SEE ALSO
proofr(1),
wwb(1),
deroff(1),
parts(1).
.SH BUGS
.PP
Because
.I parts
is not always correct in its assignments,
.I gram
also makes errors.
.SH SUPPORT
.IR "COMPONENT NAME:  " "Writer's Workbench"
.br
.IR "APPROVAL AUTHORITY:  " "Div 452"
.br
.IR "STATUS:  " Standard
.br
.IR "SUPPLIER:  " "Dept 45271"
.br
.IR "USER INTERFACE:  " "Stacey Keenan, Dept 45271, PY x3733"
.br
.IR "SUPPORT LEVEL: " "Class B - unqualified support other than Div 452"
