.id NOTICE-NOT TO BE DISCLOSED OUTSIDE BELL SYS EXCEPT UNDER WRITTEN AGRMT
.id Writer's Workbench version 2.1, January 1981
.TH MATCH 1
.SH NAME
match \- compare style tables from two or more texts
.SH SYNOPSIS
.B match
[
.B \-flags
][
.B \-ver
]
[style-file1 [style-file2 ...] 
.SH DESCRIPTION
.I Match
collates selected variables from tables produced by the
.IR style (1)
command and prints values from the different files
one below the other for easy comparison.
The
.I style-files
must contain tables produced by
.IR style .
.PP
.I Match
can also run on one file
to produce an abbreviated version of the 
.I style
table.
.PP
When comparing texts, it is advisable to use
texts of similar length.
.PP
Two options give information about the program:
.RS 5
.TP 7
.B \-flags
print the command synopsis line (see above)
showing command flags and options,
then exit.
.TP
.B \-ver
print the Writer's Workbench version number of the command, then exit.
.RE
.SH USES
This program is useful for visually inspecting similarities
and differences among stylistic features of different documents
or drafts and their revisions.
.SH SEE ALSO
style(1),
prose(1).
.SH SUPPORT
.IR "COMPONENT NAME:  " "Writer's Workbench"
.br
.IR "APPROVAL AUTHORITY:  " "Div 452"
.br
.IR "STATUS:  " Standard
.br
.IR "SUPPLIER:  " "Dept 45271"
.br
.IR "USER INTERFACE:  " "Stacey Keenan, Dept 45271, PY x3733"
.br
.IR "SUPPORT LEVEL: " "Class B - unqualified support other than Div 452"
