.id NOTICE-NOT TO BE DISCLOSED OUTSIDE BELL SYS EXCEPT UNDER WRITTEN AGRMT
.id Writer's Workbench version 2.1, January 1981
.TH ORG 1
.SH NAME
org \- show the organization of a document
.SH SYNOPSIS
.B org
[
.B \-flags
][
.B \-ver
]
[file ...]
.SH DESCRIPTION
.I Org
copies the input text to the output,
and formats it,
preserving headings and paragraph boundaries,
but only including the first and last sentence of each paragraph.
The input text must contain standard 
.I mm(1)
macros.
.PP
The output can be used to study the general organization of the paper,
and is sometimes a good abstract.
.PP
Two options give information about the program:
.RS 5
.TP 7
.B \-flags
print the command synopsis line (see above)
showing command flags and options,
then exit.
.TP
.B \-ver
print the Writer's Workbench version number of the command, then exit.
.RE
.SH SEE ALSO
mm(1).
.SH BUGS
The input text must contain standard 
.I mm
macros.
.PP
.I Org
will not recognize common abbreviations at the end of
a sentence as the sentence end.
Consequently, more than two sentences may be printed for a paragraph.
.SH SUPPORT
.IR "COMPONENT NAME:  " "Writer's Workbench"
.br
.IR "APPROVAL AUTHORITY:  " "Div 452"
.br
.IR "STATUS:  " Standard
.br
.IR "SUPPLIER:  " "Dept 45271"
.br
.IR "USER INTERFACE:  " "Stacey Keenan, Dept 45271, PY x3733"
.br
.IR "SUPPORT LEVEL: " "Class B - unqualified support other than Div 452"
