.TH PUNCT 1
.SH NAME
punct \- punctuation checker
.SH SYNOPSIS
.B /usr/bin/WWB/punct
[ file ... ]
.SH DESCRIPTION
.I Punct
scans English text for punctuation errors and doubled words.
When it finds an error,
it places the error on the standard output
together with line number and suggested repunctuation.
.SH FILES
.ta \w'/tmp/$$*  'u
/tmp/$$*	temporary files
.SH SEE ALSO
style(1), diction(1), wwb(1)
.SH BUGS
.I Punct
will consider unfamiliar abbreviations ending with a period (except initials)
to be the end of the sentence,
consequently, it will capitalize the next word.
