.id NOTICE-NOT TO BE DISCLOSED OUTSIDE BELL SYS EXCEPT UNDER WRITTEN AGRMT
.id Writer's Workbench version 2.1, January 1981
.TH WWBINFO 1
.SH NAME
wwbinfo \- print table of WWB commands and functions
.SH SYNOPSIS
.B wwbinfo
[
.B \-ver
][
.B \-flags
]
.SH DESCRIPTION
.I Wwbinfo
prints a table listing the Writer's Workbench (WWB) commands
and their functions.
Some commands run other commands.
Subordinate commands are indented.
.PP
The table is divided into four parts:
general commands,
commands that give explanations,
environmental tailoring commands,
and user-specified dictionaries.
.PP
Two options give information about the program:
.PP
.RS 5
.TP 7
.B \-flags
print the command synopsis line (see above)
showing the command flags and options, then exit.
.TP
.B \-ver
print the Writer's Workbench version number of the command, then exit.
.RE
.SH SUPPORT
.IR "COMPONENT NAME:  " "Writer's Workbench"
.br
.IR "APPROVAL AUTHORITY:  " "Div 452"
.br
.IR "STATUS:  " Standard
.br
.IR "SUPPLIER:  " "Dept 45271"
.br
.IR "USER INTERFACE:  " "Stacey Keenan, Dept 45271, PY x3733"
.br
.IR "SUPPORT LEVEL: " "Class B - unqualified support other than Div 452"
