.ds dQ /usr/lib/postscript
.TH PSENCODING 1 "DWB 3.2"
.SH NAME
.B psencoding
\- check or set the default PostScript font encoding
.SH SYNOPSIS
\*(mBpsencoding\f1
.OP "" encoding []
.SH DESCRIPTION
.B psencoding
sets the default font Encoding used by many PostScript translators to
.IR encoding .
No arguments means list the available choices and the current default.
.PP
PostScript encoding files are in directory
.MR \*(dQ .
Many existing PostScript translators include the encoding file
.MR Default.enc ,
if it exists, in the output they generate.
.PP
Requesting
.I encoding
as the default means link the file
.MI \*(dQ/ encoding .enc
to the file
.MR \*(dQ/Default.enc .
Changing the default encoding assumes you can write in directory
.MR \*(dQ .
.SH FILES
.MW \*(dQ/Default.enc
.br
.MW \*(dQ/*.enc
.SH SEE ALSO
.BR buildtables (1),
.BR dpost (1),
.BR postprint (1),
.BR trofftable (1)
