/*
 * AT&T Bell Laboratories
 * file system user interface definitions
 * : : generated by mkhdr and  genhdr : :
 */

#ifndef __FSINFO_H__
#define __FSINFO_H__

#ifndef __LCLPARAM_H__
#ifndef S_IFMT
#ifndef TM_DEFAULT
#include <sys/types.h>
#endif
#include <sys/stat.h>
#endif
#endif

#define BUFFERSIZE	4096

#endif
