/*
 * AT&T Bell Laboratories
 * signal support
 * : : generated by mkhdr : :
 */

#ifndef __SIG_H__
#define __SIG_H__

#include <signal.h>

#ifndef sigmask
#define sigmask(s)	(1<<((s)-1))
#endif

#if __STDC__
typedef int (*signal_t)(int);
#else
typedef int (*signal_t)();
#endif

#endif
