/*
 * AT&T Bell Laboratories
 * signal name/text tables
 * : : generated by mkhdr and  genhdr : :
 */

int	sig_max = 26;

char*	sig_name[] =
{
	"0",
	"HUP",
	"INT",
	"QUIT",
	"ILL",
	"TRAP",
	"IOT",
	"EMT",
	"FPE",
	"KILL",
	"BUS",
	"SEGV",
	"SYS",
	"PIPE",
	"14",
	"TERM",
	"16",
	"STOP",
	"TSTP",
	"CONT",
	"CHLD",
	"TTIN",
	"TTOU",
	"TINT",
	"XCPU",
	"XFSZ",
	"LAB",
};

char*	sig_text[] =
{
	"Signal 0",
	"Hangup",
	"Interrupt",
	"Quit",
	"Illegal instruction",
	"Trace/BPT trap",
	"IOT trap",
	"EMT trap",
	"Floating exception",
	"Killed",
	"Bus error",
	"Memory fault",
	"Bad system call",
	"Broken Pipe",
	"Signal 14",
	"Terminated",
	"Signal 16",
	"Stopped (signal)",
	"Stopped",
	"Stopped process continued",
	"Child status change",
	"Stopped (tty input)",
	"Stopped (tty output)",
	"Interrupt (terminal)",
	"CPU time limit",
	"File size limit",
	"LAB trap",
};
