.TH STIME 2
.CT 2 sa
.SH NAME
stime, biasclock \(mi set time
.SH SYNOPSIS
.nf
.B int stime(tp)
.B long *tp;
.sp
.B biasclock(milli)
.B long milli;
.fi
.SH DESCRIPTION
.I Stime
sets the system's idea of the time and date.
Time, pointed to by
.I tp,
is measured in seconds from 00:00:00 GMT Jan 1, 1970.
.PP
.I Biasclock
informs the system that
its idea of the time
should be incremented by
.I milli
milliseconds.
The system will make the adjustment
gradually
and without causing time to run backwards.
.PP
Only the super-user may use these calls.
.SH "SEE ALSO"
.IR date (1), 
.IR wwv (1),
.IR time (2), 
.IR ctime (3)
.SH DIAGNOSTICS
.B EPERM
