.TH TIMES 2
.CT 2 time_man
.SH NAME
times \(mi get process times
.SH SYNOPSIS
.nf
.B "#include <sys/types.h>
.B "#include <sys/times.h>
.PP
.B int times(buffer)
.B struct tms *buffer;
.fi
.SH DESCRIPTION
.I Times
delivers time-accounting information
for the current process
and for the terminated child processes
of the current process.
All times are in
clock ticks.
.PP
.ta 8n +24n
.nf
\fLstruct tms
{\fP
	\fLtime_t tms_utime;\fP	user time for this process
	\fLtime_t tms_stime;\fP	system time for this process
	\fLtime_t tms_cutime;\fP	user time for all child processes
	\fLtime_t tms_cstime;\fP	system time for all child processes
\fL};\fP
.fi
.PP
The children times are the sum
of the children's process times and
their children's times.
.SH "SEE ALSO"
.IR time (1), 
.IR time (2)
.SH DIAGNOSTICS
.B EFAULT
