.TH UNLINK 2
.CT 2 file_inq_creat
.SH NAME
unlink \(mi remove directory entry
.SH SYNOPSIS
.nf
.B int unlink(name)
.B char *name;
.fi
.SH DESCRIPTION
.I Unlink
removes the entry for the file pointed to by
.I name
from its directory.
If this entry was the last link to the file,
the contents of the file are freed and the file is destroyed.
If, however, the file was open in any process, the actual
destruction is delayed until it is closed, even though
the directory entry has disappeared.
.PP
Only the super-user can
.I unlink 
a directory, but see
.I rmdir
in
.IR mkdir (2).
.SH "SEE ALSO"
.IR rm (1), 
.IR link (2),
.IR mkdir (2)
.SH DIAGNOSTICS
.BR EFAULT ,
.BR EIO ,
.BR ELOOP ,
.BR ENOENT ,
.BR ENOTDIR ,
.BR EROFS
