.so CDL
.fp 8 G
.de EP
.PP
.sp
..
.PD .2i
.de c
.TP 5
..
.TH JRAW 1G
.SH NAME
jraw \- edit a circuit diagram
.SH SYNOPSIS
.B jraw
[
.I option
] [
.I file
] ...
.SH DESCRIPTION
.I Jraw
is an attempt at making a picture editor work nearly as well as a sheet
of paper.
.I Jraw
draws when it looks like the user wants to draw, and moves things when
it looks like the user want to move them.  At least that's the way it
seems when the user is
.I jraw's
author.  All graphical operations use
the same (left) button on the mouse, in anticipation of someday using
a tablet instead.  This may cause some confusion to people used to sweeping
rectangles with the same button used to select the
.I
sweep rectangle
.R
menu entry.
.SH FILES
.nf
.ta 20
.PP
/bin/sh	UNIX shell to implement \fB!\fP
/usr/ucds/lib/lib	library directory
.fi
\*(SA
