.TH RENICE 8
.CT 1 sa_nonmortals
.SH NAME
renice \- change priority of running process
.SH SYNOPSIS
.B /etc/renice
[
.BI - priority
]
.I pid ...
.SH DESCRIPTION
.I Renice
increments the scheduling priority
of the processes with the named
.I process-ids
by
.IR pri .
The default
.IR pri
is 19,
making the process least likely to run.
.PP
Only the owner of the process
or the super-user may change the priority.
Only the super-user may use negative increments.
.SH FILES
.BI /proc
.SH SEE ALSO
.IR nice (1), 
.IR nice (2), 
.IR proc (4)
