.TH SENDCOVER 8
.CT 1 writing_output
.SH NAME
sendcover \- send cover sheet to the library
.SH SYNOPSIS
.B sendcover
.I file ...
.SH DESCRIPTION
.I Sendcover
sends a document cover sheet to the 
Bell Laboratories library for their document database.
It is invoked automatically as a byproduct of
running
.I troff -mcs.
.PP
The cover sheet is translated from the form of
.IR mcs (6)
to a form used in the library
and certain other protocol information is added.
The destination is not the same as that of
.IR docsubmit (1).
.SH FILES
.F /usr/lib/tmac/tmac.cs
.br
.F /usr/lib/tmac/cstrans
.SH "SEE ALSO"
.IR docsubmit (1),
.IR mcs (6)
