.TH SMSTAT 8
.CT 1 comm_mach
.SH NAME
smstat \- list smtp queues
.SH SYNOPSIS
.B smstat
.SH DESCRIPTION
.I Smstat
prints a summary of pending mail messages
queued by
the programs in
.IR smtp (8).
Each line contains the name of a spooling directory;
the number of outbound messages,
followed by
.LR C ;
and the number of inbound messages,
followed by
.LR X .
.SH FILES
.F /usr/spool/smtpq/*
spool directories
.SH SEE ALSO
.IR smtp (8)
