.TH SWAPON 8
.CT 1 sa_auto
.SH NAME
swapon \- specify swapping device
.SH SYNOPSIS
.B "/etc/swapon"
.B -a
.br
.B "/etc/swapon"
.I name ...
.SH DESCRIPTION
.I Swapon
specifies additional devices on which paging and swapping
are to take place.
The system begins by using a single device;
.I swapon
must be used to enable others.
.PP
Usually there is a call to
.L "swapon -a"
in
.IR rc (8).
Specific swap devices may be nominated with the second form.
.SH SEE ALSO
.IR rc (8),
.I vswapon
in
.IR deprecated (2)
.SH BUGS
There is no way to stop paging and swapping on a device.
It is therefore not possible to make use of devices which may be
dismounted during system operation.
.br
Possible swap devices
must be listed in a table configured into the system;
.I swapon
can only enable devices in the table.
