# makefile generated by mkold
LOCAL=$(HOME)

DIR.00 = /.

iostream.a : iostream.a.D/in.o iostream.a.D/out.o iostream.a.D/intin.o \
		iostream.a.D/flt.o iostream.a.D/rawin.o \
		iostream.a.D/sbuf.dbp.o iostream.a.D/stream.o \
		iostream.a.D/streambuf.o iostream.a.D/strstream.o \
		iostream.a.D/cstreams.o \
		iostream.a.D/stdiobuf.o iostream.a.D/swstdio.o \
		iostream.a.D/oldformat.o iostream.a.D/manip.o \
		iostream.a.D/fstream.o iostream.a.D/filebuf.o
	ar r iostream.a iostream.a.D/in.o iostream.a.D/out.o iostream.a.D/intin.o iostream.a.D/flt.o iostream.a.D/rawin.o iostream.a.D/sbuf.dbp.o iostream.a.D/stream.o iostream.a.D/streambuf.o iostream.a.D/strstream.o iostream.a.D/cstreams.o iostream.a.D/stdiobuf.o iostream.a.D/swstdio.o iostream.a.D/oldformat.o iostream.a.D/manip.o iostream.a.D/fstream.o iostream.a.D/filebuf.o

iostream.a.D/in.o : in.c iostream.h iostream.a.D/.created
	( : creating iostream.a.D ; if [ ! -d 'iostream.a.D' ] ; then mkdir 'iostream.a.D' ; fi ; cd 'iostream.a.D' && pwd ) ; $(CC) $(CCFLAGS) -I. -c in.c ; mv in.o iostream.a.D/in.o

iostream.a.D/.created :
	if [ ! -d iostream.a.D ] ; then ( : creating iostream.a.D ; if [ ! -d 'iostream.a.D' ] ; then mkdir 'iostream.a.D' ; fi ; cd 'iostream.a.D' && pwd ) ; fi$(newline)\
	touch iostream.a.D$(DIR.00)created

iostream.a.D/out.o : out.c streamdefs.h iostream.h \
		iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c out.c ; mv out.o iostream.a.D/out.o

iostream.a.D/intin.o : intin.c iostream.h iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c intin.c ; mv intin.o iostream.a.D/intin.o

iostream.a.D/flt.o : flt.c iostream.h iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c flt.c ; mv flt.o iostream.a.D/flt.o

iostream.a.D/rawin.o : rawin.c iostream.h iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c rawin.c ; mv rawin.o iostream.a.D/rawin.o

iostream.a.D/sbuf.dbp.o : sbuf.dbp.c iostream.h iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c sbuf.dbp.c ; mv sbuf.dbp.o iostream.a.D/sbuf.dbp.o

iostream.a.D/stream.o : stream.c iostream.h iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c stream.c ; mv stream.o iostream.a.D/stream.o

iostream.a.D/streambuf.o : streambuf.c streamdefs.h iostream.h \
		iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c streambuf.c ; mv streambuf.o iostream.a.D/streambuf.o

iostream.a.D/strstream.o : strstream.c strstream.h iostream.h \
		iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c strstream.c ; mv strstream.o iostream.a.D/strstream.o

iostream.a.D/cstreams.o : cstreams.c streamdefs.h fstream.h \
		iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c cstreams.c ; mv cstreams.o iostream.a.D/cstreams.o

iostream.a.D/stdiobuf.o : stdiobuf.c stdiostream.h \
		iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c stdiobuf.c ; mv stdiobuf.o iostream.a.D/stdiobuf.o

iostream.a.D/swstdio.o : swstdio.c stdiostream.h iostream.h \
		iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c swstdio.c ; mv swstdio.o iostream.a.D/swstdio.o

iostream.a.D/oldformat.o : oldformat.c fstream.h strstream.h \
		streamdefs.h stream.h iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c oldformat.c ; mv oldformat.o iostream.a.D/oldformat.o

iostream.a.D/manip.o : manip.c iomanip.h iostream.h \
		iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c manip.c ; mv manip.o iostream.a.D/manip.o

iostream.a.D/fstream.o : fstream.c fstream.h iostream.h \
		iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c fstream.c ; mv fstream.o iostream.a.D/fstream.o

iostream.a.D/filebuf.o : filebuf.c streamdefs.h fstream.h iostream.h \
		iostream.a.D/.created
	$(CC) $(CCFLAGS) -I. -c filebuf.c ; mv filebuf.o iostream.a.D/filebuf.o
null=
newline=;
sharp=#

clean : 
	rm -f *.o
	rm -rf *.D
	rm -f tmp* core
