hplot:	driver.o
	cc driver.o -l2621 -o hplot
tek:	driver.o
	cc driver.o -l4014 -o tek
trplot:	driver.o
	cc driver.o -ltr -o trplot
penplot:	driver.o
	cc driver.o -lpen -o penplot
ramtek:	driver.o
	cc driver.o -lram -o ramtek
install:
	cp hpplot trplot penplot tek /usr/lib/plot
