.ds dP /usr/lib/postscript
.ds dT /usr/lib/tmac
.ds . \f3.\fP
.TH MCOLOR 5
.SH NAME
mcolor \- color and reverse video macro
.SH SYNOPSIS
.B troff -mcolor
[
.I options
]
.I file ...
.SH DESCRIPTION
A macro package for color selection and reverse video printing
on PostScript printers.
The package is compatible with most existing macro packages
and includes the following macro:
.TP
\&\f5.CL\fP \|\fIcolor \^text\fP
Prints
.I text
in
.IR color .
No arguments restores the default color (black).
If
.I text
is omitted the selected
.I color
remains in effect until another
.I color
is selected.
If two arguments are given the
.I text
is printed in
.I color
and then the default color is restored.
.PP
Both the text and background color can be selected.
A
.I color
argument of "color1 on color2"
prints text in color1 on a background in color2.
.PP
Named colors must be listed in the colordict
dictionary in file
\*(dP/color.ps.
.SH FILES
\*(dT/tmac.color
.br
\*(dP/color.ps
.SH SEE ALSO
.IR troff (1),
.IR dpost (1),
