.TH CLOSESHARES 3 SHARE
.SH NAME
closeshares \- close shares file
.SH SYNOPSIS
.B "int closeshares()"
.SH DESCRIPTION
.I Closeshares
closes the shares file (if open) which otherwise remains open across
shares file routine calls.
.SH FILES
.PD 0
.TP "\w'/etc/sharesXXXX'u"
/etc/shares
Shares data-base.
.PD
.SH "SEE ALSO"
getshares(3),
getshput(3),
openshares(3),
putshares(3),
sharesfile(3).
