.TH DEMO 9.6
.CT 1 games
.SH NAME
demo, swar, pacman \- graphic demonstrations and games
.SH SYNOPSIS
.B demo
[
.I name
]
.SH DESCRIPTION
If a demo is named,
.I demo
runs it, otherwise
.I demo
produces a list of what's available.
.PP
Games that permit interaction are often controlled by the mouse;
experiment to find out what it does.
Some less obvious interactions are listed below.
.PP
.I Swar
is a two-player game.
One player uses the
.L asdwx
keys,
the other
.L 12350
keys on the keypad.
.PP
.I Pacman
is controlled by the
.L hjkl
keys or the mouse.
.SH SEE ALSO
.IR crabs (9.6)
.SH BUGS
Some of the programs don't play fair.
