.TH UL 1
.CT 1 comm_term
.SH NAME
ul, hp \- print underlines on screen terminals
.SH SYNOPSIS
.B ul
[
.B -i
]
[
.B -t
.I terminal
]
[
.I file ...
]
.PP
.B hp
[
.B -e
]
[
.B -m
]
.SH DESCRIPTION
.I Ul
replaces backspaced, overstruck underscores by control sequences suitable
for the terminal given by the environment variable
.L TERM
or by option
.BR -t .
It reads from the standard input or the named files and
writes on the standard output.
Option
.B -i
represents underlining by a separate line of 
.L -
characters.
.PP
.I Hp
is a filter that presents most
.IR nroff
output sensibly on HP 2600 series terminals.
Option
.B -s
stops and waits for a newline at the beginning of each page.
Option
.B -e
uses `display enhancement' features to distinguish
underlines, superscripts, and subscripts,
which are normally all shown in inverse video.
Option
.B -m
squeezes multiple newlines out of the output.
.SH SEE ALSO
.IR column (1)
.SH BUGS
.I Hp
does not reliably handle reverse line feeds as produced
by
.IR tbl (1);
pipe the input through
.I col
to get rid of them; see
.IR column (1).
