.fp 7 P1 IPA1
.fp 8 P2 IPA2
.TH IPA 6
.CT 1 writing_troff
.SH NAME
ipa \- international phonetic alphabet font and preprocessor
.SH SYNOPSIS
.B ipa
[
.I file ...
]
.SH DESCRIPTION
.I Ipa
copies the named 
.I files
to the standard output, translating text delimited in
either two ways into
.I troff
character codes for IPA graphics:
.IP
.BR @ipa( ... )
.br
.BR @ipa{ ... }
.PP
To generate IPA characters in a table,
.I ipa
should come before 
.IR tbl (1)
in a pipeline of processes.
.PP
The following table shows the correspondence between ASCII
characters and IPA graphics.
Only phonemes that occur in American English are handled.
The reference tells how to access other IPA graphics that 
exist in the font.
.if n .ig
.TS
cfL c | cfL c | cfL c | cfL c | cfL c.
a	@ipa{a}	b	@ipa{b}	c	@ipa{c}	d	@ipa{d}	e	@ipa{e}
f	@ipa{f}	g	@ipa{g}	h	@ipa{h}	i	@ipa{i}	j	@ipa{j}
k	@ipa{k}	l	@ipa{l}	m	@ipa{m}	n	@ipa{n}	o	@ipa{o}
p	@ipa{p}	q	@ipa{q}	r	@ipa{r}	s	@ipa{s}	t	@ipa{t}
u	@ipa{u}	v	@ipa{v}	w	@ipa{w}	x	@ipa{x}	y	@ipa{y}
z	@ipa{z}	A	@ipa{A}	B	@ipa{B}	C	@ipa{C}	D	@ipa{D}
E	@ipa{E}	F	@ipa{F}	G	@ipa{G}	H	@ipa{H}	I	@ipa{I}
J	@ipa{J}	K	@ipa{K}	L	@ipa{L}	M	@ipa{M}	N	@ipa{N}
O	@ipa{O}	P	@ipa{P}	Q	@ipa{Q}	R	@ipa{R}	S	@ipa{S}
T	@ipa{T}	U	@ipa{U}	V	@ipa{V}	W	@ipa{W}	X	@ipa{X}
Y	@ipa{Y}	Z	@ipa{Z}	!	@ipa{!}	@	@ipa{@}	#	@ipa{#}
$	@ipa{$}	%	@ipa{%}	^	@ipa{^}	&	@ipa{&}	*	@ipa{*}
\&_	@ipa{_}	-	@ipa{-}	+	@ipa{+}	\&=	@ipa{=}	,	@ipa{,}
<	@ipa{<}	.	@ipa{.}	>	@ipa{>}	:	@ipa{:}	;	@ipa{;}
"	@ipa{"}	'	@ipa{'}	|	@ipa{|}	~	@ipa{~}	`	@ipa{`}
?	@ipa{?}
.TE
..
.if t .ig
.IP
TABLE NOT PRINTABLE IN NROFF
..
.SH SEE ALSO
M. Y. Liberman,
.I An IPA Preprocessor for Troff,
11225-860915-15TMS
.br
.IR troff (1)
.SH BUGS
.I Ipa
mounts the IPA fonts in 
.I troff
font positions 5 and 6, which may conflict with other
font assignments.
