.TH LPR 1 alice
.CT 1 comm_dev
.SH NAME
lpr \(mi line printer spooler
.SH SYNOPSIS
.B lpr
[
.B -m
]
[
.I name ...
]
.PP
.B lp0
[
.I name ...
]
.PP
.B lp1
[
.I name ...
]
.SH DESCRIPTION
.I Lpr
causes the
named files
to be queued and then printed off line.
If no files are named, the standard input is read.
The option
.B -m
causes notification via
.IR mail (1)
to be sent when the job completes.
.PP
.I Lp0
and
.I lp1
direct output to particular printers.
.SH FILES
.TF /usr/spool/lpd/*
.TP
.F /usr/spool/lpd/*
spool area
.TP
.F /usr/lib/lpd
printer daemon
.TP
.F /usr/lib/lpfx
filter to handle banners and underlining
.SH SEE\ ALSO
.IR pr (1), 
.IR thinkblt (9.1)
.SH BUGS
Queued jobs print in directory (seemingly random) order.
