.TH MEMO 1 "local"
.SH NAME
memo \- produce macros for MM interactively
.SH SYNOPSIS
.B memo
.I filename \
[
.I argument\
]
.SH DESCRIPTION
.I Memo
is designed as a computer
aid to help new or infrequent users of the PWB/MM Memorandum
Macros.
It asks questions interactively to produce a
file which contains the necessary introductory and concluding
macros for PWB/MM.
In order to enter the text of the memo, you must enter
the editor.
For help to any question enter a
.I
\?
A detailed explanation of the proper
answer will be printed.
.P
The following are optional arguments to be used when filename already exists to avoid lengthy printout:
.TP 7
.B a
Enter editor to add/modify text.
.TP 7
.B b
Be prompted for concluding macros.
.TP 7
!
Overwrite filename and begin introductory macros.
.PD
.SH "SEE ALSO"
.IR nroff (1)
