.TH OPENSHARES 3 SHARE
.SH NAME
openshares \- open shares file
.SH SYNOPSIS
.B "int openshares(lock)"
.br
.B "int lock;"
.SH DESCRIPTION
.I Openshares
attempts to open the shares file for writing,
otherwise,
if 
.I lock
is 0,
it attempts to open it for reading.
If one of the opens succeeds,
it returns 1,
otherwise it returns 0.
.PP
If the shares file is already open,
this routine does nothing.
.SH FILES
.PD 0
.TP "\w'/etc/sharesXXXX'u"
/etc/shares
Shares data-base.
.PD
.SH "SEE ALSO"
closeshares(3),
getshares(3),
getshput(3),
putshares(3),
sharesfile(3).
