.TH PL 1 SHARE
.SH NAME
pl \- print share information for designated users
.SH SYNOPSIS
.B pl
[-a[g]] [-[n][v]] [-pfilename] [-u uid[-uid] ...] [login-name ...]
.SH DESCRIPTION
.I Pl
prints the share information
for the given list of login names.
The optional flags affect the default behaviour as follows:-
.TP "\w'-pfileXX'u"
.BI -a [g]
This flag causes information on all currently active users to be printed.
The optional flag
.B g
restricts the selection to real users (ie: doesn't print
.IR groups ).
.TP
.BI -n
The normal output is one item per line,
this flag puts all items for a user on the same line.
.TP
.BI -p file
Directs
.I pl
to use an alternate shares file, whose path name is
.IR file .
.TP
.BI -u
The list is assumed to be user IDs.
If any two user IDs are separated by a minus, then an inclusive range is assumed.
.TP
.BI -v
The normal output includes descriptions of each item,
this flag turns off verbose mode.
.PP
If no arguments are given then
.I pl
will use the login name of the person that executed
the command.
.SH FILES
.PD 0
.TP "\w'/etc/sharesXX'u"
/etc/shares
The shares file.
.TP
/etc/passwd
Information on user names and \s-1ID\s0s.
.PD
.SH "SEE ALSO"
lnode(5), passwd(5), share(5).
