.TH PUTSHARES 3 SHARE
.SH NAME
putshares \- write shares file entry
.SH SYNOPSIS
.B "#include <shares.h>"
.br
.sp
.B "int putshares(lp, extime)"
.br
.B "struct lnode * lp;"
.br
.B "unsigned long extime;"
.SH DESCRIPTION
.I Putshares
writes the shares entry with the same uid as
.IR lp\->l_uid .
.I Putshares
returns -1 if any error occurs,
0 if
.I lp\->l_uid
is greater than
.SM MAXUID ,
or the size of the entry if succesfully written.
.SH "SEE ALSO"
closeshares(3),
getshares(3),
getshput(3),
openshares(3),
sharesfile(3).
.SH DIAGNOSTICS
.I Putshares
returns 0
if
.I lp\->l_uid
is greater than
.SM MAXUID ,
or -1 on error.
