.TH RATES 1 SHARE
.SH NAME
rates \- show system share scheduling rates by scheduling group
.SH SYNOPSIS
.B rates
[-Kn] [-cn] [-sn] [-u]
.SH DESCRIPTION
.I Rates
prints a table of rates by scheduling group,
which purports to show the share of the system being allocated to each group
of users.
In particular,
it is possible to compare the actual working rate with the intended
and effective share.
.PP
The table contains `#'s to indicate rate of consumption of resources
for each group,
an `I' indicating the intended share,
and (if different) an '!' indicating the effective share.
Any difference between intended and effective share is caused
by the recent history of usage.
.P
Invoked without arguments,
.I Rates
will print the table and exit.
The flags affect operation as follows:-
.RS 2
.TP 10
.ul
flag
.ul
meaning
.TP
.BI -K n
Set the 
.I half-life
for decaying the displayed rate to
.B n
seconds [default 4].
.TP
.BI -c n
Continuous operation, where
.BR n ,
if present, limits the number of cycles.
.TP
.BI -s n
Delay time between updates becomes
.B n
seconds [default 4].
.TP
.BI -u
The display will show users,
instead of scheduling groups.
.SH EXAMPLES
.RS 4
\fBrates -c | dis\fR
.SH SEE ALSO
dis(1),
shstats(1),
ustats(1),
share(5).
