.TH REMSHENT 1 SHARE
.SH NAME
remshent \- remove an entry from the shares data-base
.SH SYNOPSIS
.B remshent
[\c
.I name|uid ...\c
]
.SH DESCRIPTION
.I Remshent
removes entries from the shares data-base in the file
.IR /etc/shares .
Entries are specified as user names,
or as uids.
If no arguments are given,
.I remshent
reads the names from standard input,
one per line.
.SH FILES
.PD 0
.TP 16
/etc/shares
for share details.
.TP
/etc/passwd
for user names and \s-1ID\s0s.
.PD
.SH "SEE ALSO"
.IR lim (1),
.IR pl (1),
.IR shares (5).
