.TH SERVER 1
.CT 1 comm_mach
.SH NAME
server \- run anonymous command on another machine
.SH SYNOPSIS
.B server
.I machine command
.SH DESCRIPTION
.I Server
uses Datakit to run
.I command
on the named
.I machine.
If it has set-userid mode,
the owner of
.I server
will log in on the remote machine.
In this way, a user can execute commands on the
remote machine without having a login there.
.PP
.I Server
typically accepts only a small set of commands, such as
.I who, ps, cat,
and
.I date;
the list is at the discretion of the remote machine.
.I Server
also checks for suspicious argument characters.
.SH FILES
.F /etc/server
list of legal commands
.SH "SEE ALSO"
.IR con (1), 
.IR push (1), 
.IR dcon (1)
