.TH SETUPGROUPS 3
.SH NAME
setupgroups \- set access group vector for invoker
.SH SYNOPSIS
.B setupgroups(name, gid)
.br
.B char *name;
.br
.B int gid;
.SH DESCRIPTION
This library routine sets up the invoker's access group vector
by searching the
.I /etc/group
file for groups matching
.IR name .
The invokers real group ID should be passed in
.IR gid ,
as there is no need to load this into the vector.
.PP
.I Setgroups
returns 0 for success, or \-1 on error with
.I errno
set appropriately.
.PP
This routine is safe to use on systems
where the multiple access groups system calls have not been installed.
.SH "SEE ALSO"
setgroups(2),
getgrent(3),
login(8).
