.TH SHARESFILE 3 SHARE
.SH NAME
sharesfile \- change name of shares file
.SH SYNOPSIS
.B "int sharesfile(s)"
.br
.B "char * s;"
.SH DESCRIPTION
This routine
closes the old shares file (if open)
and resets its name to the string passed.
.SH "SEE ALSO"
closeshares(3),
getshares(3),
getshput(3),
openshares(3),
putshares(3).
