.TH TELNO 7
.SH NAME
telno \- retrieve from bell labs phone book
.SH SYNOPSIS
.B telno
[
.I datum ... datum
]
.SH DESCRIPTION
.PP
If there are no arguments on the command line,
.I telno
reads its arguments, one to a line,
from the standard input.
Arguments are names,
phone numbers,
or organization numbers,
possibly preceded by a keyword and an equal sign.
The first character of a name must be a letter,
of a phone number or organization number a digit.
Otherwise regular expressions
.I a la
.IR grep (1)
are accepted.
Names are prefixes of last names, or the last name followed
by a comma and one initial.
.PP
Giving a name, a phone number, or an organization number
.I (org=127)
produces
white pages information.
.SH SEE ALSO
.IR tel (7)
.SH DIAGNOSTICS
.I too long
means that the given name has more letters than any
name in the phone book.
(All the names are truncated to 8 characters before the data
arrives on the machine.)
.I None
is printed when there are no matches.
.SH BUGS
The phone book is badly out of date.
