.TH FONT 6
.CT 1 writing_troff writing_output
.SH NAME
font \- typesetter fonts
.SH DESCRIPTION
Listed below are some of the more common (or more cryptically
named) typesetter fonts.
.PP
In the directories
.F /usr/lib/font
and
.F /usr/jerq/font 
are kept tables for fonts available on some or all of
the Autologic APS-5 phototypesetter, the Mergenthaler Linotron 202
phototypesetter, the Canon laser printer,
and the Teletype 5620 terminal running under 
.IR mux (9.1).
Those directories may be consulted for the
current list of offerings.
.PP
Most fonts come in families, e.g.
.LR Souvenir ,
.L SouvenirI
(italic),
.L SouvenirB
(bold),
.L SouvenirBI
(bold italic),
.L SouvenirBK
(demi-bold, `black')
.L SouvenirKI
(demi-bold italic).
For the 5620 and the Canon there is a
separate font table for each point size, e.g.
.LR CW.11 .
.PP
In
.I troff
fonts must be `mounted' in a `font position'. 
The default set is 
.L
R I B BI H HB HK CW CH S
for the 202 and the Canon
and
.L
R I B H CW S S1 GR
for the APS-5.
Other fonts may be mounted with the
.L .fp
request.
Fonts with long names must be given aliases; see
the
.IR troff
manual.
.LP
.2C
.de fq
\f5\\$1\\fR	\\$2 \\$3 \\$4 \\$5 \\$6
..
.fq B Times bold
.fq BI Times bold italic
.fq CH Chess
.fq CS Constant Width Slanted
.fq CT Courier Typewriter (APS-5)
.fq CW Constant width (ASCII typewriter)
.fq CX News Gothic condensed italic (APS-5)
.fq GB Greek bold (APS-5)
.fq GR Greek
.fq GS German Script (APS-5)
.fq H  Helvetica
.fq HB Helvetica bold
.fq HI Helvetica italic
.fq HK Helvetica black
.fq HX Helvetica bold italic
.fq I  Times italic
.fq M1 Universal [sic] Math 1
.fq M2 Universal Math 2
.fq M3 Universal Math 3
.fq OE Old English
.fq OK Helvetica outline black
.fq PA Palatino
.fq PB Palatino bold
.fq PI Palatino italic
.fq PO Printout (ASCII constant width)
.fq PX Palatino bold italic
.fq R  Times Roman
.fq S  Special (math symbols)
.fq S1 Special (APS-5)
.fq SC Script (APS-5)
.fq SM Stymie medium (APS-5)
.fq TB Techno bold (APS-5)
.fq TX Techno bold italic (APS-5)
.fq US USA state maps (202)
.fq X1 Universal Newspaper Pi (202)
.LP
.fq defont Default \fImux\fR font
.1C
.SH FILES
.TF /usr/lib/font/dev202/DESC.out
.TP
.F /usr/lib/font
.TP
.F /usr/lib/font/dev202/DESC.out
description of 202 typesetter
.TP
.F /usr/lib/font/dev202/R.out
tables for font
.L R
.br
.F /usr/jerq/font
.SH SEE ALSO
.IR troff (1), 
.IR jf (9.1), 
.IR font (9.5)
