.TH TERM 6
.CT 1 comm_term
.SH NAME
terminals \- conventional names
.SH DESCRIPTION
These names
are used by certain commands and are maintained
as part of the shell environment; see
.IR sh (1),
.IR environ (5).
.TF dumb
.TP
.B 2621
Hewlett-Packard HP262? series terminals
.TP
.B 1620
DIABLO 1620 (and others using HyType II)
.TP
.B 33
Teletype Model 33
.TP
.B 37
Teletype Model 37
.TP
.B 43
Teletype Model 43
.TP
.B 5620
Teletype Model 5620 dotmap display
.TP
.B dumb
terminals with no special features
.TP
.B 4014
Tektronix 4014
.TP
.B vt52
Digital Equipment Corp. VT52
.PD
.PP
The list goes on and on.
Consult
.F /etc/termcap
(see
.IR termcap (5))
for the whole truth.
.PP
Commands whose behavior may depend on the terminal
typically consult
.L TERM
in the environment
or accept arguments of the form
.BI -T term,
where
.I term
is one of the names given above.
.SH SEE ALSO
.IR stty (1), 
.IR tabs (1), 
.IR plot (1),
.IR sh (1), 
.IR environ (5),
.IR ul (1), 
.IR column (1),
.IR termcap (5),
.I nroff
in
.IR troff (1)
.SH BUGS
The programs that ought to adhere to this nomenclature
do so only fitfully.
