xx(ADDD,"addd3 r%d,r%d,r%d\n")
xx(ADDF,"addf3 r%d,r%d,r%d\n")
xx(ADDI,"addl3 r%d,r%d,r%d\n")
xx(ADDP,"addl3 r%d,r%d,r%d\n")
xx(ADDRFP,"moval %s(ap),r%d\n")
xx(ADDRGP,"moval _%s,r%d\n")
xx(ADDRLP,"moval %s(fp),r%d\n")
xx(ADDU,"addl3 r%d,r%d,r%d\n")
xx(ARGB,"(see emit)")
xx(ARGD,"movd r%d,%d(sp)\n")
xx(ARGF,"movf r%d,%d(sp)\n")
xx(ARGI,"movl r%d,%d(sp)\n")
xx(ARGP,"movl r%d,%d(sp)\n")
xx(ASGNB,"(see emit)\n")
xx(ASGNC,"movb r%d,(r%d)\n")
xx(ASGND,"movd r%d,(r%d)\n")
xx(ASGNF,"movf r%d,(r%d)\n")
xx(ASGNI,"movl r%d,(r%d)\n")
xx(ASGNP,"movl r%d,(r%d)\n")
xx(ASGNS,"movw r%d,(r%d)\n")
xx(BANDI,"bicl3 r%d,r%d,r%d\n")
xx(BANDU,"bicl3 r%d,r%d,r%d\n")
xx(BCOMU,"mcoml r%d,r%d\n")
xx(BORI,"bisl3 r%d,r%d,r%d\n")
xx(BORU,"bisl3 r%d,r%d,r%d\n")
xx(BXORI,"xorl3 r%d,r%d,r%d\n")
xx(BXORU,"xorl3 r%d,r%d,r%d\n")
xx(CALLB,"calls $0,(r%d)\n")
xx(CALLD,"calls $0,(r%d); movd r0,r%d\n")
xx(CALLF,"calls $0,(r%d); movf r0,r%d\n")
xx(CALLI,"calls $0,(r%d); movl r0,r%d\n")
xx(CALLV,"calls $0,(r%d)\n")
xx(CNSTC,"movl $%s,r%d\n")
xx(CNSTI,"movl $%s,r%d\n")
xx(CNSTP,"movl $%s,r%d\n")
xx(CNSTS,"movl $%s,r%d\n")
xx(CNSTU,"movl $%s,r%d\n")
xx(CVCI,"cvtbl r%d,r%d\n")
xx(CVCU,"movzbl r%d,r%d\n")
xx(CVDF,"cvtdf r%d,r%d\n")
xx(CVDI,"cvtdl r%d,r%d\n")
xx(CVDU,"cvtdl r%d,r%d\n")
xx(CVFD,"cvtfd r%d,r%d\n")
xx(CVIC,"cvtlb r%d,r%d\n")
xx(CVID,"cvtld r%d,r%d\n")
xx(CVIS,"cvtlw r%d,r%d\n")
xx(CVIU,"movl r%d,r%d\n")
xx(CVPU,"movl r%d,r%d\n")
xx(CVSI,"cvtwl r%d,r%d\n")
xx(CVSU,"movzwl r%d,r%d\n")
xx(CVUC,"cvtlb r%d,r%d\n")
xx(CVUI,"movl r%d,r%d\n")
xx(CVUP,"movl r%d,r%d\n")
xx(CVUS,"movw r%d,r%d\n")
xx(DIVD,"divd3 r%d,r%d,r%d\n")
xx(DIVF,"divf3 r%d,r%d,r%d\n")
xx(DIVI,"divl3 r%d,r%d,r%d\n")
xx(DIVU,"pushl r%d; pushl r%d; calls $2,udiv; movl r0,r%d\n")
xx(EQD,"cmpd r%d,r%d; jeql L%s\n")
xx(EQF,"cmpf r%d,r%d; jeql L%s\n")
xx(EQI,"cmpl r%d,r%d; jeql L%s\n")
xx(EQU,"cmpl r%d,r%d; jeqlu L%s\n")
xx(GED,"cmpd r%d,r%d; jgeq L%s\n")
xx(GEF,"cmpf r%d,r%d; jgeq L%s\n")
xx(GEI,"cmpl r%d,r%d; jgeq L%s\n")
xx(GEU,"cmpl r%d,r%d; jgequ L%s\n")
xx(GTD,"cmpd r%d,r%d; jgtr L%s\n")
xx(GTF,"cmpf r%d,r%d; jgtr L%s\n")
xx(GTI,"cmpl r%d,r%d; jgtr L%s\n")
xx(GTU,"cmpl r%d,r%d; jgtru L%s\n")
xx(INDIRB,"moval (r%d),r%d\n")
xx(INDIRC,"movb (r%d),r%d\n")
xx(INDIRD,"movd (r%d),r%d\n")
xx(INDIRF,"movf (r%d),r%d\n")
xx(INDIRI,"movl (r%d),r%d\n")
xx(INDIRP,"movl (r%d),r%d\n")
xx(INDIRS,"movw (r%d),r%d\n")
xx(JUMPV,"jbr L%s\n")
xx(LED,"cmpd r%d,r%d; jleq L%s\n")
xx(LEF,"cmpf r%d,r%d; jleq L%s\n")
xx(LEI,"cmpl r%d,r%d; jleq L%s\n")
xx(LEU,"cmpl r%d,r%d; jlequ L%s\n")
xx(LSHI,"ashl r%d,r%d,r%d\n")
xx(LSHU,"ashl r%d,r%d,r%d\n")
xx(LTD,"cmpd r%d,r%d; jlss L%s\n")
xx(LTF,"cmpf r%d,r%d; jlss L%s\n")
xx(LTI,"cmpl r%d,r%d; jlss L%s\n")
xx(LTU,"cmpl r%d,r%d; jlssu L%s\n")
xx(MODI,"(see emit)")
xx(MODU,"pushl r%d; pushl r%d; calls $2,urem; movl r0,r%d\n")
xx(MULD,"muld3 r%d,r%d,r%d\n")
xx(MULF,"mulf3 r%d,r%d,r%d\n")
xx(MULI,"mull3 r%d,r%d,r%d\n")
xx(MULU,"mull3 r%d,r%d,r%d\n")
xx(NED,"cmpd r%d,r%d; jneq L%s\n")
xx(NEF,"cmpf r%d,r%d; jneq L%s\n")
xx(NEGD,"mnegd r%d,r%d\n")
xx(NEGF,"mnegf r%d,r%d\n")
xx(NEGI,"mnegl r%d,r%d\n")
xx(NEI,"cmpl r%d,r%d; jneq L%s\n")
xx(NEU,"cmpl r%d,r%d; jnequ L%s\n")
xx(RETD,"movd r%d,r0\n")
xx(RETF,"movf r%d,r0\n")
xx(RETI,"movl r%d,r0\n")
xx(RETV,"")
xx(RSHI,"ashl r%d,r%d,r%d\n")
xx(RSHU,"(see emit)")
xx(SUBD,"subd3 r%d,r%d,r%d\n")
xx(SUBF,"subf3 r%d,r%d,r%d\n")
xx(SUBI,"subl3 r%d,r%d,r%d\n")
xx(SUBP,"subl3 r%d,r%d,r%d\n")
xx(SUBU,"subl3 r%d,r%d,r%d\n")
xx(SWTCHI,"movl r%d,r0\n")
