.TH CORE 5
.CT 1 debug_tune
.SH NAME
core \- format of memory image file
.SH DESCRIPTION
A memory image of a terminated
process is written into file
.F core
when any of various errors occur; see
.IR signal (2).
The memory image is written in the process's
working directory, if it can be; normal
access controls apply.
.PP
A core file consists of a copy of the user block for the
terminated process, followed by an image of its data
and stack segments.
The user block, which occupies 5K bytes, contains descriptive
information about the process and a stack used by the operating
system when serving the process; see the include file
.BR <sys/user.h> .
.SH "SEE ALSO"
.IR adb (1), 
.IR pi (9.1),
.IR bigcore (1),
.IR signal (2)
