< ../ADM/defns

all:V:	intro.out

pg:	intro.out
	count intro.ms intro.out

spell:VQ:
	dospell intro.ms

lp:	intro.out
	$LP $newprereq && touch $target

intro.out:D:	intro.ms $REF
	$PREFER -sapa intro.ms | troff -mpm > $target

index:V:
	touch intro.ind
pindex:V:
	touch intro.ind
