.TH TTYS 5
.CT 1 comm_term
.SH NAME
ttys \- terminal initialization data
.SH DESCRIPTION
The file
.F /etc/ttys
directs
.IR init (8)
in associating login processes with terminal ports.
It contains one line per port.
.PP
If the first character of a line is
.L 0
the line will be ignored;
if it is 
.L 1
the line will be effective.
The second character is used as an argument to
.IR getty (8),
which performs such tasks as baud-rate recognition,
reading the login name,
and calling
.IR login (8).
For normal lines,
the character is 
.LR 0 .
Other characters can be used, for example, with hard-wired terminals
where speed recognition is unnecessary
or which have special characteristics; see
.IR getty (8)
for a list.
The remainder of the line is the terminal's entry
in the device directory,
.FR /dev .
.SH FILES
.F /etc/ttys
.SH "SEE ALSO"
.IR init (8), 
.IR getty (8), 
.IR login (8)
