/*
 * AT&T Bell Laboratories
 * <sys/param.h> + <sys/types.h> + <sys/stat.h>
 * : : generated by mkhdr : :
 */

#ifndef __LCLPARAM_H__
#define __LCLPARAM_H__

#include <sys/param.h>
#ifndef S_IFDIR
#include <sys/stat.h>
#endif

#endif
