.TH GETFONT 9.1
.CT 1 comm_term
.SH NAME
getfont \- replace terminal's default font
.SH SYNOPSIS
.B getfont
[
.I option ...
]
[
.I font
]
.SH DESCRIPTION
.I Getfont
reads font data from file
.I font.
The current layer and subsequently created layers use this font as
.IR defont ;
see
.IR string (9.3).
If
.I font
does not directly name a file, it is looked for in directory
.FR /usr/jerq/font .
.PP
The options are:
.TP
.B -m
The font change applies to the basic
.IR mux (9.1)
menu as well as to layers.
.TP
.B -l
The font change applies to the current layer only.
.TP
.B -d
Print debugging information about fonts before and after.
.PP
.I Getfont
discards inaccessible fonts.
To reclaim store without loading a font,
call it with no
.I font
argument.
.SH EXAMPLES
.TP
.L
getfont pelm.10
Larger type for demos and eyesight problems.
.TP
.L
getfont defont
Restore the original font.
.SH FILES
.F /usr/jerq/font
.SH SEE ALSO
.IR string (9.3), 
.IR font (9.5), 
.IR font (6)
