.TH READER 9.7
.CT 1 writing_output inst_info
.SH NAME
reader \- electronic retrieval of typeset documents
.SH SYNOPSIS
.B reader
.I name
.SH DESCRIPTION
.I Reader
presents the named paper on a 5620 terminal in a form designed
for readability, not for similarity to the printed version.
The
.I name
is a pathname for a manuscript in the 
.IR papers (7)
database with
any final
.L .d
elided) or the name of a 
.IR troff (1)
input file.
Mouse button 1 selects subheads;
button 3 moves forward (`more') or backward (`less').
The program exits completely on button 2, or tentatively (to avoid
downloading upon reexecution) on button 3 (`done').
.PP
When the text in a screen overlaps text in a previous screen, a tick mark
in the bar (not a scroll bar) at the left of the screen shows where
new material begins.
.PP
Fully installed papers in the database, which appear as directories suffixed
.LR .d ,
have been preprocessed so that
.I reader
can present figures and complex equations.
In
.I troff
input, it understands straightforward text and 
.IR eqn (1),
the macro packages
.IR ms (6),
.I mm,
and
.I me,
but cannot handle arbitrary motions such as appear in figures and
complex equations.
.SH FILES
.TF /n/bowell/pap/Titles
.TP
.F /n/bowell/pap/Titles
titles, authors and installation dates
.TP
.F /n/bowell/pap/*org
membership list
.TP
.BI /n/bowell/pap/ center / department / author\f5/\fIpapername\fR[\f5.d\fR]
.SH SEE ALSO
.IR troff (1), 
.IR proof (9.1), 
.IR docsubmit (1), 
.IR papers (7)
.SH BUGS
Button 1 knows only already-read subheads unless the paper has been preprocessed.
.br
.I Reader
can only handle papers written in
.I troff
with standard
.RB ( -ms ,
.BR -mm ,
.BR -me )
macro packages.
