#define FLOAT 	1 
#define DOUBLE 	2 
#define CHAR 	3 
#define SHORT 	4 
#define INT 		5 
#define UNSIGNED 	6 
#define POINTER 	7 
#define VOID 	8 
#define STRUCT 	9 
#define UNION 	10 
#define FUNCTION 	11 
#define ARRAY 	12 
#define ENUM 	13 
#define LONG 	14 
#define CONST 	15 
#define VOLATILE 	16 
#define ID 		32 
#define FCON 	34 
#define ICON 	35 
#define SCON 	36 
#define INCR 	39 
#define DECR 	48 
#define DEREF 	49 
#define ANDAND 	50 
#define OROR 	51 
#define LEQ 		52 
#define EQL 		53 
#define NEQ 		54 
#define GEQ 		55 
#define RSHIFT 	56 
#define LSHIFT 	57 
#define ELLIPSIS 	64 
#define SIZEOF 	65 
#define ASM 		66 
#define AUTO 	67 
#define BREAK 	68 
#define CASE 	69 
#define CONTINUE 	70 
#define DEFAULT 	71 
#define DO 		72 
#define ELSE 	73 
#define EXTERN 	74 
#define FOR 		75 
#define GOTO 	76 
#define IF 		77 
#define REGISTER 	78 
#define RETURN 	79 
#define SIGNED 	80 
#define STATIC 	81 
#define SWITCH 	82 
#define TYPEDEF 	83 
#define WHILE 	84 
#define EOI 		127 
