.TH ADVENTURE 6
.CT 1 games
.SH NAME
adventure, zork, rogue, wump \- dungeon-exploration games
.SH SYNOPSIS
.B /usr/games/adventure
.PP
.B /usr/games/zork
.PP
.B /usr/games/rogue
.PP
.B /usr/games/wump
.SH DESCRIPTION
.I Adventure
is the grandaddy of dungeon-exploration games, part
of the object of which is to puzzle out the object and the rules.
.I Zork
marks the zenith of the genre.
.PP
.I Rogue
requires a cursor-addressed terminal to
show fragments of the cave map.
Indicia published at the bottom of the screen are
the cave level being explored, the amount of gold accumulated,
armor class,
and measures of your potency: `hit points', strength,
and experience level.
Type 
.L ?
for more help.
.PP
The
.I wump
cave is inhabited by a Wumpus and by Super Bats that like to pick you up
and drop you somewhere else.
You wander among the rooms, trying to
shoot the Wumpus with an arrow, meanwhile avoiding
being eaten by the Wumpus and falling
into
Bottomless Pits.
.SH FILES
.TF  /usr/games/lib/rogue_roll
.TP
.F adv.susp
.TP
.F rogue.save
.TP
.F /usr/games/lib/rogue_roll
.SH SEE ALSO
.B readnews -n net.games.rogue
.SH BUGS
You take these games where and as you find them.
