.TH ALTRAN 1 alice
.SH NAME
altran \- language for algebraic manipulation
.SH SYNOPSIS
.B altran
[
.I option
]
... file ...
.SH DESCRIPTION
.I Altran
compiles the language described in the reference
via Fortran as an intermediate language.
The
.I files
may have names ending in
.BR .al ,
for Altran source,
.BR .f ,
for Fortan source, or
.B .o
for binary object files.
The output normally includes
a .f file for each .al file,
a .o file for each old or new .f file,
an executable file
.BR a.out ,
and a listing file
whose name ends in
.B .list 
for each .al file.
.PP
All the
.I options
of
.IR f77 (1)
and
.IR ld (1)
are accepted with the same meanings.
.PP
The executable
.BR a.out
file accepts two parameters.
One is of the form
.BI p= n
where
.I n
is the number of decimal digits of precision to be used for long
integers,
.if n .RI 18<= n <= 900,
.if t .RI 18\(<= n \(<=900,
default 18.
The other parameter is of the form
.BI w= n
where
.I n
is the workspace size in thousands of words,
.if n .RI 10<= n <=800,
.if t .RI 10\(<= n \(<=800,
default 50.
.SH FILES
.ta \w'/usr/lib/libal.a   'u
.nf
/usr/lib/altran	the compiler proper
/usr/lib/libal.a	library
fort.[789]	intermediate files
*.al
*.f
*.o
*.list
.fi
.DT
.SH SEE ALSO
.IR f77 (1), 
.IR ld (1)
.br
W. S Brown,
.I ALTRAN User's Manual,
Bell Laboratories, Murray Hill, NJ,
1977
.SH BUGS
Run-time output is voluminous.
