.TH ASA 1
.SH NAME
asa \- interpret ASA control characters
.SH SYNOPSIS
.B asa
[
.I file
]
...
.SH DESCRIPTION
.I Asa
takes files which were written with ASA carriage control characters,
usually by FORTRAN programs, converts them to a form suitable for printing
on a terminal, line printer, and so on, and writes the results on the
standard output.
.PP
The control characters handled are:
.PP
	\' \'	single space
.br
	\'0\'	double space
.br
	\'-\'	triple space
.br
	\'+\'	overprint the previous line
.br
	\'1\'	start a new page
.PP
If no file names are given, the standard input is used.
.PP
Each input
file given starts a new page.
A skip to a new page on the first line of the
first input file is ignored.
