.TH BANNER 6
.CT 1 misc
.SH NAME
banner, rot, rnd, bigp \- print in large type
.SH SYNOPSIS
.B /usr/games/banner
[
.BI - font
]
.I text
[
.B | /usr/games/rot
.B | /usr/games/rnd
.I height width
]
.PP
.B /usr/games/bigp
[
.I text
]
.SH DESCRIPTION
.I Banner
prints its arguments, one per line, in
.PP
.EX
 #                                   #
  #                                  #
  #    ###  # ##   ## #  ###        ####  #   # # ##   ###
  #       # ##  # #  ## #   #        #    #   # ##  # #   #
  #    #### #     #   # ####         #    #   # #   # ####
  #   #   # #     #   # #            #  # #  ## #   # #       ##
   #   ###  #      ####  ###          ##   ## # ####   ###    ##
                      #                       # #
                  ####                     ###  #
.EE
.PP
The
.I font
may be selected from
.FR /usr/jerq/font ;
see
.IR font (9.5).
.PP
.I Rot
rotates its input clockwise ninety degrees.
.IP
.L
banner Sideways | rot
.PP
runs down the page, and
.IP
.L
banner Upside Down | rot | rot
.PP
is disconcerting.
.PP
.I Rnd
scales the non-white-space characters in its input by integral
.I height
and
.IR width.
.PP
.I Bigp
generates
banners suitable for printing on a line-printer.
Its output is approximately the same as
.IP
.L
banner -defont text | rot | rnd 2 4
.PP
If no arguments are supplied,
.I bigp
creates a banner from the standard input.
