.TH BCD 6
.CT 1 misc
.SH NAME
bcd, ppt, morse \- convert to antique media
.SH SYNOPSIS
.B /usr/games/bcd
.I text
.PP
.B /usr/games/ppt
.PP
.B /usr/games/morse
.SH DESCRIPTION
.I Bcd
converts the literal
.I text
into a tangible form familiar to old-timers.
.PP
.I Ppt
converts the standard input into yet another old standard.
.PP
.I Morse
converts the standard input into a pronounceable two-symbol code.
.SH "SEE ALSO"
.IR dd (1)
