.TH BIANCHI 6
.CT 1 games
.SH NAME
bianchi \- espresso, steamed milk, hot water
.SH SYNOPSIS
.B "make mess"
.SH DESCRIPTION
This machine makes espresso, hot water, and steamed milk.
It is attached to the cold water supply.
The shut off valve is actuated by the yellow handle under the
sink.
.PP
The power switch is a two position switch on the lower left portion
of the front face of the cabinet.
At the 0 position, the machine is powered off.
.PP
The push button switch near the center of the upper front face
enables water to flow though the coffee receptacles.
It does not automatically shut off.
.PP
The handle on the right side of the base enables cold water to enter the
machine should the pump fail.
It should not normally be used.
.PP
Users accustomed to the previous machines should be warned that
this one requires considerably less coffee per cup.
The bayonet mounted ground coffee holders will be very hard to
attach if overfilled.
.SH WARNING!
The steam and hot water supplies are both extremely hot and capable
of high pressure.
Turn them on slowly.
The unwary user may suffer loss of skin or eyesight.
.SH BUGS
When first powered on it takes 15 minutes to warm up.
The last person leaving at night should turn the machine
off.
