.TH CARDS 6
.CT 1 games
.SH NAME
canfield, fish \- card games
.SH SYNOPSIS
.B /usr/games/fish
.PP
.B /usr/games/canfield
.SH DESCRIPTION
.PP
The object of the children's card game
.I fish
is to accumulate `books' of 4 cards of equal rank.
At each turn one player
selects a card from his hand, and asks the other player for
all cards of that rank.
If the other player has some, he hands them all over
and the first player makes another request.
The turn ends when
the second player has no card of the rank requested;
he replies, `Go fish!'
The first
player then draws a card from the `pool' of undealt cards.
If this is the card he had last requested, he draws again.
.PP
The ranks are called 
.LR a ,
.LR 2 ,
\&...,
.LR 10 , 
.LR j ,
.LR q ,
.LR k .
Hitting
return requests information about the state of the game.
Typing 
.L p
as a first
guess gets `pro' level play.
.PP
.I Canfield
is a solitaire game.
It requires a cursor-addressed terminal.
