.TH CRABS 9.6
.CT 1 games
.SH NAME
crabs \- graphical marine adventure game
.SH SYNOPSIS
.B crabs
[
.B -i
]
[
.B -s
.I duration
]
[
.B -v
.I velocity
]
[
.I number
]
.SH DESCRIPTION
In
.IR crabs ,
difficult situations are encountered in trying to kill or capture
crustaceans swarming in a murky sea.
You will have to work very
rapidly to keep your territory free of seabed intruders.
At first,
you may even find it hard to keep a clear view of your surroundings, but
later discoveries about the spirit of the game will suggest a solution.
.PP
There are several options.
.TP
.B -i
causes the intruders to play intelligently, allowing them to avoid detection.
.TP
.B -s
simplifies the game for the first
.I duration
time intervals.
Default is 0.
5-10 is recommended for beginners, although
you may want to forgo this option the first time, just to see how interesting
it can get.
.TP
.B -v
adjusts the velocity of the crabs, 1 being fastest.
Default is 5.
.PP
.I Number
specifies the number of intruders.
Default is 30.
