.TH DOCTOR 6
.CT 1 games
.SH NAME
doctor, tso \- psychiatric consultation
.SH SYNOPSIS
.B /usr/games/doctor
.PP
.B /usr/games/tso
.SH DESCRIPTION
.I Doctor
will understandingly explore most anything with you.
Just type your thoughts followed by double carriage
returns.
.PP
.I Tso,
on the other hand, has a will of its own.
