.TH FESTOON 6
.CT 1 games
.SH NAME
festoon \- memo writer
.SH SYNOPSIS
.B festoon
length percent
.SH DESCRIPTION
.I Festoon
prepares a memorandum on any undesired topic, containing
.I length
sentences and a specified
.I percent
of new nouns.
A total effect might radically monoarchate this qualitativeness.
.SH SEE ALSO
.IR wwb (1)
