.TH GEBACA 9.6
.CT 1 games
.SH NAME
gebaca, gebam \- get back at corporate america
.SH SYNOPSIS
.B /usr/games/gebaca
.PP
.B demo gebam
.SH DESCRIPTION
.I Gebaca
is an arcade-type shoot-em-down with familiar characters.
It runs on Teletype 5620 terminals in
native mode only.
Use the mouse to dodge and shoot.
.PP
.I Gebam
is a cheap ripoff that runs under
.IR mux (9.1).
