.TH HANGMAN 6 bowell
.CT 1 games
.SH NAME
hangman, ana, word_clout \- word games
.SH SYNOPSIS
.B /usr/games/hangman
[
.I arg
]
.PP
.B /usr/games/ana
[
.I n
]
.PP
.B /usr/games/word_clout
.SH DESCRIPTION
.I Hangman
chooses a word at least seven letters
long from a dictionary.
You then guess letters one at a time.
.PP
The optional argument
.I arg
names an alternate dictionary.
The special name
.L \-a
gets a very large
dictionary.
.PP
.I Ana
reads words, one per line, from standard input and prints
anagrams on standard output.
The number
.I n,
which also may be given in standard input, limits the
number of words in the anagrams.
.PP
.I Word_clout
traces connections in a thesaurus to find
just words.
Need to express unpleasant feelings so they seem auspicious?
.I Word_clout
suggests calling them `warm'.
The program will give instructions in its uses, which
include service as a thesaurus.
.SH FILES
.TP
.F /usr/dict/words
.TP
.F /usr/dict/web2
alternate dictionary for hangman
.F /usr/lib/spell/amspell
.SH BUGS
.I Hangman
runs hyphenated compounds together.
