.TH IMP 6
.CT 1 mail
.SH NAME
imp \- interactive mail program
.SH SYNOPSIS
.B /usr/games/imp
.SH DESCRIPTION
.I Imp
attempts to avoid the complexity of using modern mail programs by 
asking for control information interactively rather than by
expecting the user to supply it on the command line or by
using defaults that are sometimes not exactly what the user has
in mind.
Thus, 
.I imp
prompts for the userid of the mail target, the target's home
machine, the userid and home machine of the sender, and the postmark.
The message can be entered from the standard input as in
.IR mail (1)
or taken from a file.
.PP
A particularly useful application of
.I imp
is to cause mail that you send from some borrowed account
to appear as if it came from you on your home machine, thereby
reducing the possibility of confusing the recipient.
.SH FILES
.F /dev/tty
.SH "SEE ALSO"
.IR mail (1),
.IR upas (8)
.SH BUGS
Probably.
Try sending mail to yourself before using
.I imp
to send mail to others.
