.TH NUMBER 6
.CT 1 inst_info
.SH NAME
number \(mi convert Arabic numerals to English
.SH SYNOPSIS
.B number
.SH DESCRIPTION
.I Number
copies the standard input to the standard output,
replacing all decimal numbers by their spelled-out
equivalent.
Punctuation is added to make the output sound well when
played through
voice synthesizers.
