.TH PAPER 1 
.SH NAME
paper \- list input on HP2621P printer
.SH SYNOPSIS
.B paper
[
.I file
]
...
.SH DESCRIPTION
.I paper
prints the argument files (or the standard input
if there are no arguments) on the user's terminal
which is assumed to be a HP2621P.
A handshaking protocol is used to prevent overrunning
the terminal's buffer and dropping characters.
