.  \"ident	"%W%"
.  \"Copyright (c) 1984 AT&T
.  \"All Rights Reserved
.  \"THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
.  \"The copyright notice above does not evidence any
.  \"actual or intended publication of such source code.
.TH PIPESTREAM 3I+ "C++ Stream Library" " "
.SH NAME
pipestream \- iostream specialized as circular buffer
.SH SYNOPSIS
.ft B
.ta1i 2i
.nf
#include <iostream.h>
#include <pipestream.h>

class pipestream : public iostream {
public:
		pipestream();
		pipestream(char* ptr, int len);
	pipebuf*	rdbuf();
	} ;
.fi
.ft R
.SH DESCRIPTION
\f(CWpipestream\fR 
specializes
\f(CWiostream\fR
to use a circular buffer (\f(CWpipebuf\fR).
.PP
Assume
.br
\(em \fBps\fR is a \f(CWpipestream\fR.
.br
\(em \fBptr\fR is a \f(CWchar*\fR.
.br
\(em \fBlen\fR is an \f(CWint\fR.
.br
\(em \fBpb\fR is a \f(CWpipebuf*\fR.
.PP
Constructors:
.TP
\fBpipestream()\fR
Constructs a \f(CWpipestream\fP with an empty \f(CWpipebuf\fR.
.TP
\fBpipestream(ptr,len)\fR
Constructs a \f(CWpipestream\fP with a \f(CWpipebuf\fR
that uses the \fBlen\fR bytes
at \fBptr\fR as a reserve area.
.PP
Members:
.TP
\fBpb=ps.rdbuf()\fR
Returns the associated \fBpipebuf\fR. \fBpipebuf::rdbuf\fR has
the same semantics as \fBstreambuf::rdbuf\fR, but the type of
the result is more precise.
.SH SEE ALSO
pipebuf(3C++)
ios(3C++)
