.TH RSCAN 1 polya
.CT 1 graphics
.SH NAME
rscan, pix \- scan page on ricoh scanner and display on 5620
.SH SYNOPSIS
.B rscan
[
.B -D
]
[
.B -r
.I n
]
[
.B name
]
.SH DESCRIPTION
.I Rscan
reads data from the Ricoh scanner and writes it in file
.I name
with a header as described in
.IR pictures (5).
If no
.I name
is given, it calls the file
.B Junk.
The flag
.B -D
turns on dither mode.
The flag
.BI -r
selects the scanner resolution.
Values of
.I n
are 0 for 200\(mu200 dots per inch, 1 for 200\(mu100 DPI, 2 for 300\(mu300 DPI (default),
and 3 for 240\(mu240 DPI.
The data from the scanner are bytes with the low order bit corresponding
to the left edge of the paper.
There are 324 bytes/scan line at the default resolution.
.PP
.I Pix
displays a scanned page in a window on the 5620 terminal.
Button 3 displays a menu for moving around in the data.
.SH "SEE ALSO"
.IR imscan (1),
.IR pictures (5)
