.  \"ident	"%W%"
.  \"Copyright (c) 1984 AT&T
.  \"All Rights Reserved
.  \"THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
.  \"The copyright notice above does not evidence any
.  \"actual or intended publication of such source code.
.TH STDIOBUF 3I+ "C++ Stream Library" " "
.SH NAME
stdiobuf \- iostream specialized to stdio FILE
.SH SYNOPSIS
.ft B
.ta1i 2i
.nf
#include <iostream.h>
#include <strstream.h>
#include <stdio.h>

class stdiobuf : streambuf {
		stdiobuf(FILE* f);
	FILE*	stdiofile();
}
.fi
.ft R
.SH DESCRIPTION
Operations on a
\f(CWstdiobuf\fR
are reflected on
the underlying
\f(CWFILE\fR.
A \f(CWstdiobuf\fR is constructed in unbuffered mode, which causes all operations
to be immediately reflected in the \f(CWFILE\fR.
\fBseek\fRs are translated into \fBfseek\fRs.
\fBsetbuf\fR has its usual meaning.  If it supplies a reserve
area buffering will be turned back on.
.SH SEE ALSO
filebuf(3C++)
istream(3C++)
ostream(3C++)
ssbuf.pub(3C++)
