.TH TELNET 1 research
.SH NAME
telnet \- user interface to the telnet protocol
.SH SYNOPSIS
.I telnet
[
.I host
[
.I port
]
]
.SH DESCRIPTION
.I Telnet
communicates with another host using the TELNET protocol.
If
.I telnet
is invoked without arguments, it prompts 
.LR telnet> .
In this mode it accepts the commands listed below.
If it is invoked with arguments, it performs an
.L open
command (see below) with those arguments.
.PP
Once a connection has been opened,
.I telnet
sends typed text to the remote host.
To issue
.I telnet
commands when in input mode, precede them with the
.I telnet
escape character, initially control-].
.PP
The following commands are available.
Only a unique prefix of the command need be typed.
.TP
\f5open\fP \fIhost\fP [ \fIport\fP ]
Open a connection to the named host.
A missing port number defaults to a
TELNET server.
The
.I host
may be a host name
or an Internet address specified in the `dot notation'.
.TP
.B close
Close a TELNET session and return to command mode.
.TP
.B quit
Close any open TELNET session and exit
.IR telnet .
.TP
\f5escape\fP [ \fIescape-char\fP ]
Set the
.I telnet
escape character.
Control characters may
be specified as 
.L ^
followed by a single
letter.
.TP
.B status
Show the current status of
.IR telnet .
.TP
.B options
Toggle viewing of TELNET options processing.
When viewing is on, all TELNET option negotiations
will be displayed.
Options sent by
.I telnet
are displayed as SENT, options
received as
RCVD.
.TP
.B crmod
Toggle carriage return mode.
When this mode is on,
carriage return characters received from the remote
host map into a carriage return and a line
feed.
.TP
\f5?\fP [ \fIcommand\fP ]
Get help.
With no arguments, print a help summary.
With a command specified,
print information about that command only.
.SH FILES
.F /usr/inet/lib/*
.SH SEE ALSO
.IR dcon (1),
.IR netstat (8)
