.TH APNEWS 1 
.SH NAME
apnews \- present recent AP wire stories
.SH SYNOPSIS
.B apnews
.SH DESCRIPTION
.I Apnews
is designed to skim the current news on the AP wire.
On a video terminal, it presents a top half screen of twenty
story slugs (two-word labels); typing the number of one of
these slugs displays the first ten lines of the story
on the bottom half screen.
Successive ten line pages of the story are obtained
by hitting carriage return.
Successive twenty slug top half pages are obtained
by hitting \fBm\fR
(if you aren't reading a story, carriage return will do).
You can return to the current top half page with
\fB\&.\fR, or to the first top half page with \fBt\fR.
.PP
If you type
\fBs\fI keywords\fR
a search through today's stories is done for stories
with those words; a menu of such stories is presented.
You can use the story now being displayed as a source
of keywords by typing \fBy\fR.
.PP
To get a copy of a story you are reading in your own
file space, type
\fBc\fI xyz\fR which will
copy the story to file or directory \fIxyz\fR
(appending if \fIxyz\fR is a file and not empty).
The command '?' prints some help.
.SH FILES
/data/ap
.SH "SEE ALSO"
ap.keys(5)
.SH BUGS
These are left as an exercise for the reader.  Please report to mel.
