'\"macro stdmacro
.if n .pH g1.binarsys %W%
.nr X
.if \nX=0 .ds x} binarsys 4 "Essential Utilities" "\&"
.if \nX=1 .ds x} binarsys 4 "Essential Utilities"
.if \nX=2 .ds x} binarsys 4 "" "\&"
.if \nX=3 .ds x} binarsys "" "" "\&"
.TH \*(x}
.SH NAME
\f4binarsys\f1 \- remote system information for the \f4ckbinarsys\f1 command
.SH DESCRIPTION
\f4binarsys\f1
contains lines of the form:
.sp .5
.ce
\f2remote_system_name\f4:\f2val\f1
.sp .5
where \f2val\f1 is either \f4Y\f1 or \f4N\f1.
This line indicates whether that particular remote system can properly
deal with messages having binary content.
The absence of an entry for a particular system 
or absence of the \f4binarsys\f1 file altogether will imply \f4N\f1o.
.PP
Blank lines or lines beginning with \f4#\f1 are considered
comments and ignored.
Should a line of \f4Default=y\f1 be encountered,
the default condition for missing entries described in the previous paragraph
is reversed to be \f4Y\f1es.
Another line of \f4Default=n\f1 will restore the default condition to \f4N\f1o.
.PP
\f4mail\f1 is distributed with the \f4binarsys\f1
file containing only a \f4Default=y\f1 line.
.SH FILES
\f4/etc/mail/binarsys\f1
.SH SEE ALSO
\f4ckbinarsys\fP(1M), \f4mailsurr\fP(4)
.br
\f4mail\fP(1) in the \f2User's Reference Manual\f1.
.Ee
