/* The Plum Hall Validation Suite for C
 * Unpublished copyright (c) 1986-1991, Chiron Systems Inc and Plum Hall Inc.
 * VERSION: 4
 * DATE: 1993-01-01
 * The "ANSI" mode of the Suite corresponds to the official ANSI C, X3.159-1989.
 * As per your license agreement, your distribution is not to be moved or copied outside the Designated Site
 * without specific permission from Plum Hall Inc.
 */

/****************************************************************************
 ** Self-checking C source code generated by EGEN component of             **
 **    The Plum Hall Validation Suite for C.                               **
 **    (C) 1986-1988 Chiron Systems Inc and Plum Hall Inc                  **
 **    EGEN Version 1.09.000  88/08/21                                     **
 **                                                                        **
 **    EGEN -P -R1 -V -A -N5 -Dinteger.gen ( @ @ ) @ ( @ @ )               **
 ****************************************************************************/
#include "defs.h"


int main()
	{
	extern char *Filename;
	auto unsigned int ui;
	static unsigned int * pui;
	auto unsigned int ** ppui;
	auto int i;
	static int * pi;
	auto int ** ppi;
	auto unsigned short us;
	static unsigned short * pus;
	auto unsigned short ** ppus;
	auto short s;
	static short * ps;
	auto short ** pps;
	auto unsigned char uc;
	static unsigned char * puc;
	auto unsigned char ** ppuc;
	auto char c;
	static char * pc;
	auto char ** ppc;
	auto unsigned long ul;
	static unsigned long * pul;
	auto unsigned long ** ppul;
	auto long l;
	static long * pl;
	auto long ** ppl;
	register int rint1;
	register int rint2;
	register int rint3;
	register int rint4;
	register int rint5;

	ui = ivalue(100);
	pui = &ui;
	ppui = &pui;
	i = ivalue(10);
	pi = &i;
	ppi = &pi;
	us = lvalue(33000);
	pus = &us;
	ppus = &pus;
	s = ivalue(13);
	ps = &s;
	pps = &ps;
	uc = ivalue(128);
	puc = &uc;
	ppuc = &puc;
	c = ivalue(20);
	pc = &c;
	ppc = &pc;
	ul = lvalue(65000L);
	pul = &ul;
	ppul = &pul;
	l = lvalue(97L);
	pl = &l;
	ppl = &pl;
	rint1 = ivalue(1);
	rint2 = ivalue(2);
	rint3 = ivalue(3);
	rint4 = ivalue(4);
	rint5 = ivalue(5);
	Filename = "int1.c";

	/* post++ 0x65 => 0x64 */
	/* 0x64 && 128 => 1 */
	/* 10 / 3 => 3 */
	/* 1 < 3 => 1 */
	/* 1 << 1 => 2 */
	iequals(__LINE__, ((((*pui)++ ) && *puc) << (rint1 < (i / rint3))), 2);
	iequals(__LINE__, ui, (unsigned)101);

	/* 4 % 1 => 0 */
	/* 0 | 0x80 => 128 */
	/* post-- 19 => 20 */
	/* 128 / 1 => 128 */
	iequals(__LINE__, (((rint4 % rint1) | uc) / (((c)-- ) || *pl)), 128);
	iequals(__LINE__, c, 19);

	/* 19 != 0xfde8L => 1 */
	/* 97L *= 1 => 97L */
	/* 19 ^ 13 => 30 */
	/* 30 ^ 0x80e8 => 0x80f6 */
	/* 97L | 0x80f6 => 33015L */
	lequals(__LINE__, ((**ppl *= (*pc != *pul)) | ((c ^ **pps) ^ *pus)), 33015L);
	lequals(__LINE__, l, 97L);

	/* post-- 0x80e7 => 0x80e8 */
	/* 19 &= 0x80e8 => 0 */
	iequals(__LINE__, ((*pc &= ((**ppus)-- )) && (ul &= (rint2 *= **ppi))), 0);
	iequals(__LINE__, rint2, 2);
	lequals(__LINE__, ul, 65000L);
/* 	iequals(__LINE__, us, (unsigned)32999); DELETED - NON-PORTABLE */
	iequals(__LINE__, c, 0);

	/* 13 % 13 => 0 */
	/* 0x80e7 <= 0 => 0 */
	/* 2 &= 5 => 0 */
	/* 0 *= 0 => 0 */
	/* 0 ^ 0 => 0 */
	iequals(__LINE__, ((us <= (s % *ps)) ^ (*pc *= (rint2 &= rint5))), 0);
	iequals(__LINE__, rint2, 0);
	iequals(__LINE__, c, 0);

	return 	report(Filename);
	}
