/* The Plum Hall Validation Suite for C
 * Unpublished copyright (c) 1986-1991, Chiron Systems Inc and Plum Hall Inc.
 * VERSION: 4
 * DATE: 1993-01-01
 * The "ANSI" mode of the Suite corresponds to the official ANSI C, X3.159-1989.
 * As per your license agreement, your distribution is not to be moved or copied outside the Designated Site
 * without specific permission from Plum Hall Inc.
 */

/****************************************************************************
 ** Self-checking C source code generated by EGEN component of             **
 **    The Plum Hall Validation Suite for C.                               **
 **    (C) 1986-1988 Chiron Systems Inc and Plum Hall Inc                  **
 **    EGEN Version 1.09.000  88/08/21                                     **
 **                                                                        **
 **    EGEN -P -R12 -V -A -N5 -Dinteger.gen ( @ @ ) @ ( @ @ )              **
 ****************************************************************************/
#include "defs.h"


int main()
	{
	extern char *Filename;
	auto unsigned int ui;
	static unsigned int * pui;
	auto unsigned int ** ppui;
	auto int i;
	static int * pi;
	auto int ** ppi;
	auto unsigned short us;
	static unsigned short * pus;
	auto unsigned short ** ppus;
	auto short s;
	static short * ps;
	auto short ** pps;
	auto unsigned char uc;
	static unsigned char * puc;
	auto unsigned char ** ppuc;
	auto char c;
	static char * pc;
	auto char ** ppc;
	auto unsigned long ul;
	static unsigned long * pul;
	auto unsigned long ** ppul;
	auto long l;
	static long * pl;
	auto long ** ppl;
	register int rint1;
	register int rint2;
	register int rint3;
	register int rint4;
	register int rint5;

	ui = ivalue(100);
	pui = &ui;
	ppui = &pui;
	i = ivalue(10);
	pi = &i;
	ppi = &pi;
	us = lvalue(33000);
	pus = &us;
	ppus = &pus;
	s = ivalue(13);
	ps = &s;
	pps = &ps;
	uc = ivalue(128);
	puc = &uc;
	ppuc = &puc;
	c = ivalue(20);
	pc = &c;
	ppc = &pc;
	ul = lvalue(65000L);
	pul = &ul;
	ppul = &pul;
	l = lvalue(97L);
	pl = &l;
	ppl = &pl;
	rint1 = ivalue(1);
	rint2 = ivalue(2);
	rint3 = ivalue(3);
	rint4 = ivalue(4);
	rint5 = ivalue(5);
	Filename = "int12.c";

	/* 97L < 0x64 => 1 */
	/* 1 ^ 0xfde8L => 0xfde9L */
	/* neg 20 => -20 */
	/* 20 / -20 => -1 */
	/* 0xfde9L != -1 => 1 */
	iequals(__LINE__, (((**ppl < **ppui) ^ *pul) != (c / ( - c))), 1);

	/* 10 + 97L => 107L */
	/* 20 /= 107L => 0 */
	/* 0x80 += 10 => 0x8a */
	/* 0x80e8 = 0x8a => 0x8a */
	/* 0 % 0x8a => 0x0 */
	iequals(__LINE__, ((c /= (**ppi + *pl)) % (*pus = (**ppuc += **ppi))), 0x0);
	iequals(__LINE__, uc, (unsigned)138);
	iequals(__LINE__, us, (unsigned)138);
	iequals(__LINE__, c, 0);

	/* post-- 96L => 97L */
	/* 0 = 97L => 97 */
	/* 1 | 97 => 97 */
	iequals(__LINE__, ((**ppuc || (**ppuc == ul)) | (c = ((l)-- ))), 97);
	lequals(__LINE__, l, 96L);
	iequals(__LINE__, c, 97);

	/* 3 %= 0x8a => 3 */
	/* 1 -= 3 => -2 */
	/* 4 %= 0x8a => 4 */
	/* 13 += 4 => 17 */
	/* -2 * 17 => -34 */
	iequals(__LINE__, ((rint1 -= (rint3 %= us)) * (s += (rint4 %= uc))), -34);
	iequals(__LINE__, rint4, 4);
	iequals(__LINE__, s, 17);
	iequals(__LINE__, rint3, 3);
	iequals(__LINE__, rint1, -2);

	/* 10 % 4 => 2 */
	/* 138 < 2 => 0 */
	/* 17 % 0xfde8L => 0x11L */
	/* 4 < 0x11L => 1 */
	/* 0 <= 1 => 1 */
	iequals(__LINE__, ((uc < (*pi % rint4)) <= (rint4 < (**pps % ul))), 1);

	return 	report(Filename);
	}
