/* The Plum Hall Validation Suite for C
 * Unpublished copyright (c) 1986-1991, Chiron Systems Inc and Plum Hall Inc.
 * VERSION: 4
 * DATE: 1993-01-01
 * The "ANSI" mode of the Suite corresponds to the official ANSI C, X3.159-1989.
 * As per your license agreement, your distribution is not to be moved or copied outside the Designated Site
 * without specific permission from Plum Hall Inc.
 */

/****************************************************************************
 ** Self-checking C source code generated by EGEN component of             **
 **    The Plum Hall Validation Suite for C.                               **
 **    (C) 1986-1988 Chiron Systems Inc and Plum Hall Inc                  **
 **    EGEN Version 1.09.000  88/08/21                                     **
 **                                                                        **
 **    EGEN -P -R2 -V -A -N5 -Dinteger.gen ( @ @ ) @ ( @ @ )               **
 ****************************************************************************/
#include "defs.h"


int main()
	{
	extern char *Filename;
	auto unsigned int ui;
	static unsigned int * pui;
	auto unsigned int ** ppui;
	auto int i;
	static int * pi;
	auto int ** ppi;
	auto unsigned short us;
	static unsigned short * pus;
	auto unsigned short ** ppus;
	auto short s;
	static short * ps;
	auto short ** pps;
	auto unsigned char uc;
	static unsigned char * puc;
	auto unsigned char ** ppuc;
	auto char c;
	static char * pc;
	auto char ** ppc;
	auto unsigned long ul;
	static unsigned long * pul;
	auto unsigned long ** ppul;
	auto long l;
	static long * pl;
	auto long ** ppl;
	register int rint1;
	register int rint2;
	register int rint3;
	register int rint4;
	register int rint5;

	ui = ivalue(100);
	pui = &ui;
	ppui = &pui;
	i = ivalue(10);
	pi = &i;
	ppi = &pi;
	us = lvalue(33000);
	pus = &us;
	ppus = &pus;
	s = ivalue(13);
	ps = &s;
	pps = &ps;
	uc = ivalue(128);
	puc = &uc;
	ppuc = &puc;
	c = ivalue(20);
	pc = &c;
	ppc = &pc;
	ul = lvalue(65000L);
	pul = &ul;
	ppul = &pul;
	l = lvalue(97L);
	pl = &l;
	ppl = &pl;
	rint1 = ivalue(1);
	rint2 = ivalue(2);
	rint3 = ivalue(3);
	rint4 = ivalue(4);
	rint5 = ivalue(5);
	Filename = "int2.c";

	/* 5 > 97L => 0 */
	/* 4 -= 0 => 4 */
	/* 2 ^ 20 => 22 */
	/* 1 |= 22 => 23 */
	/* 4 + 23 => 27 */
	iequals(__LINE__, ((rint4 -= (rint5 > l)) + (rint1 |= (rint2 ^ *pc))), 27);
	iequals(__LINE__, rint1, 23);
	iequals(__LINE__, rint4, 4);

	/* 13 == 0x64 => 0 */
	/* 0 & 20 => 0 */
	/* neg 10 => -10 */
	/* 5 &= -10 => 4 */
	/* 0 <= 4 => 1 */
/* 	iequals(__LINE__, (((**pps == ui) & c) <= (rint5 &= ( - *pi))), 1); /* non-portable */
/* 	iequals(__LINE__, rint5, 4); /* non-portable */

	/* neg 0x80 => -128 */
	/* 4 != -128 => 1 */
	iequals(__LINE__, ((rint4 != ( - **ppuc)) || ((s / rint2) / ui)), 1);

	/* 10 < 10 => 0 */
	/* 0x64 += 0 => 0x64 */
	/* 0x64 < 1 => 0 */
	iequals(__LINE__, ((ui += (*pi < i)) < (ul || (rint1 - i))), 0);
	iequals(__LINE__, ui, (unsigned)100);

	/* pre++ 10 => 11 */
	/* 0x64 |= 11 => 0x6f */
	/* 0x80 / 23 => 5 */
	/* 5 * 97L => 485L */
	/* 0x6f + 485L => 596L */
	lequals(__LINE__, ((**ppui |= ( ++ *pi)) + ((uc / rint1) * l)), 596L);
	iequals(__LINE__, i, 11);
	iequals(__LINE__, ui, (unsigned)111);

	return 	report(Filename);
	}
