/* The Plum Hall Validation Suite for C
 * Unpublished copyright (c) 1986-1991, Chiron Systems Inc and Plum Hall Inc.
 * VERSION: 4
 * DATE: 1993-01-01
 * The "ANSI" mode of the Suite corresponds to the official ANSI C, X3.159-1989.
 * As per your license agreement, your distribution is not to be moved or copied outside the Designated Site
 * without specific permission from Plum Hall Inc.
 */

/****************************************************************************
 ** Self-checking C source code generated by EGEN component of             **
 **    The Plum Hall Validation Suite for C.                               **
 **    (C) 1986-1988 Chiron Systems Inc and Plum Hall Inc                  **
 **    EGEN Version 1.09.000  88/08/21                                     **
 **                                                                        **
 **    EGEN -P -R6 -V -A -N5 -Dinteger.gen ( @ @ ) @ ( @ @ )               **
 ****************************************************************************/
#include "defs.h"


int main()
	{
	extern char *Filename;
	auto unsigned int ui;
	static unsigned int * pui;
	auto unsigned int ** ppui;
	auto int i;
	static int * pi;
	auto int ** ppi;
	auto unsigned short us;
	static unsigned short * pus;
	auto unsigned short ** ppus;
	auto short s;
	static short * ps;
	auto short ** pps;
	auto unsigned char uc;
	static unsigned char * puc;
	auto unsigned char ** ppuc;
	auto char c;
	static char * pc;
	auto char ** ppc;
	auto unsigned long ul;
	static unsigned long * pul;
	auto unsigned long ** ppul;
	auto long l;
	static long * pl;
	auto long ** ppl;
	register int rint1;
	register int rint2;
	register int rint3;
	register int rint4;
	register int rint5;

	ui = ivalue(100);
	pui = &ui;
	ppui = &pui;
	i = ivalue(10);
	pi = &i;
	ppi = &pi;
	us = lvalue(33000);
	pus = &us;
	ppus = &pus;
	s = ivalue(13);
	ps = &s;
	pps = &ps;
	uc = ivalue(128);
	puc = &uc;
	ppuc = &puc;
	c = ivalue(20);
	pc = &c;
	ppc = &pc;
	ul = lvalue(65000L);
	pul = &ul;
	ppul = &pul;
	l = lvalue(97L);
	pl = &l;
	ppl = &pl;
	rint1 = ivalue(1);
	rint2 = ivalue(2);
	rint3 = ivalue(3);
	rint4 = ivalue(4);
	rint5 = ivalue(5);
	Filename = "int6.c";

	/* post++ 2 => 1 */
	/* 97L - 1 => 96L */
	/* post-- 1 => 2 */
	/* 0x80 ^= 2 => 0x82 */
	/* 96L ^ 0x82 => 226L */
	lequals(__LINE__, ((l - ((rint1)++ )) ^ (**ppuc ^= ((rint2)-- ))), 226L);
	iequals(__LINE__, rint2, 1);
	iequals(__LINE__, uc, (unsigned)130);
	iequals(__LINE__, rint1, 2);

	/* 0x80e8 < 5 => 0 */
	/* 3 ^ 0 => 3 */
	/* 0x80e8 - 10 => 0x80de */
	/* 20 == 0x80de => 0 */
	/* 3 >> 0 => 3 */
	iequals(__LINE__, ((rint3 ^ (**ppus < rint5)) >> (**ppc == (us - i))), 3);

	/* 4 <<= 1 => 8 */
	/* neg 5 => -5 */
	/* -5 >= 2 => 0 */
	/* 8 >> 0 => 8 */
	iequals(__LINE__, ((rint4 <<= (*pul || *pl)) >> (( - rint5) >= rint1)), 8);
	iequals(__LINE__, rint4, 8);

	/* post++ 11 => 10 */
	/* 0x80e8 ^ 10 => 0x80e2 */
	/* 0x82 % 13 => 0 */
	/* 0 < 13 => 1 */
	/* 0x80e2 == 1 => 0 */
	iequals(__LINE__, ((us ^ ((**ppi)++ )) == ((**ppuc % s) < s)), 0);
	iequals(__LINE__, i, 11);

	/* 11 != 13 => 1 */
	/* 97L *= 1 => 97L */
	/* pre-- 1 => 0 */
	/* neg 0 => 0 */
	/* 97L == 0 => 0 */
	iequals(__LINE__, ((*pl *= (i != s)) == ( - ( -- rint2))), 0);
	iequals(__LINE__, rint2, 0);
	lequals(__LINE__, l, 97L);

	return 	report(Filename);
	}
