/* The Plum Hall Validation Suite for C
 * Unpublished copyright (c) 1986-1991, Chiron Systems Inc and Plum Hall Inc.
 * VERSION: 4
 * DATE: 1993-01-01
 * The "ANSI" mode of the Suite corresponds to the official ANSI C, X3.159-1989.
 * As per your license agreement, your distribution is not to be moved or copied outside the Designated Site
 * without specific permission from Plum Hall Inc.
 */

/****************************************************************************
 ** Self-checking C source code generated by EGEN component of             **
 **    The Plum Hall Validation Suite for C.                               **
 **    (C) 1986-1988 Chiron Systems Inc and Plum Hall Inc                  **
 **    EGEN Version 1.09.000  88/08/21                                     **
 **                                                                        **
 **    EGEN -P -R12 -V -A -N5 -Dmixed.gen ( @ @ ) @ ( @ @ )                **
 ****************************************************************************/
#include "defs.h"


int main()
	{
	extern char *Filename;
	static float f1;
	auto float * pf1;
	static long stlong1;
	static float f2;
	auto float * pf2;
	static long stlong2;
	static float f3;
	static float * pf3;
	auto long stlong3;
	static float f4;
	static float * pf4;
	static long stlong4;
	static double d1;
	auto double * pd1;
	static long stlong5;
	static double d2;
	static double * pd2;
	static long stlong6;
	auto double d3;
	static double * pd3;
	static long stlong7;
	static double d4;
	static double * pd4;
	auto long stlong8;

	f1 = fvalue(1.100000E+000);
	pf1 = &f1;
	stlong1 = lvalue(1L);
	f2 = fvalue(2.200000E+000);
	pf2 = &f2;
	stlong2 = lvalue(2L);
	f3 = fvalue(3.300000E+000);
	pf3 = &f3;
	stlong3 = lvalue(3L);
	f4 = fvalue(4.400000E+000);
	pf4 = &f4;
	stlong4 = lvalue(4L);
	d1 = dvalue(1.100000000000000E+000);
	pd1 = &d1;
	stlong5 = lvalue(5L);
	d2 = dvalue(2.200000000000000E+000);
	pd2 = &d2;
	stlong6 = lvalue(6L);
	d3 = dvalue(3.300000000000000E+000);
	pd3 = &d3;
	stlong7 = lvalue(7L);
	d4 = dvalue(4.400000000000000E+000);
	pd4 = &d4;
	stlong8 = lvalue(8L);
	Filename = "mix12.c";

	/* 1L < 6L => 1 */
	/* 1 ^ 7L => 6L */
	/* neg 2.20000000000000E+000 => -2.20000000000000E+000 */
	/* 4.40000000000000E+000 / -2.20000000000000E+000 => -2.00000000000000E+000 */
	/* 6L != -2.00000000000000E+000 => 1 */
	iequals(__LINE__, (((stlong1 < stlong6) ^ stlong7) != (d4 / ( - *pd2))), 1);

	/* 8L + 4L => 12L */
	/* 7L /= 12L => 0L */
	/* 5L += 8L => 13L */
	/* 1L = 13L => 13L */
	/* 0L % 13L => 0L */
	lequals(__LINE__, ((stlong7 /= (stlong8 + stlong4)) % (stlong1 = (stlong5 += stlong8))), 0L);
	lequals(__LINE__, stlong5, 13L);
	lequals(__LINE__, stlong1, 13L);
	lequals(__LINE__, stlong7, 0L);

	/* post-- 12L => 13L */
	/* 13L = 13L => 13L */
	/* 1 | 13L => 13L */
	lequals(__LINE__, ((stlong4 || (stlong3 == stlong4)) | (stlong5 = ((stlong1)-- ))), 13L);
	lequals(__LINE__, stlong1, 12L);
	lequals(__LINE__, stlong5, 13L);

	/* 0L %= 8L => 0L */
	/* 3.30000E+000 -= 0L => 3.30000E+000 */
	/* 2L %= 3L => 2L */
	/* 12L += 2L => 14L */
	/* 3.30000E+000 * 14L => 4.62000E+001 */
	fequals(__LINE__, ((f3 -= (stlong7 %= stlong8)) * (stlong1 += (stlong2 %= stlong3))), 4.62000E+001);
	lequals(__LINE__, stlong2, 2L);
	lequals(__LINE__, stlong1, 14L);
	lequals(__LINE__, stlong7, 0L);
	fequals(__LINE__, f3, 3.30000E+000);

	/* 13L <= 14L => 1 */
	/* 8L &= 1 => 0L */
	/* post++ 7L => 6L */
	/* 3L % 6L => 3L */
	/* 0L <= 3L => 1 */
	iequals(__LINE__, ((stlong8 &= (stlong5 <= stlong1)) <= (stlong3 % ((stlong6)++ ))), 1);
	lequals(__LINE__, stlong6, 7L);
	lequals(__LINE__, stlong8, 0L);

	return 	report(Filename);
	}
