/* The Plum Hall Validation Suite for C
 * Unpublished copyright (c) 1986-1991, Chiron Systems Inc and Plum Hall Inc.
 * VERSION: 4
 * DATE: 1993-01-01
 * The "ANSI" mode of the Suite corresponds to the official ANSI C, X3.159-1989.
 * As per your license agreement, your distribution is not to be moved or copied outside the Designated Site
 * without specific permission from Plum Hall Inc.
 */

/****************************************************************************
 ** Self-checking C source code generated by EGEN component of             **
 **    The Plum Hall Validation Suite for C.                               **
 **    (C) 1986-1988 Chiron Systems Inc and Plum Hall Inc                  **
 **    EGEN Version 1.09.000  88/08/21                                     **
 **                                                                        **
 **    EGEN -P -R13 -V -A -N5 -Dmixed.gen ( @ @ ) @ ( @ @ )                **
 ****************************************************************************/
#include "defs.h"


int main()
	{
	extern char *Filename;
	static float f1;
	auto float * pf1;
	static long stlong1;
	static float f2;
	auto float * pf2;
	static long stlong2;
	static float f3;
	static float * pf3;
	auto long stlong3;
	static float f4;
	static float * pf4;
	static long stlong4;
	static double d1;
	auto double * pd1;
	static long stlong5;
	static double d2;
	static double * pd2;
	static long stlong6;
	auto double d3;
	static double * pd3;
	static long stlong7;
	static double d4;
	static double * pd4;
	auto long stlong8;

	f1 = fvalue(1.100000E+000);
	pf1 = &f1;
	stlong1 = lvalue(1L);
	f2 = fvalue(2.200000E+000);
	pf2 = &f2;
	stlong2 = lvalue(2L);
	f3 = fvalue(3.300000E+000);
	pf3 = &f3;
	stlong3 = lvalue(3L);
	f4 = fvalue(4.400000E+000);
	pf4 = &f4;
	stlong4 = lvalue(4L);
	d1 = dvalue(1.100000000000000E+000);
	pd1 = &d1;
	stlong5 = lvalue(5L);
	d2 = dvalue(2.200000000000000E+000);
	pd2 = &d2;
	stlong6 = lvalue(6L);
	d3 = dvalue(3.300000000000000E+000);
	pd3 = &d3;
	stlong7 = lvalue(7L);
	d4 = dvalue(4.400000000000000E+000);
	pd4 = &d4;
	stlong8 = lvalue(8L);
	Filename = "mix13.c";

	/* neg 4.40000E+000 => -4.40000E+000 */
	/* -4.40000E+000 != 2.20000E+000 => 1 */
	/* 1 * 1 => 1 */
	iequals(__LINE__, ((stlong3 || (stlong4 | stlong3)) * (( - *pf4) != *pf2)), 1);

	/* post-- 3.40000000000000E+000 => 4.40000000000000E+000 */
	/* 4L >= 4.40000000000000E+000 => 0 */
	iequals(__LINE__, ((stlong4 >= ((*pd4)-- )) && (d1 = (stlong7 ^= stlong8))), 0);
	lequals(__LINE__, stlong7, 7L);
	dequals(__LINE__, d1, 1.10000000000000E+000);
	dequals(__LINE__, d4, 3.40000000000000E+000);

	/* post-- 0L => 1L */
	/* 2.20000000000000E+000 && 1L => 1 */
	/* ! 8L => 0 */
	/* 7L ^= 0 => 7L */
	/* 1 == 7L => 0 */
	iequals(__LINE__, ((d2 && ((stlong1)-- )) == (stlong7 ^= ( ! stlong8))), 0);
	lequals(__LINE__, stlong7, 7L);
	lequals(__LINE__, stlong1, 0L);

	/* pre-- 3L => 2L */
	/* 8L >>= 2L => 2L */
	/* 4L != 2L => 1 */
	/* 6L & 1 => 0L */
	/* 2L & 0L => 0L */
	lequals(__LINE__, ((stlong8 >>= ( -- stlong3)) & (stlong6 & (stlong4 != stlong2))), 0L);
	lequals(__LINE__, stlong3, 2L);
	lequals(__LINE__, stlong8, 2L);

	/* 2.20000E+000 >= 2.20000E+000 => 1 */
	/* 4.40000E+000 *= 1 => 4.40000E+000 */
	/* 7L >> 0L => 7L */
	/* 6L /= 7L => 0L */
	/* 4.40000E+000 == 0L => 0 */
	iequals(__LINE__, ((f4 *= (*pf2 >= *pf2)) == (stlong6 /= (stlong7 >> stlong1))), 0);
	lequals(__LINE__, stlong6, 0L);
	fequals(__LINE__, f4, 4.40000E+000);

	return 	report(Filename);
	}
