/* The Plum Hall Validation Suite for C
 * Unpublished copyright (c) 1986-1991, Chiron Systems Inc and Plum Hall Inc.
 * VERSION: 4
 * DATE: 1993-01-01
 * The "ANSI" mode of the Suite corresponds to the official ANSI C, X3.159-1989.
 * As per your license agreement, your distribution is not to be moved or copied outside the Designated Site
 * without specific permission from Plum Hall Inc.
 */

/****************************************************************************
 ** Self-checking C source code generated by EGEN component of             **
 **    The Plum Hall Validation Suite for C.                               **
 **    (C) 1986-1988 Chiron Systems Inc and Plum Hall Inc                  **
 **    EGEN Version 1.09.000  88/08/21                                     **
 **                                                                        **
 **    EGEN -P -R2 -V -A -N5 -Dmixed.gen ( @ @ ) @ ( @ @ )                 **
 ****************************************************************************/
#include "defs.h"


int main()
	{
	extern char *Filename;
	static float f1;
	auto float * pf1;
	static long stlong1;
	static float f2;
	auto float * pf2;
	static long stlong2;
	static float f3;
	static float * pf3;
	auto long stlong3;
	static float f4;
	static float * pf4;
	static long stlong4;
	static double d1;
	auto double * pd1;
	static long stlong5;
	static double d2;
	static double * pd2;
	static long stlong6;
	auto double d3;
	static double * pd3;
	static long stlong7;
	static double d4;
	static double * pd4;
	auto long stlong8;

	f1 = fvalue(1.100000E+000);
	pf1 = &f1;
	stlong1 = lvalue(1L);
	f2 = fvalue(2.200000E+000);
	pf2 = &f2;
	stlong2 = lvalue(2L);
	f3 = fvalue(3.300000E+000);
	pf3 = &f3;
	stlong3 = lvalue(3L);
	f4 = fvalue(4.400000E+000);
	pf4 = &f4;
	stlong4 = lvalue(4L);
	d1 = dvalue(1.100000000000000E+000);
	pd1 = &d1;
	stlong5 = lvalue(5L);
	d2 = dvalue(2.200000000000000E+000);
	pd2 = &d2;
	stlong6 = lvalue(6L);
	d3 = dvalue(3.300000000000000E+000);
	pd3 = &d3;
	stlong7 = lvalue(7L);
	d4 = dvalue(4.400000000000000E+000);
	pd4 = &d4;
	stlong8 = lvalue(8L);
	Filename = "mix2.c";

	/* 2.20000E+000 > 3.30000E+000 => 0 */
	/* 2L -= 0 => 2L */
	/* 4L ^ 7L => 3L */
	/* 5L |= 3L => 7L */
	/* 2L + 7L => 9L */
	lequals(__LINE__, ((stlong2 -= (*pf2 > f3)) + (stlong5 |= (stlong4 ^ stlong7))), 9L);
	lequals(__LINE__, stlong5, 7L);
	lequals(__LINE__, stlong2, 2L);

	/* 2L == 7L => 0 */
	/* 0 & 3L => 0L */
	/* neg 7L => -7L */
	/* 7L &= -7L => 1L */
	/* 0L <= 1L => 1 */
/* 	iequals(__LINE__, (((stlong2 == stlong5) & stlong3) <= (stlong7 &= ( - stlong5))), 1); /* non-portable */
/* 	lequals(__LINE__, stlong7, 1L); /* non-portable */

	/* neg 3.30000E+000 => -3.30000E+000 */
	/* 2L != -3.30000E+000 => 1 */
	iequals(__LINE__, ((stlong2 != ( - *pf3)) || ((stlong4 / stlong2) / f1)), 1);

	/* 4.40000E+000 < 4L => 0 */
	/* 3L += 0 => 3L */
	/* 3L < 1 => 0 */
	iequals(__LINE__, ((stlong3 += (*pf4 < stlong4)) < (stlong4 || (*pf2 - d4))), 0);
	lequals(__LINE__, stlong3, 3L);

	/* pre++ 1L => 2L */
	/* 8L |= 2L => 10L */
	/* 2.20000E+000 / 3L => 7.33333E-001 */
	/* 7.33333E-001 * 3.30000E+000 => 2.42000E+000 */
	/* 10L + 2.42000E+000 => 1.24200E+001 */
	fequals(__LINE__, ((stlong8 |= ( ++ stlong1)) + ((f2 / stlong3) * f3)), 1.24200E+001);
	lequals(__LINE__, stlong1, 2L);
	lequals(__LINE__, stlong8, 10L);

	return 	report(Filename);
	}
