/* The Plum Hall Validation Suite for C
 * Unpublished copyright (c) 1986-1991, Chiron Systems Inc and Plum Hall Inc.
 * VERSION: 4
 * DATE: 1993-01-01
 * The "ANSI" mode of the Suite corresponds to the official ANSI C, X3.159-1989.
 * As per your license agreement, your distribution is not to be moved or copied outside the Designated Site
 * without specific permission from Plum Hall Inc.
 */

/****************************************************************************
 ** Self-checking C source code generated by EGEN component of             **
 **    The Plum Hall Validation Suite for C.                               **
 **    (C) 1986-1988 Chiron Systems Inc and Plum Hall Inc                  **
 **    EGEN Version 1.09.000  88/08/21                                     **
 **                                                                        **
 **    EGEN -P -R4 -V -A -N5 -Dmixed.gen ( @ @ ) @ ( @ @ )                 **
 ****************************************************************************/
#include "defs.h"


int main()
	{
	extern char *Filename;
	static float f1;
	auto float * pf1;
	static long stlong1;
	static float f2;
	auto float * pf2;
	static long stlong2;
	static float f3;
	static float * pf3;
	auto long stlong3;
	static float f4;
	static float * pf4;
	static long stlong4;
	static double d1;
	auto double * pd1;
	static long stlong5;
	static double d2;
	static double * pd2;
	static long stlong6;
	auto double d3;
	static double * pd3;
	static long stlong7;
	static double d4;
	static double * pd4;
	auto long stlong8;

	f1 = fvalue(1.100000E+000);
	pf1 = &f1;
	stlong1 = lvalue(1L);
	f2 = fvalue(2.200000E+000);
	pf2 = &f2;
	stlong2 = lvalue(2L);
	f3 = fvalue(3.300000E+000);
	pf3 = &f3;
	stlong3 = lvalue(3L);
	f4 = fvalue(4.400000E+000);
	pf4 = &f4;
	stlong4 = lvalue(4L);
	d1 = dvalue(1.100000000000000E+000);
	pd1 = &d1;
	stlong5 = lvalue(5L);
	d2 = dvalue(2.200000000000000E+000);
	pd2 = &d2;
	stlong6 = lvalue(6L);
	d3 = dvalue(3.300000000000000E+000);
	pd3 = &d3;
	stlong7 = lvalue(7L);
	d4 = dvalue(4.400000000000000E+000);
	pd4 = &d4;
	stlong8 = lvalue(8L);
	Filename = "mix4.c";

	/* 2L - 8L => -6L */
	/* 7L & -6L => 2L */
	/* pre++ 1.10000000000000E+000 => 2.10000000000000E+000 */
	/* 6L != 2.10000000000000E+000 => 1 */
	/* 2L <= 1 => 0 */
	iequals(__LINE__, ((stlong7 & (stlong2 - stlong8)) <= (stlong6 != ( ++ *pd1))), 0);
	dequals(__LINE__, d1, 2.10000000000000E+000);

	/* pre-- 3.30000000000000E+000 => 2.30000000000000E+000 */
	/* 2.30000000000000E+000 == 1.10000E+000 => 0 */
	/* 7L && 8L => 1 */
	/* 1L /= 1 => 1L */
	/* 0 - 1L => -1L */
	lequals(__LINE__, ((( -- *pd3) == f1) - (stlong1 /= (stlong7 && stlong8))), -1L);
	lequals(__LINE__, stlong1, 1L);
	dequals(__LINE__, d3, 2.30000000000000E+000);

	/* neg 8L => -8L */
	/* 5L - -8L => 13L */
	/* 4L %= 1L => 0L */
	/* 7L &= 0L => 0L */
	/* 13L ^ 0L => 13L */
	lequals(__LINE__, ((stlong5 - ( - stlong8)) ^ (stlong7 &= (stlong4 %= stlong1))), 13L);
	lequals(__LINE__, stlong4, 0L);
	lequals(__LINE__, stlong7, 0L);

	/* 3L ^ 3L => 0L */
	/* 6L |= 0L => 6L */
	/* 1.10000E+000 / 2.20000E+000 => 5.00000E-001 */
	/* 5.00000E-001 > 2.10000E+000 => 0 */
	/* 6L - 0 => 6L */
	lequals(__LINE__, ((stlong6 |= (stlong3 ^ stlong3)) - ((*pf1 / f2) > d1)), 6L);
	lequals(__LINE__, stlong6, 6L);

	/* post-- 1.10000000000000E+000 => 2.10000000000000E+000 */
	/* 4.40000E+000 != 2.10000000000000E+000 => 1 */
	/* 2.20000E+000 + 3.30000E+000 => 5.50000E+000 */
	/* 2.30000E+000 && 5.50000E+000 => 1 */
	/* 1 + 1 => 2 */
	iequals(__LINE__, ((f4 != ((*pd1)-- )) + (*pd3 && (*pf2 + f3))), 2);
	fequals(__LINE__, d1, 1.10000E+000);

	return 	report(Filename);
	}
