.TH DRUM 4
.CT 2 sa
.SH NAME
drum \- paging device
.SH DESCRIPTION
This file is the paging and swapping device.
It usually refers to an indirect driver
that allows swapping to be spread over several disk drives.
.SH FILES
.F /dev/drum
.SH BUGS
The indirect driver divides the swap area into interleaved sections
of half a megabyte or so;
reads may not span the boundary between sections.
Since the system doesn't allocate blocks across sections,
this probably doesn't matter.
