.TH ABORT 3
.CT 2 proc_man
.SH NAME
abort \- generate a fault
.SH SYNOPSIS
.B int abort()
.PP
.SH DESCRIPTION
.I Abort
sends the current process a
.L SIGIOT
signal, which normally terminates
the process with a core dump.
.SH SEE ALSO
.IR adb (1), 
.IR signal (2), 
.IR exit (2)
.SH DIAGNOSTICS
Usually `abort \- core dumped' from the shell.
