.TH CHRTAB 3
.CT 2 graphics
.SH NAME
chrtab \(mi simple character bitmaps
.SH SYNOPSIS
.B extern char chrtab[95][16];
.SH DESCRIPTION
.I Chrtab
contains 8-by-16 bitmaps for
.SM ASCII
printing characters.
The 16 bytes pointed to by
.B chrtab[c-'\ ']
are the 16 rows of character
.I c
from top to bottom.
The most significant bit is the leftmost bit.
The bottom row is always empty (has all bits 0).
.SH SEE ALSO
.IR font (9.5)
.SH BUGS
The bitmaps of
.I chrtab
are intended for use with line printers, not bitmap devices.
