.EQ
delim $$
.EN
.TH ERF 3M
.CT 2 math
.SH NAME
erf, erfc \(mi error function
.SH SYNOPSIS
.B #include <math.h>
.PP
.B double erf(x)
.br
.B double x;
.PP
.B double erfc(x)
.br
.B double x;
.SH DESCRIPTION
These functions calculate the error function
.RI erf( x )
.if n .ig
$=~2 pi sup -1/2 int from 0 to x  roman e sup -t sup 2 dt$
..
and the complementary error function
.RI erfc( x )
.if n .ig
$=~ 1 - erf( x )$
..
\&.
The error criterion for both
.I erf
and
.I erfc
is relative.
.SH DIAGNOSTICS
There are no error returns.
.EQ
delim off
.EN
