.TH POLY 3
.CT 2 graphics math
.SH NAME
poly_lk, poly_read \(mi polyhedron database routines
.SH SYNOPSIS
.nf
.B #include <poly.h>
.PP
.B int poly_lk(name)
.B char *name;
.PP
.B int poly_read(p, dir, n)
.B Polyhedron *p;
.B char *dir;
.fi
.SH DESCRIPTION
These routines access the
.IR poly (7)
database of polyhedra.
.PP
.I Poly_lk
tries to interpret
.I name
as a polyhedron reference.
If it is a number, it returns that number.
Otherwise, it returns the number of the first polyhedron
for which
.I name
is a prefix of the polyhedron's name.
.PP
.I Poly_read
forms an in-core description of the polyhedron number
.I n
in the directory
.IR dir .
If
.I dir
is 0, the normal directory
.RB ( /usr/lib/polyhedra )
is used.
.SH "SEE ALSO"
.IR poly (5),
.IR poly (7)
.SH DIAGNOSTICS
.I Poly
returns \-1 on unknown names.
.PP
.I Poly_read
returns zero on success,
nonzero on error.
