.TH QSORT 3
.CT 2 data_man
.SH NAME
qsort \(mi quicker sort
.SH SYNOPSIS
.nf
.B qsort(base, nel, width, compar)
.B char *base;
.B int (*compar)();
.fi
.SH DESCRIPTION
.I Qsort
(quicker sort)
sorts an array into nondecreasing order.
The first argument is a pointer to the base of the data;
the second is the number of elements;
the third is the width of an element
in bytes;
the last is the name of a comparison routine
to be called with pointers
to elements being compared.
It should be declared as
.EX
        compar(a, b)
        char *a, *b;
.EE
The routine must return
an integer less than, equal to, or greater than 0
according as the first argument is to be considered
less than, equal to, or greater than the second.
.SH "SEE ALSO"
.IR sort (1)
