.TH BADGE A
.CT 1 shell
.SH NAME
badge \- print Bell Labs badge
.SH SYNOPSIS
.B badge
.I string1
.I string2
.I [ picture.ps ]
.SH DESCRIPTION
.I Badge
is an ASCII-to-PostScript converter that frames
its arguments in a pleasant, colorful badge,
suitable for laminating.
File
.I picture.ps
is assumed to contain 24-bit color encapsulated PostScript.
If it is omitted or doesn't exist, a blank box will appear;
.B goofy
and
.B donald
(see FILES) are available for the camera-shy.
.SH EXAMPLES
.TP
.L
badge "DONALD F" DUCK /usr/games/ps/donald | lp -dpeacock
.TP
.L
badge "P J" "WEINBERGER" /usr/games/ps/goofy | lp -dpeacock
.EX
.SH BUGS
Very long names (over 1.75 inches in 14 point type) are not accounted for.
.P
Unlike a similar badge provided by security, the
logo adheres to corporate standards.
.SH FILES
/usr/games/ps/donald
.br
/usr/games/ps/goofy
.br
/usr/games/ps/logo	A corporate logo.
