.TH MINTERM 10.5 UCDS
.SH NAME
minterm \- minterm file format
.SH DESCRIPTION
The
.I minterm
file format consists of at least one binary valued function
definition.
A function definition begins
.B .o
.I n ...
followed by line(s) that have the form
.IR term : mask
\&...
The first
.I n
following
.B .o
is a numeric symbol of the function
(usually an output pin number of a rom or pal integrated circuit).
Any other
.IR n 's
are numeric symbols of input binary variables.
.I Term
and
.I mask
are decimal numbers.
.PP
There is a correspondence between the bits of the numbers in binary
representation and the input symbols, the first input symbol
is associated with the least significant bit.
The meaning of a bit with value 1 in
.I mask
is `do care',
and the meaning of a bit with value 1 in
.I term
is `input must be 1'.
Thus the
.IR term : mask
is a implicant, and a set of them when
.IR or 'ed
together
describes the input conditions for which the output symbol will have
a value of 1.
.PP
For example:
.IP
.ft 8
 .o 3 1 2
 3:3
 .o 4 1 2
 1:3 2:3 3:3
 .o 5 2 3
 1:3 2:3
 .o 11
 .o 9
 0:0
.ft
.PP
Output 3 is the
.I and
function of inputs 1 and 2;
output 4 is the
.I or
function of inputs 1 and 2
.RI ( quine (10.1)
would change this to 1:1 2:2);
output 5 is the
.I exclusive-or
function of inputs 2 and 3;
output 11 is a constant 0 and output 9 is
a constant 1.
.SH SEE ALSO
.IR lde (10.1),
.IR quine (10.1),
.IR cover (10.1),
.IR hazard (10.1),
.IR pal (10.1)
