.TH DKNAME 7
.CT 1 comm_mach inst_info
.SH NAME
dkname \(mi map system name to Datakit address
.SH SYNOPSIS
.B dkname
.I sysname ...
.SH DESCRIPTION
.I Dkname
looks up machine names and prints the corresponding full
Datakit address on the standard output.
The addresses are not necessarily printed in the same order as the arguments.
The addresses are obtained by the first possible match in the file
.FR /usr/lib/uucp/Systems.dk .
.SH FILES
.F /usr/lib/uucp/Systems.dk
