.TH NEWS 7
.CT 1 comm_users
.SH NAME
news \(mi print news items
.SH SYNOPSIS
.B news
[
.B -a
]
[
.B -n
]
[
.B -s
]
[
.I item ...
]
.SH DESCRIPTION
When invoked without options,
this simple local news service
prints files that have appeared in
.BR /usr/news
since last reading, most recent first,
with each preceded by an appropriate header.
The time of reading is recorded.
The options are
.TP
.B -a
Print all items, regardless of currency.
The recorded time is not changed.
.TP
.B -n
Report the names of the current items without
printing their contents, and without changing
the recorded time.
.TP
.B -s
Report the number of current items.
.PP
Other arguments
select particular news items.
.PP
If an interrupt
is received during a news item, the
next item is started immediately.
Another interrupt
within a second of the first causes the program to terminate.
.PP
To post a news item, create a file in
.FR  /usr/news .
.PP
You may arrange to receive news automatically by 
registering your mail address in
.FR /usr/lib/subscribers .
A daemon mails newly posted news items
to all addresses on the list.
.SH FILES
.F /usr/news/*
.br
.F $HOME/news_time
date of last read news
.br
.F /usr/lib/subscribers
.SH SEE ALSO
.IR calendar (1), 
.IR readnews (7)
