<../mkconf.sysv

CC=cc
LPROG=connect canon #dispatch
LIBS=lib.a
LIBOBJ=canon.o lcreat.o

%: %.sh
	cp $stem.sh $target
	chmod +x $target

connect: connect.o
	$CC $CFLAGS -o connect connect.o

dispatch: dispatch.o
	$CC $CFLAGS -o dispatch dispatch.o

canon: canonmain.o lib.a
	$CC $CFLAGS -o canon canonmain.o lib.a

compile:V: $LPROG $LIBS

install:V:
	test -d $LDIR || mkdir $LDIR
	cp $LPROG $LDIR
	chown root $LDIR/connect && chmod 4755 $LDIR/connect

lib.a: $LIBOBJ
	ar r lib.a $LIBOBJ

clean:V:
	rm -f $LPROG $LIBS *.o
