#
# U of Toronto systems
#
MFLOWS=mflow.u
MFAIRS=mfair.u

all:V: $NAUTS $COMETS $MFLOWS $STARS $MFAIRS

# $COMETS:V:
# 	cc=$cc mk -f ../lib/mk.comet $target
# $NAUTS:V:
# 	cc=$cc mk -f ../lib/mk.naut $target
$MFLOWS:V:
	cc=$cc mk -f ../lib/mk.mflow $target
# $STARS:V:
# 	cc=$cc mk -f ../lib/mk.star $target
$MFAIRS:V:
	cc=$cc mk -f ../lib/mk.mfair $target
