.TH BUFLD 4
.CT 2 comm_mach
.SH NAME
buf_ld \- buffering line discipline
.SH DESCRIPTION
.I Buf_ld
treasures up data for a while, then emits it in
a burst.
It is otherwise trans\%parent.
It is meant to reduce overhead of programs such as
.IR cu (1)
and
.IR uucp (1)
that read input from moderate-speed lines in raw or cbreak mode.
.PP
It saves characters until
16 have arrived,
or until 1/20 sec has passed
and no more characters have come.
.SH "SEE ALSO
.IR stream (4),
.IR ttyld (4)
