      LOGICAL FUNCTION A0DESE(X,NX,T,DT,ERRPAR,DELTA,E,ERROR)
C
C  ERROR FILTER FOR KEEPING TRACK OF THE MAXIMUM ABSOLUTE VALUE OF THE
C  SOLUTION, IF IT IS NECESSARY.
C
      COMMON /ODESM/IGMAX,IGMAXO
C
      REAL X(NX),T,DT,DELTA
      REAL ERRPAR(2),E(NX)
      LOGICAL ERROR
      EXTERNAL ERROR
C
      COMMON /CSTAK/DS
      DOUBLE PRECISION DS(500)
      REAL RS(1000)
      EQUIVALENCE (DS(1),RS(1))
C
C ... RAISE THE GLOBAL MAXIMUM, IF NECESSARY.
C
      IF (IGMAX.GT.0) CALL A0DESU(X,NX,RS(IGMAX))
C
      A0DESE=ERROR(X,NX,T,DT,ERRPAR,DELTA.EQ.1.0E0,E)
C
      RETURN
C
      END
