      SUBROUTINE A0DESL(X,NX,GLBMAX,GLBMXO)
C
C  TO LOAD THE GLOBAL MAXIMUM.
C
      REAL X(NX)
      REAL GLBMAX(NX),GLBMXO(NX)
C
      DO 10 I=1,NX
         GLBMAX(I)=ABS((X(I)))
 10      GLBMXO(I)=GLBMAX(I)
C
      RETURN
C
      END
