      LOGICAL FUNCTION A1ODEE(V, NV, T, DT, ERRPAR, DELTA, EV,
     1   ERROR)
      INTEGER NV
      EXTERNAL ERROR
      REAL V(NV), T, DT, ERRPAR(2), DELTA, EV(NV)
      LOGICAL ERROR
      LOGICAL ERPUTS
C THE ERROR FILTER FOR NLEQS.
C SCRATCH SPACE ALLOCATED - S(A1ODEE) = S(ERROR).
      ERPUTS = DELTA .EQ. 1.
      A1ODEE = ERROR(V, NV, T, DT, ERRPAR, ERPUTS, EV)
      RETURN
      END
