      SUBROUTINE A1ODEH(T0, V0, T1, V1, NV, DT, TSTOP, EV, OK,
     1   HANDLE)
      INTEGER NV
      EXTERNAL HANDLE
      REAL T0, V0(NV), T1, V1(NV), DT, TSTOP
      REAL EV(NV)
      LOGICAL OK
      COMMON /A1ODEF/ FNUM
      INTEGER FNUM
      COMMON /A10DER/ NJS, NFS, NTSS, NSSS, NES, NNITS, NNDS, NNFS, NRS
      INTEGER NJS, NFS, NTSS, NSSS, NES, NNITS
      INTEGER NNDS, NNFS, NRS
      COMMON /A1ODEM/ THETA, EGIVE, MINIT, MAXIT, KEEJAC, IRCS
      INTEGER MINIT, MAXIT, KEEJAC, IRCS
      REAL THETA, EGIVE
      COMMON /A1ODEG/ TJ, DTJ, GETJAC, SEPATE, USENGJ, USENNS, USENFD
      REAL TJ, DTJ
      LOGICAL GETJAC, SEPATE, USENGJ, USENNS, USENFD
      COMMON /A10DET/ TGOOD
      REAL TGOOD
C OUTPUT FILTER FOR IODES.
C SCRATCH SPACE ALLOCATED - S(A1ODEH) = S(HANDLE).
      IF (T0 .EQ. T1) GOTO 1
         FNUM = 0
         TGOOD = T1
         GOTO  2
   1     NRS = NRS+1
   2  IF (T0 .NE. T1 .OR. KEEJAC .NE. 3) GOTO 3
         GETJAC = T0 .NE. TJ
         TJ = T0
   3  NTSS = NTSS+1
      CALL HANDLE(T0, V0, T1, V1, NV, DT, TSTOP)
      RETURN
      END
