      LOGICAL FUNCTION D1ODEE(V, NV, T, DT, ERRPAR, DELTA, EV,
     1   ERROR)
      INTEGER NV
      EXTERNAL ERROR
      REAL ERRPAR(2), EV(NV)
      LOGICAL ERROR
      DOUBLE PRECISION V(NV), T, DT, DELTA
      LOGICAL ERPUTS
C THE ERROR FILTER FOR NLEQS.
C SCRATCH SPACE ALLOCATED - S(D1ODEE) = S(ERROR).
      ERPUTS = DELTA .EQ. 1D0
      D1ODEE = ERROR(V, NV, T, DT, ERRPAR, ERPUTS, EV)
      RETURN
      END
