      DOUBLE PRECISION FUNCTION DFLR(X)
C
C  DFLR RETURNS FLR(X)
C
      DOUBLE PRECISION X
C
      DFLR = DBLE( FLOAT ( IDINT(X) ) )
      IF (X .GE. 0.0D0) RETURN
      IF (DFLR .NE. X) DFLR = DFLR - 1.0D0
C
      RETURN
      END
