      LOGICAL FUNCTION DIODEE(V, NV, T, DT, ERRPAR, ERPUTS, EV)
      INTEGER NV
      REAL ERRPAR(2), EV(NV)
      LOGICAL ERPUTS
      DOUBLE PRECISION V(NV), T, DT
      INTEGER I
      REAL TEMP, DTPOW
      LOGICAL CONGED
      DOUBLE PRECISION DABS
C THE STANDARD ERROR PROCEDURE FOR DIODES.
C SCRATCH SPACE ALLOCATED - NONE.
      IF (.NOT. ERPUTS) GOTO 1
         DTPOW = DABS(DT)
         GOTO  2
   1     DTPOW = 1
   2  CONGED = .TRUE.
C ERROR FOR V.
      DO  3 I = 1, NV
         TEMP = DTPOW*(ERRPAR(1)*DABS(V(I))+ERRPAR(2))
         IF (TEMP .LT. EV(I)) CONGED = .FALSE.
         EV(I) = TEMP
   3     CONTINUE
      DIODEE = CONGED
      RETURN
      END
