      SUBROUTINE DIODE(V, NV, TSTART, TSTOP, DT, D, ERRPAR,
     1   HANDLE)
      INTEGER NV
      EXTERNAL D, HANDLE
      REAL ERRPAR(2)
      DOUBLE PRECISION V(NV), TSTART, TSTOP, DT
      EXTERNAL DIODED, DIODEE, DIODEN
C THE FIRST LEVEL OF DIODE.
      CALL DIODER(V, NV, TSTART, TSTOP, DT, D, DIODEE, ERRPAR, DIODEN,
     1   DIODED, HANDLE)
      RETURN
      END
