      SUBROUTINE DIODES(V, NV, TSTART, TSTOP, DT, D, ERRPAR,
     1   HANDLE)
      INTEGER NV
      EXTERNAL D, HANDLE
      REAL ERRPAR(2)
      DOUBLE PRECISION V(NV), TSTART, TSTOP, DT
      EXTERNAL DIODEE
      LOGICAL ERPUTS
C THE FIRST LEVEL OF DIODES.
      ERPUTS = .FALSE.
      CALL DIODE1(V, NV, TSTART, TSTOP, DT, D, DIODEE, ERRPAR, ERPUTS,
     1   HANDLE)
      RETURN
      END
