      INTEGER FUNCTION IDCEIL(X)
C
C  IDCEIL RETURNS CEIL(X)
C
      DOUBLE PRECISION X
C
      IDCEIL = IDINT(X)
      IF (X .LE. 0.0D0) RETURN
      IF (DBLE(FLOAT(IDCEIL)) .NE. X) IDCEIL = IDCEIL + 1
C
      RETURN
      END
