      SUBROUTINE IODE3(V, NV, TSTART, TSTOP, DT, D, THETA, KEEJAC,
     1   MINIT, MAXIT, KMAX, XPOLY, KINIT, ERROR, ERRPAR, ERPUTS, INMI
     2   , DA, HANDLE)
      INTEGER NV
      EXTERNAL D, ERROR, INMI, DA, HANDLE
      INTEGER KEEJAC, MINIT, MAXIT, KMAX, KINIT
      REAL V(NV), TSTART, TSTOP, DT, THETA, ERRPAR(2)
      LOGICAL XPOLY, ERPUTS
      COMMON /CSTAK/ DS
      DOUBLE PRECISION DS(500)
      EXTERNAL A1ODEE, A1ODEH, A1ODEP, A1ODEN
      INTEGER ISTKGT, I, IRCS, MMAX, IN, IS(1000)
      REAL HFRACT, BETA, GAMMA, DELTA, EGIVE, RS(1000)
      REAL WS(1000)
      LOGICAL USENFD, USENGJ, USENNS, LS(1000)
      INTEGER TEMP, TEMP1
      EQUIVALENCE (DS(1), WS(1), RS(1), IS(1), LS(1))
      DATA USENGJ/.FALSE./
      DATA USENNS/.FALSE./
      DATA USENFD/.FALSE./
C THE FOURTH LEVEL OF IODES.
C SCRATCH SPACE ALLOCATED -
C     S( IODE3) = S(A1ODES) +
C REAL WORDS +
C                 MMAX
C INTEGER WORDS.
C THE PORT LIBRARY STACK AND ITS ALIASES.
      IF (TSTART .EQ. TSTOP) RETURN
      CALL ENTER(1)
C CHECK THE INPUT FOR ERRORS.
      MMAX = KMAX+5
      BETA = 1
      IF (THETA .EQ. 0.5) GOTO 1
         GAMMA = 1
         GOTO  2
   1     GAMMA = 2
   2  IF (.NOT. ERPUTS) GOTO 3
         DELTA = 1
         GOTO  4
   3     DELTA = 0
C GET N.
   4  IN = ISTKGT(MMAX, 2)
      IS(IN) = 1
      IS(IN+1) = 2
      IS(IN+2) = 3
      I = 4
         GOTO  6
   5     I = I+1
   6     IF (I .GT. MMAX) GOTO  7
         TEMP1 = IN+I
         TEMP = IN+I
         IS(TEMP1-1) = 2*IS(TEMP-3)
         GOTO  5
   7  IF (THETA .NE. 0.5) GOTO 9
         HFRACT = 0.5
         DO  8 I = 1, MMAX
            TEMP = IN+I
            IS(TEMP-1) = 2*IS(TEMP-1)
   8        CONTINUE
         GOTO  10
   9     HFRACT = 1
  10  EGIVE = 1E+2
      IRCS = 1
      CALL IODE4(V, NV, TSTART, TSTOP, DT, D, THETA, KEEJAC, MINIT,
     1   MAXIT, USENGJ, USENNS, USENFD, BETA, GAMMA, DELTA, IS(IN),
     2   MMAX, HFRACT, EGIVE, KMAX, XPOLY, KINIT, IRCS, ERROR, ERRPAR,
     3   ERPUTS, INMI, DA, HANDLE)
      CALL LEAVE
      RETURN
      END
