      SUBROUTINE IODEH(T0, V0, T1, V1, NV, DT, TSTOP)
      INTEGER NV
      REAL T0, V0(NV), T1, V1(NV), DT, TSTOP
C DEFAULT HANDLE PROCEDURE FOR IODES.
C SCRATCH SPACE ALLOCATED - NONE.
      RETURN
      END
