      LOGICAL FUNCTION IODEE(V, NV, T, DT, ERRPAR, ERPUTS, EV)
      INTEGER NV
      REAL V(NV), T, DT, ERRPAR(2), EV(NV)
      LOGICAL ERPUTS
      INTEGER I
      REAL ABS, TEMP, DTPOW
      LOGICAL CONGED
C THE STANDARD ERROR PROCEDURE FOR IODES.
C SCRATCH SPACE ALLOCATED - NONE.
      IF (.NOT. ERPUTS) GOTO 1
         DTPOW = ABS(DT)
         GOTO  2
   1     DTPOW = 1
   2  CONGED = .TRUE.
C ERROR FOR V.
      DO  3 I = 1, NV
         TEMP = DTPOW*(ERRPAR(1)*ABS(V(I))+ERRPAR(2))
         IF (TEMP .LT. EV(I)) CONGED = .FALSE.
         EV(I) = TEMP
   3     CONTINUE
      IODEE = CONGED
      RETURN
      END
