      SUBROUTINE IODE(V, NV, TSTART, TSTOP, DT, D, ERRPAR, HANDLE)
      INTEGER NV
      EXTERNAL D, HANDLE
      REAL V(NV), TSTART, TSTOP, DT, ERRPAR(2)
      EXTERNAL IODEE, IODED, IODEN
C THE FIRST LEVEL OF IODE.
      CALL IODER(V, NV, TSTART, TSTOP, DT, D, IODEE, ERRPAR, IODEN,
     1   IODED, HANDLE)
      RETURN
      END
