      SUBROUTINE IODE1(V, NV, TSTART, TSTOP, DT, D, ERROR, ERRPAR,
     1   ERPUTS, HANDLE)
      INTEGER NV
      EXTERNAL D, ERROR, HANDLE
      REAL V(NV), TSTART, TSTOP, DT, ERRPAR(2)
      LOGICAL ERPUTS
      INTEGER KMAX, KINIT
      LOGICAL EQUIL, XPOLY
C THE SECOND LEVEL OF IODES.
      KMAX = 10
      XPOLY = .FALSE.
      KINIT = 2
      EQUIL = .TRUE.
      CALL IODE2(V, NV, TSTART, TSTOP, DT, D, EQUIL, KMAX, XPOLY, KINIT,
     1   ERROR, ERRPAR, ERPUTS, HANDLE)
      RETURN
      END
