      SUBROUTINE IODES(V, NV, TSTART, TSTOP, DT, D, ERRPAR,
     1   HANDLE)
      INTEGER NV
      EXTERNAL D, HANDLE
      REAL V(NV), TSTART, TSTOP, DT, ERRPAR(2)
      EXTERNAL IODEE
      LOGICAL ERPUTS
C THE FIRST LEVEL OF IODES.
      ERPUTS = .FALSE.
      CALL IODE1(V, NV, TSTART, TSTOP, DT, D, IODEE, ERRPAR, ERPUTS,
     1   HANDLE)
      RETURN
      END
