      SUBROUTINE IODEX
      COMMON /A10DER/ STATS
      INTEGER STATS(9)
      INTEGER I1MACH
      INTEGER TEMP
C TO PRINT THE RUN-TIME STATISTICS FOR IODE.
      CALL A1ODEX(STATS, 0)
      TEMP = I1MACH(2)
      WRITE (TEMP,  1) STATS
   1  FORMAT (32H IODE(J,F,TS,SS,E,NIT,ND,NF,R) =, 9(I5))
      RETURN
      END
