      SUBROUTINE ODESH(T0,X0,T1,X1,NX,DT,TSTOP,E)
C
C  THE DEFAULT OUTPUT ROUTINE FOR USE WITH ODES.
C  IT SIMPLY RETURNS.
C
C  SCRATCH SPACE ALLOCATED - NONE.
C
C  ERROR STATES - NONE.
C
      REAL T0,X0(NX),T1,X1(NX),DT,TSTOP
      REAL E(NX)
C
      RETURN
C
      END
