.TH 32LD 9.1
.CT 1 lib_obj
.SH NAME
32ld \- bootstrap loader for 5620
.SH SYNOPSIS
.B 32ld
[
.I option ...
]
.I file
[
.I argument ...
]
.SH DESCRIPTION
.I 32ld
loads the MAC-32 object
.I file
for execution in a 5620 connected to the standard output.
When loading into a
.IR mux (9.1)
layer, the
.I arguments
are passed to the program as in Unix.
The options are:
.TP
.B -d
Print on the standard error file the sizes of the text, data and bss
segments of
.I file.
The standard error must be
separated from the standard output to
avoid corrupting the down-load.
.TP
.B -p
Print down-loading protocol statistics on the diagnostic output
(for stand-alone loading only).
.TP
.B -z
Load the process but don't run it.
It may be started using
.IR 3pi ;
see
.IR pi (9.1).
This option works only under
.IR mux .
.PP
The environment variable
.B JPATH
is the analog of the shell's
.B PATH
variable to define a set of directories in which to search for
.IR file .
.SH SEE ALSO
.IR jx (9.1), 
.IR mux (9.1)
