.TH CIP 9.1
.CT 1 writing_troff graphics
.SH NAME
cip \- draw pictures for typesetting
.SH SYNOPSIS
.B cip
.SH DESCRIPTION
.I Cip
prepares or modifies
.IR pic (1)
descriptions, which may subsequently be typeset.
It provides a palette of
shapes: box, circle, ellipse, line, arc, spline, and text.
Button 1 selects shapes from the palette or the screen.
Button 2 places or redraws
.RL ( edit ,
.LR move )
shapes.
Button 3 controls menus.
.PP
File names and text strings are entered from the keyboard.
Keyboard input always ends with a newline.
A current file name is remembered and offered for
file operations; backspace over it to substitute
a new name, or type newline to accept it.
.PP
The
.L define macro
menu item allows a box to be swept, collecting all contained shapes
into a group.
Groups are selected as whole.
When a group is selected, a special menu appears.
Item
.L separate
dissolves the group;
.L reflect x
reflects about a horizontal midline; after
.L copy
button 2 places copies at the cursor.
Item
.L edit
confines activity to the group.
Changes are reflected in all copies of the group.
To leave the group, click button 1 at
.LR "edit depth" .
.SH SEE ALSO
.IR pic (1), 
.IR ped (9.1)
.br
Sally A. Browning,
`Cip User's Manual: One Picture is Worth a Thousand Words',
this manual, Volume\ 2
.SH BUGS
.I Cip
cannot handle arbitrary
.I pic
programs, just programs in the style
that it produces.
