.TH ICON 9.1
.CT 1 editor graphics
.SH NAME
icon \- icon editor
.SH SYNOPSIS
.B icon
.SH DESCRIPTION
.I Icon
is a pixel-level editor for textures and small bitmaps.
.I Icon
presents a magnified pixel grid and a true-size image.
Editing is done on the magnified grid.
Pixels can be turned black by pressing the button 1,
and white by pressing button 2.
.PP
Button 3 provides an iconic menu of editing commands.
Some commands require a rectangle to
be swept; this is done either by
the middle button (which supplies a fixed 16\(mu16 rectangle) or by the right
button (for rectangles of any size).
.PP
.TP \w'band-aid\ 'u
arrow
Move region (sweep rectangle
and click at destination).
.TP
overlapping regions
Copy region (sweep rectangle
and click at destination).
.TP
cross
Invert region (sweep rectangle).
.TP
eraser
Erase region (sweep rectangle).
.TP
horizontal (vertical) folded arrow
Reflect region horizontally (vertically) (sweep rectangle).
.TP
clockwise (counterclockwise) arrow
Rotate region deasil (withershins) (sweep rectangle).
.TP
horizontal (vertical) sheared lines
Shear a region horizontally (vertically) (sweep rectangle and point at destination
of nearest corner of rectangle).
.TP
scaled square
Scale a region (sweep rectangle and
sweep destination rectangle).
.TP
tweed pattern
Texture a region (sweep source rectangle and
a (bigger) destination rectangle to be tiled with copies of the source).
.TP
glasses
Read file (type file name and position the icon by clicking).
The subdirectories of
.F /usr/jerq/icon/
are searched automatically
after the current directory.
.TP
grid
Switch on or off the background grids.
.TP
extend region
Change the size of the drawing area.
.TP
pen
Write file (sweep rectangle and type file name).
See
.IR bitfile (9.5)
for the format.
.TP
overlapping rectangles
Bitblt region (driven by submenus on the right button).
.TP
mouse
Pick up a 16\(mu16 rectangle and make it the current cursor
(click a button to pick up a 16\(mu16 region, and click again to
revert to normal).
.TP
help
Display help information (click a button to revert to normal).
.TP
band-aid
Undo last drawing operation.
.SH FILES
.F /usr/jerq/icon/*/*
.SH SEE ALSO
.IR bitfile (9.5)
