.TH LIBC 9.3
.CT 1 lib_obj
.SH NAME
libc \- standard library functions
.SH DESCRIPTION
Various standard functions from
Section 3 are available in 5620 programs:
.LP
.2C
.ft 5
abs
atoi
atol
chrtab
qsort
rand
srand
strcat
strchr
strrchr
strcmp
strcpy
strncat
strncmp
strncpy
strlen
.1C
.ft 1
.LP
In addition, certain
.IR stdio (3)
programs are available under the
.IR jx (9.1)
emulator.
.SH SEE ALSO
.IR arith (3),
.IR atof (3),
.IR chrtab (3),
.IR libc (9.3),
.IR qsort (3),
.IR rand (3),
.IR string (3)
