.TH RULER 9.1
.CT 1 comm_term
.SH NAME
ruler \- measure things on the screen
.SH SYNOPSIS
.B ruler
.SH DESCRIPTION
.I Ruler
measures things on a
.IR mux (9.1)
screen.
Press button 1 to sweep out a rectangle anywhere on the screen.
For each rectangle swept,
.I ruler
displays the coordinates of the rectangle's corners (labeled
.B down
and
.BR up ),
the size
of the rectangle and length of its diagonal.
.LP
There is
a menu on button 3.
The
.B pixels
and
.B chars
items control whether the size and diagonal are measured
in units of pixels or characters;
.B stop
deactivates
.I ruler
without exiting;
.B measure
reactivates
.IR ruler .
.SH BUGS
Character units are arbitrarily defined as the width and height of a 
.L 0
in the
.I ruler
layer.
This may have nothing to do with character sizes in other layers.
.br
Ruler's menu must pop up in its own layer, perhaps far
away from the cursor.
