.TH TERM 9.1
.CT 1 comm_term
.SH NAME
term \- nonstandard mux terminals
.SH SYNOPSIS
.B exec
.B term
.I termtype
.SH DESCRIPTION
.I Term
replaces the program in the layer on its standard output with
an emulator for the terminal type specified by
.IR termtype .
In the resulting layer, environment variable TERM is set appropriately.
Known types are
.TP
.B 2621
Hewlett-Packard 2621
.TP
.B 2621c
Same, with data compression between host and terminal;
useful at line speeds of 2400 baud and lower.
.TP
.B 4014
Tektronix 4014
.TP
.B 5620
Teletype DMD 5620 stand-alone terminal.
.TP
.B 5620c
Same, with data compression.
.TP
.B 33
Teletype Model 33 (actually closer to 35).
.PP
Also,
.I termtype
.B mux
restores and initializes a standard
.IR mux (9.1)
terminal program.
.SH BUGS
Nonstandard terminal emulators do not work across
.IR dcon,
but usually do across
.IR ndcon
connections; see
.IR dcon (1).
.br
Unexported shell parameters and functions are lost.
