char	*tokens[] = {
	"+",		/* PLUS */
	"-",		/* MINUS */
	"^",		/* EXP */
	"*",		/* MUL */
	"/",		/* DIV */
	"=",		/* EQ */
	"<>",		/* NE */
	"<=",		/* LE */
	">=",		/* GE */
	">",		/* GT */
	"<",		/* LT */
	"and",		/* AND */
	"or",		/* OR */
	"list", 	/* LIST */
	"del",		/* DEL */
	"let",		/* LET */
	"run",		/* RUN */
	"to",		/* TO */
	"for",		/* FOR */
	"print",	/* PRINT */
	"input",	/* INPUT */
	"read", 	/* READ */
	"dim",		/* DIM */
	":",		/* COLON */
	"(",		/* LPAR */
	")",		/* RPAR */
	"[",		/* LSQ */
	"]",		/* RSQ */
	",",		/* COMMA */
	"goto", 	/* GOTO */
	"gosub",	/* GOSUB */
	"return",	/* RETURN */
	"end",		/* END */
	"trace",	/* TRACE */
	"notrace",	/* NOTRACE */
	"rem",		/* REM */
	"clear",	/* CLEAR */
	"\"",		/* QUOTE */
	"'",		/* PRIME */
	"if",		/* IF */
	"then", 	/* THEN */
	"step", 	/* STEP */
	"next", 	/* NEXT */
	"data", 	/* DATA */
	"ask",		/* ASK */
	"left$(",	/* LEFT */
	"right$(",	/* RIGHT */
	"mid$(",	/* MID */
	"len(", 	/* LEN */
	"chr$(",	/* CHR */
	"ascii(",	/* ASCII */
	"def",		/* DEF */
	"fn",		/* FN */
	"tab(", 	/* TAB */
	"stop", 	/* STOP */
	"on",		/* ON */
	"log(", 	/* LOG */
	"exp(", 	/* EXPFN */
	"abs(", 	/* ABS */
	"atn(", 	/* ATN */
	"cos(", 	/* COS */
	"int(", 	/* INTFN */
	"option",	/* OPTION */
	"base", 	/* BASE */
	"randomize",	/* RANDOM */
	"rnd(", 	/* RND */
	"restore",	/* RESTORE */
	"sin(", 	/* SIN */
	"sqr(", 	/* SQR */
	"tan(", 	/* TAN */
	"chain",	/* CHAIN */
	"hgr",		/* HGR */
	"hplot",	/* HPLOT */
	"output",	/* OUTPUT */
	"get",		/* GET */
	"close",	/* CLOSE */
	"open", 	/* OPEN */
	"arg$(",	/* ARG */
	"#",		/* SHARP */
	"system(",	/* SYSTEM */
	"flush",	/* FLUSH */
	"append",	/* APPEND */
	"val(", 	/* VAL */
	"str$(",	/* STR */
	"unblank$(",	/* UNBLANK */
	"&",		/* PRFORM */
	"using",	/* USING */
	"upshift$(",	/* UPSHIFT */
	"else",		/* ELSE */
	"more",		/* MORE */
	"sgn(",		/* SGN */
	"rand(",	/* RAND */
	0
	};
