      LOGICAL FUNCTION DOVAR(INDX)
      INTEGER DOPT, DOLIST
      COMMON /DOS/ DOPT, LDO, DOLIST(192)
C
C     CHECKS VAR AT DSA(INDX) NOT IN DOSTACK ALREADY
C     AS A LIMIT OR INDEX OF PREVIOUSLY DEFINED AND CURRENTLY
C     DEFINED DO
C
      DOVAR = .FALSE.
      IF (DOPT) 40, 40, 10
   10 DO 30 I=1,DOPT,6
        L1 = I + 2
        L2 = L1 + 3
        DO 20 K=L1,L2
          IF (DOLIST(K).EQ.INDX) GO TO 50
   20   CONTINUE
   30 CONTINUE
   40 RETURN
   50 DOVAR = .TRUE.
      GO TO 40
      END
