      SUBROUTINE ERROR1(MESS, LMESS)
C
      INTEGER MESS(20), LMESS
      INTEGER ZERO(1)
C
      DATA ZERO(1) /0/
C
      CALL ERROR2(MESS, LMESS, ZERO(1), ZERO(1), 1, 1)
C
      RETURN
C
      END
