      INTEGER FUNCTION FINDCM(K1)
      INTEGER K1(2)
      INTEGER PCOM, COM, SYMLEN
      LOGICAL COMPAR
      COMMON /COMS/ LCOM, PCOM, COM(300)
      COMMON /PARAMS/ INUT, I1, NOCHAR, SYMLEN, I2, I3, I4
C
C     ROUTINE FINDS COMMON BLOCK WHOSE NAME IS AT K1 IN COM
C     RETURNS INDEX IN COM OR 0 IF CANNOT FIND IT
C
      IF (PCOM-1) 30, 30, 10
   10 K = PCOM - 1
      KK = SYMLEN + 5
      DO 20 I=1,K,KK
        FINDCM = I
        IF (COMPAR(COM(I),K1)) GO TO 40
   20 CONTINUE
   30 FINDCM = 0
   40 RETURN
      END
