      INTEGER FUNCTION FIND(K)
C
C      FIND HAS TO FIND THE INDEX IN NODE
C      OF THE LATTICE ENTRY AT K, DOES A
C     LINEAR SEARCH ON NODE ARRAY
C      P.U. ASSUMES NODE ARRAY SET UP PROPERLY
C      AND THAT NODES ITS ASKED TO FIND ARE ALWAYS IN THE
C      ARRAY SOMEWHERE. CAN BE ASKED TO FIND INDEX OF
C      ANY NODE IN LATTICE, EVEN ASFS
C
      INTEGER PNODE
      COMMON /HEAD/ LNODE, PNODE, NODE(500)
      L = PNODE - 1
      DO 10 I=1,L
        IF (K.NE.IABS(NODE(I))) GO TO 10
        FIND = I
        GO TO 20
   10 CONTINUE
   20 RETURN
      END
