      INTEGER FUNCTION IGATT2(INDEX, FIELD)
C
      COMMON /GRAPH/ LLAT, PLAT, LAT(6000)
C
      INTEGER INDEX, FIELD
      INTEGER LLAT, PLAT, LAT
      INTEGER FWTH(8), FPOS(8)
C
      DATA FWTH(1) /16/, FPOS(1) /1/
      DATA FWTH(2) /2/, FPOS(2) /16/
      DATA FWTH(3) /2/, FPOS(3) /32/
      DATA FWTH(4) /2/, FPOS(4) /64/
      DATA FWTH(5) /2/, FPOS(5) /128/
      DATA FWTH(6) /2/, FPOS(6) /256/
      DATA FWTH(7) /4/, FPOS(7) /512/
      DATA FWTH(8) /32/, FPOS(8) /2048/
C
      IGATT2 = MOD(LAT(INDEX)/FPOS(FIELD),FWTH(FIELD))
C
      RETURN
C
      END
