      SUBROUTINE IN(CARD, INUT)
C
      INTEGER CARD(80)
      LOGICAL EOF
C
      DATA EOF /.FALSE./
      DATA IDOT /1H./
C
      IF (EOF) RETURN
C
C     READ A CARD. PHYSICAL EOF SHOULD TRANSFER TO 100
C
      READ (INUT,99999,END=100) CARD
99999 FORMAT (80A1)
      IF (CARD(1).NE.IDOT) RETURN
C
C     HERE FOR EOF
C
 100  CARD(1) = IDOT
      EOF = .TRUE.
C
      RETURN
      END
