      INTEGER FUNCTION INREF(IDUM)
      INTEGER REF, PREF
      COMMON /CREF/ LREF, PREF, REF(100)
C
C     ROUTINE TO INPUT CALL TEMPLATES, RETURNS -1 FOR EOF,  0 FOR END
C     OF REFS FOR THIS PGM UNIT, AND 1 FOR REF RETRIEVED
C
      READ (IDUM) PREF, K, (REF(L),L=1,PREF)
      IF (K-3) 10, 30, 40
   10 INREF = 1
   20 RETURN
   30 INREF = 0
      GO TO 20
   40 INREF = -1
      GO TO 20
      END
