      SUBROUTINE RDSYM(IC, IP)
C
C      PGM UNIT RDSYM POSITIONS I4,I6 CORRECTLY AND INPUTS SYMBOL
C      TABLE OF PGM UNIT AT NODE(IC) WHEN LAST ONE READ WAS THAT OF NODE
C
      INTEGER SYMLEN, PDSA, PLAT, FINDND, PNODE, DSA
      LOGICAL INSYM, L
      COMMON /PARAMS/ I1, I2, I3, SYMLEN, I4, I5, I6
      COMMON /FACTS/ NAME, NOST, ITYP, IASF
      COMMON /CTABL/ LDSA, PDSA, DSA(5000)
      COMMON /GRAPH/ LLAT, PLAT, LAT(6000)
      COMMON /HEAD/ LNODE, PNODE, NODE(500)
      IF (IP.LT.IC) GO TO 10
      REWIND I4
      REWIND I6
 10   L = INSYM(I6,0)
      IF (FINDND(DSA(NAME+4),I).EQ.NODE(IC)) RETURN
   20 IF (INREF(I6).EQ.1) GO TO 20
      GO TO 10
      END
