      SUBROUTINE SEPAR(ICHAR)
C
C      FINDS SEPARATER CONSTRUCT IN FORMAT STMTS
C     SEPARATER IS A  COMBINATION OF "/" AND ","
C     ",," IS ALWAYS ILLEGAL IN A SEPARATER
C     MIXING OF "/" AND "," IS WARNED AGAINST
C
C     ICHAR CONTAINS LENGTH OF SEPARATOR FOUND
      INTEGER PSTMT, STMT
      COMMON /INPUT/ NSTMT, PSTMT, STMT(1327)
      ICHAR = PSTMT
      ICOM = 0
C
C     " , "
C
   10 IF (STMT(PSTMT).NE.68) GO TO 20
      ICOM = ICOM + 1
C
C      CHECK FOR ",,"
C
      PSTMT = PSTMT + 1
      IF (STMT(PSTMT).EQ.68) GO TO 30
   20 IF (STMT(PSTMT).NE.67) GO TO 50
      PSTMT = PSTMT + 1
      GO TO 10
   30 CALL ERROR1(19H ILLEGAL ADJACENT ,, 19)
C
C      FLUSH TO NEXT NON-SEPARATER
C
   40 PSTMT = PSTMT + 1
      IF (STMT(PSTMT).EQ.67 .OR. STMT(PSTMT).EQ.68) GO TO 40
   50 ICHAR = PSTMT - ICHAR
      IF (ICOM.GT.0 .AND. ICHAR.GT.1) CALL ERROR1(
     *    36H ILLEGAL MIXING OF / AND , IN FORMAT, 36)
      RETURN
      END
