      SUBROUTINE SORT(IPT, L)
      EXTERNAL EXCH
      INTEGER HASH, PDSA, DSA
      COMMON /CHASH/ LHASH, HASH(401)
      COMMON /CTABL/ LDSA, PDSA, DSA(5000)
C
C     PUT ALL SUMBOL INDICES IN HASH TABLE TO SORT THEM
C
      L = 0
      I = IPT
   10 IF (I.EQ.0) GO TO 20
      L = L + 1
      HASH(L) = I
      I = DSA(I+3)
      GO TO 10
C
C     CALL SORT ROUTINE
C     UPON RETURN HASH CONTAINS INDICES OF ALL SYMBOLS OR LABELS IN
C     DSA IN LEXICOGRAPHIC ORDER
C
   20 CALL SSORT(EXCH, DSA, LDSA, HASH, L, 4)
      RETURN
      END
