.TH BIGCORE 1
.CT 1 debug_tune
.SH NAME
bigcore, coreid \- permit big core images, identify source of image
.SH SYNOPSIS
.B bigcore
.I command
.PP
.B coreid
[
.I file
]
.SH DESCRIPTION
.I Bigcore
calls the named
.I command
with no restriction on the size of core images.
By default,
no core image will be written when a program aborts
if it would be larger than a megabyte.
.PP
.I Coreid
reads the file
.FR core ,
or the specified core image
.I file,
and prints on the standard output the argument list
of the program that produced the core image.
.SH FILES
.F core
.SH SEE ALSO
.IR core (5)
.SH BUGS
.I Coreid
only works for core images from C and Fortran programs.
.br
The arguments shown are those at the time of the dump,
not at invocation of the program.
