.TH DOCTYPE 1 
.CT 1 writing_troff
.SH NAME
doctype \- guess command line for formatting a document
.SH SYNOPSIS
.B doctype
[
.I option ...
] [
.I file
]
...
.SH DESCRIPTION
.I Doctype
guesses and prints on the standard output the command line for printing
a document that uses 
.IR troff (1),
related preprocessors like
.IR eqn (1),
and the 
.IR ms (6)
and
.I mm 
macro packages.
.PP
Option
.B -n
invokes
.I nroff
instead of
.I troff.
Other options are passed to
.I troff.
.SH EXAMPLES
.TP
.L
eval `doctype chapter.?` | apsend
Typeset files named chapter.0, chapter.1, ...
.SH SEE ALSO
.IR troff (1), 
.IR eqn (1), 
.IR tbl (1), 
.IR refer (1), 
.IR prefer (1),
.IR pic (1), 
.IR ideal (1), 
.IR grap (1),
.IR ped (9.1),
.IR mcs (6),
.IR ms (6),
.IR man (6)
.SH BUGS
It's pretty dumb about guessing the proper macro package.
