.TH FILE 1
.CT 1 files 
.SH NAME
file \(mi determine file type
.SH SYNOPSIS
.B file
.I file ...
.PP
.B file
.B -f
.I names
.SH DESCRIPTION
.I File
performs a series of tests on a set of files
in an attempt to classify their contents by language or purpose.
The names may be enumerated or contained in the file specified
by the
.B -f
option.
.SH BUGS
It can make mistakes, for example classifying a file of decimal data,
.LR .01 ,
.LR .02 ,
etc. as
.IR troff (1)
input.
