.TH INTRO 1
.SH NAME
intro \- introduction to commands
.SH DESCRIPTION
This section describes publicly accessible commands
in alphabetic order.
.PP
The name of a particular machine at the head of the
page means that the command lives there and not necessarily
elsewhere.
`Local' means the same, without being specific about where.
.SH SEE ALSO
Section (7) for databases.
.br
Section (8) for `hidden' commands for booting, maintenance, etc.
.br
Section (9) for commands that involve the Teletype 5620 terminal.
.br
.I How to get started,
in the Introduction.
.SH DIAGNOSTICS
Upon termination each command returns two bytes of status,
one supplied by the system giving the cause for
termination, and (in the case of `normal' termination)
one supplied by the program;
see
.IR exit (2).
The former byte is 0 for normal termination, the latter
is customarily 0 for successful execution, nonzero
to indicate troubles such as erroneous parameters, bad or inaccessible data,
or other inability to cope with the task at hand.
It is called variously `exit code', `exit status' or
`return code', and is described only where special
conventions are involved.
