.TH LAB 1 alice
.CT 1 misc
.SH NAME
lab \(mi label maker
.SH SYNOPSIS
.B lab
[
.B -m
]
[
.I file ...
]
.SH DESCRIPTION
.I Lab
causes the
.I files
to be queued for printing as mailing labels.
If no files are named, the standard input is read.
The option
.B -m
causes notification via
.IR mail (1)
to be sent when the job completes.
.PP
The last line of each label is identified by ending it
with one or more spaces and a hyphen.
The hyphen must be the last character in the line;
no white space may follow it.
.SH FILES
.TF  /usr/spool/lab/*
.TP
.F /usr/spool/lab/*
spool area
.TP
.F /usr/lib/lab
printer daemon
.SH SEE\ ALSO
.IR pr (1)
.SH BUGS
Queued jobs print in directory (seemingly random) order.
