.TH LOAD 1
.CT 1 sa_mortals
.SH NAME
load \(mi load statistics
.SH SYNOPSIS
.B load
[
.I interval
[
.I count
[
.I sysfile
[
.I corefile
]
]
]
]
.SH DESCRIPTION
.I Load
reports the number of
processes ready to run averaged over the preceding 1, 5, and 15 minutes.
.PP
The optional
.I interval
argument causes
a report once each
.I interval
seconds.
The first report is for all time since a reboot and each
subsequent report is for the last interval only.
.PP
The optional
.I count
argument restricts the number of reports.
.PP
The optional arguments
.I sysfile
and
.I corefile
cause the named files to be consulted instead of the defaults,
.F /unix
and
.FR /dev/kmem .
.SH FILES
.F /dev/kmem
.br
.F /unix
.SH SEE ALSO
.IR vismon (9.1),
.IR ps (1),
.IR vmstat (8)
