.TH NEWGRP 1
.CT 1 proc_man secur
.SH NAME
newgrp \(mi change to a new group
.SH SYNOPSIS
.B newgrp
.I group
[
.I command
[
.I arg ...
] ]
.SH DESCRIPTION
.I Newgrp
runs a
.I command
with the (real and effective) groupid temporarily set to 
.I group.
If no command is given, the user's shell (see
.IR passwd (5))
is executed.
.PP
A password is demanded if the group has
a password and the user does not.
.SH EXAMPLES
.TP
.L
exec newgrp bin
Restart the shell with a different groupid.
.SH FILES
.F /etc/group
.br
.F /etc/passwd
.SH "SEE ALSO"
.IR login (8), 
.IR getuid (2)
.SH BUGS
On other systems,
.I newgrp
is built into the shell.
Here it will spawn a new shell unless invoked with
.BR exec .
