.TH PLOT 1
.CT 1 comm_dev graphics
.SH NAME
plot \(mi graphics filters
.SH SYNOPSIS
.B plot
[
.BI -T terminal
]
.SH DESCRIPTION
These filters read plotting instructions (see
.IR  plot (5))
from the standard input,
and in general
produce plotting instructions suitable for
a particular
.I terminal
on the standard output.
.PP
If no
.I terminal
type is specified, the environment parameter
.L TERM
(see
.IR environ (5))
is used.
Known
.I terminals
are:
.TP
.B  2621
.PD 0
.TP
.B hp
Hewlett-Packard screen terminal.
.PD
.TP
.B 4014
.PD 0
.TP
.B tek
Tektronix 4014 storage scope.
.PD
.TP
.B troff
Convert to 
.IR troff (1)
input.
.TP
.B 5620
.PD 0
.TP
.B  jerq
Teletype DMD display under
.IR mux (9.1).
The filter persists after plotting, to make a
layer that skips downloading on subsequent plots.
.PD
.TP
.B 750
.PD 0
.TP
.B  pen
Hewlett-Packard pen plotter.
.PD
.SH FILES
.nf
.F /usr/lib/plot/hpplot
.F /usr/lib/plot/trplot
.F /usr/lib/plot/penplot
.F /usr/lib/plot/tek
.F /usr/jerq/bin/jplot
.fi
.SH "SEE ALSO"
.IR plot (3), 
.IR plot (5)
.SH BUGS
A persistent
.I plot
layer on a 5620 terminal imitates
.LR "term 33" , 
it loses most abilities of a
.IR mux (9.1)
layer; see
.IR term (9.1).
.br
Which plotters are known depends on which computer you are on.
