.TH STRINGS 1 
.CT 1 files
.SH NAME
strings \- find printable strings in a file
.SH SYNOPSIS
.B strings
[
.I option ...
] [
.I file ...
.SH DESCRIPTION
.I Strings
looks for and prints 
.SM ASCII
strings in 
.I files.
A string is a sequence of printing characters, tabs, or
backspaces terminated by
a newline or a null character.
In object files, strings are normally
looked for only in the text and data segments.
The options are:
.TP
.B \-t
Look for strings in the text segment of an object file.
.TP
.B \-d
Look for strings in the data segment of an object file.
.TP
.B \-s
Look for symbol strings in the symbol table of an object file.
.TP
.B \-a
Look for strings throughout the file.
.TP
.B \-o
Precede each string by its octal offset in the file.
.TP
\fB\-\fInumber\fR
Ignore strings less than
.I number
characters long (excluding newlines).
Default length is 4.
.PP
.I Strings
is useful for identifying random object files and many other things.
.SH "SEE ALSO"
.IR gre (1),
.IR xd (1)
.SH BUGS
Newlines are quietly inserted in very long strings.
