.TH VIS 1
.CT 1 files
.SH NAME
vis \- show invisible characters
.SH SYNOPSIS
.B vis
[
.B -t
]
[
.B -s
]
[
.I file ...
]
.SH DESCRIPTION
.I Vis
reads each
.I file
in sequence and writes it on the standard output.
Non-printing characters are translated on output as in the 
.L l
command of
.IR ed (1).
If no
.I file
is given
.I vis
reads from the standard input.
The options are
.TP
.B -t
Do not translate tabs.
.TP
.B -s
Strip invisible characters; same effect as
.BR "tr -cd '" <tab><newline><space> -~' .
.SH SEE ALSO
.IR cat (1), 
.IR ed (1),
.IR xd (1)
