.TH WC 1
.CT 1 files writing_aids
.SH NAME
wc \- word count
.SH SYNOPSIS
.B wc
[
.B -lwc
]
[
.I file ...
]
.SH DESCRIPTION
.I Wc
counts lines, words and characters in the named
.I files,
or in the standard input if no file is named.
A word is a maximal string of characters
delimited by spaces, tabs or newlines.
.PP
If the optional argument is present,
just the specified counts (lines, words or characters)
are selected by the letters
.BR l ,
.BR w ,
or
.BR c .
