.TH WWV 1
.CT 1 time_man sa_mortals
.SH NAME
wwv \- print or set the date from accurate clock
.SH SYNOPSIS
.B wwv
[ option ... ]
.SH DESCRIPTION
.I Wwv
connects to a clock synchronized with a time standard.
With no argument it prints the time obtained.
It accepts these options:
.TP
.B -b
Print both the
.SM WWV
time and the system's current idea of the time.
.TP
.B -s
Set the system's time to agree with
.SM WWV.
Only the super-user can do this.
The system time cannot be changed by more than 20 minutes.
.TP
.B -f
With
.BR -s ,
force the time to be set by
.SM WWV
even if the local time disagrees
by more than 20 minutes.
.TP
.B -u
Report time in
.SM GMT
rather than local time.
.SH FILES
.F /usr/adm/wtmp
to record time-setting; see
.IR utmp (5)
.SH SEE ALSO
.IR date (1), 
.IR time (2),
.IR stime (2)

