.TH POSTNEWS 7 alice
.CT 1 comm_users
.SH NAME
postnews \(mi submit netnews articles
.SH SYNOPSIS
.B postnews
[
.I file
]
.SH DESCRIPTION
.I Postnews
submits the
.I file
as a
.IR readnews (7)
article.
It prompts for title,
primary newsgroup, and other newsgroup distribution.
Good manners decree an informative title and accurate, minimal,
distribution.
.PP
The names of newsgroups are relative pathnames
of directories depending from
.FR /usr/spool/news ,
with slashes
replaced by dots.
.PP
If no file is specified,
.I postnews
invokes an editor specified by the environment variable
.B EDITOR
(default
.LR vi ).
The editor's buffer is initialized with header information,
which may be changed.
The text of the article may be appended.
.SH "SEE ALSO"
.IR readnews (7)
.br
BSD manual for more sophisticated uses,
such as posting news from a program.
.SH BUGS
The editor default is distinctly nonclassical.
