.TH SKY 7 bowell
.CT 1 inst_info
.SH NAME
sky \- astronomical ephemeris
.SH SYNOPSIS
.B sky
[
.B -l
]
.SH DESCRIPTION
.I Sky
predicts the apparent locations of the sun, moon, visible planets,
and stars brighter than magnitude 2.5.
It reads one line from the standard input to obtain the desired time
expressed as five numbers: year, month, day, hour, and minute in GMT.
An empty line means now.
Each object is printed with astronomical coordinates, azimuth-elevation
coordinates relative to Murray Hill, NJ, and magnitude.
For variable stars the maximum magnitude is printed with 
.LR * .
.PP
Option 
.B -l
causes
.I sky 
to prompt for another viewing location.
.PP
Standard astronomical effects are accounted for:
nutation and precession of the equinox, annual aberration, diurnal parallax,
and proper motion.
Atmospheric effects (extinction and refraction) are not calculated,
nor is perturbation of the earth by other bodies.
.PP
In ephemeris (slighly different from civil) time, the program
yields
positions of sun, moon, and stars good to a few tenths of an
arc-second.
Planets are good to a few seconds.
.SH FILES
.F /usr/lib/startab
.SH SEE ALSO
.IR scat (7)
.br
.I
American Ephemeris and Nautical Almanac
and
.I
Explanatory Supplement to the American Ephemeris and Nautical Almanac
