.TH TOWN 7 alice
.CT 1 inst_info
.SH NAME
town \- gazetteer of US places
.SH SYNOPSIS
.B town
[
.I place
]
.SH DESCRIPTION
.I Town
produces information about the
.I place,
which is the name of a US town, possibly followed by a comma
and a two-letter state abbreviation.
If no
.I place
is given, place names are read one per line from the
standard input.
.PP
The information produced is latitude, longitude, approximate
population, a forecast from
.IR weather (7),
and a recent item from
.IR apnews (7).
.SH FILES
.F /usr/spool/town/ustown*
gazetteer in
.IR cbt (1)
format
.SH SEE ALSO
.IR av (A),
.IR dict (7)
