.TH WEATHER 7  alice
.CT 1 inst_info
.SH NAME
weather \- conditions and forecast by town
.SH SYNOPSIS
.B weather
[
.B -h
]
[
.B -m
]
.SH DESCRIPTION
.I Weather
reports current weather conditions and a forecast for towns
in the contiguous United States.
It reads town names from the standard input, one per line.
Each input line should be in the style of
.IP
.L walla walla, wa
.LP
where the state is given as the 2-letter Post Office abbreviation.
.PP
The information provided is the temperature, humidity, whether or not it
is raining or snowing, and an indication of cloudiness and visibility
if it is not.
If the wind is above 10 knots the wind speed and
direction are given.
Up to three forecasts are given (assuming they can be found within
a 4\(mu4 degree latitude-longitude square): a forecast of high
and low temperatures plus probability of precipitation taken from
some numerical model of the atmosphere, a general area forecast
and a marine forecast (if near the coast and if the
.B -m
argument is given).
.PP
The command
.B "weather -h"
is equivalent to
.L weather
followed by a single input
line of
.LR "murray hill, nj" .
.SH SEE ALSO
.IR avw (A)
