all:
	cd hped; make
	cd dped; make
	cd tped; make
install:
	cd hped; make install
	cd dped; make install
	cd tped; make install
	cp doc/* /usr/jerq/lib/ped
clean:
	cd hped; make clean
	cd dped; make clean
	cd tped; make clean
