.TH BESSEL 3M
.CT 2 math
.SH NAME
besj0, besj1, besjn, besy0, besy1, besyn \(mi bessel functions
.SH SYNOPSIS
.nf
.B #include <math.h>
.PP
.B double besj0(x)
.B double x;
.PP
.B double besj1(x)
.B double x;
.PP
.B double besjn(n, x)
.B double x;
.PP
.B double besy0(x)
.B double x;
.PP
.B double besy1(x)
.B double x;
.PP
.B double besyn(n, x)
.B double x;
.fi
.SH DESCRIPTION
These functions calculate Bessel functions of the first
and second kinds for real arguments and integer orders.
.SH DIAGNOSTICS
Negative arguments cause
.I besy0, besy1,
and
.I besyn
to return a huge negative value
and set
.I errno
to
.BR EDOM .
