.TH FERROR 3S
.CT 2 file_io file_inq_creat
.SH NAME
feof, ferror, clearerr, fileno \(mi stream status inquiries
.SH SYNOPSIS
.B #include <stdio.h>
.PP
.B int feof(stream)
.br
.SM
.B FILE
.B *stream;
.PP
.B int ferror(stream)
.br
.SM
.B FILE
.B *stream
.PP
.B int clearerr(stream)
.br
.SM
.B FILE
.B *stream
.PP
.B int fileno(stream)
.br
.SM
.B FILE
.B *stream;
.SH DESCRIPTION
.I Feof
returns non-zero if end of file has been encountered on the named input
.I stream,
otherwise zero.
After returning
.BR EOF ,
.IR stdio (3)
functions will not necessarily return
.BR EOF
again; 
.I feof
provides a lasting indication.
.PP
.I Ferror
returns non-zero when an error has occurred reading or writing
the named
.I stream,
otherwise zero.
Unless cleared by
.I clearerr,
the error indication lasts until
the stream is closed.
.PP
.I Clearerr
resets the error indication on the named
.I stream.
.PP
.I Fileno
returns the integer file descriptor
associated with the
.I stream,
see
.IR  open (2).
.PP
These functions
are implemented as macros;
they cannot be redeclared.
.SH "SEE ALSO"
.IR stdio (3)
