.TH GAMMA 3M
.CT 2 math
.SH NAME
gamma \(mi log gamma function
.SH SYNOPSIS
.nf
.B #include <math.h>
.PP
.B double gamma(x)
.B double x;
.PP
.B extern int signgam;
.fi
.SH DESCRIPTION
.I Gamma
returns
ln |\(*G(\|\fIx\fP\|)|.
The sign of
\(*G(\|\fIx\fP\|)
is returned in the external integer
.IR signgam .
.SH EXAMPLES
Computation of the gamma function:
.PP
.nf
.ta 8n +8n
.ft L
	errno = 0;
	y = gamma(x);
	if(errno || (y > 88.0))
		error();
	y = signgam*exp(y);
.fi
.ft P
.SH DIAGNOSTICS
A large value
.RL ( HUGE )
is returned for negative integer arguments
and
.I errno
is set to
.BR EDOM .
.SH BUGS
There should be a positive indication of error.
.br
The name should indicate the answer is a logarithm,
perhaps
.IR lgamma .
