.TH GETARG 3F
.CT 2 data_man
.SH NAME
getarg, iargc \(mi command arguments to Fortran
.SH SYNOPSIS
.nf
.B subroutine getarg(argno, string)
.B integer argno
.B character *(*) string
.PP
.B iargc()
.fi
.SH DESCRIPTION
These procedures permit Fortran programs to access the command arguments.
The integer function
.I iargc
returns the number of command arguments.
The subroutine
.I getarg
stores the
.IR argno th
command argument in its second argument.
The string is truncated or padded with blanks,
in accord with the rules of Fortran character assignment.
.SH EXAMPLES
.TP
.L
a.out arg1 arg2
In a program invoked this way
.I iargc
will return 2.
.TP
.L
character*4 s
.br
.ns
.TP
.L
call getarg(2, s)
Place
.L arg2
in
.I s.
.SH "SEE ALSO"
.IR exec (2)
