.TH GETENV 3
.CT 2 data_man
.SH NAME
getenv \(mi value for environment name
.SH SYNOPSIS
.nf
.B char *getenv(name)
.B char *name;
.fi
.SH DESCRIPTION
.I Getenv
searches the environment list
(see
.IR environ (5))
for a string starting with
\fIname\fL=\fR.
If no such a string is found, 0
is returned.
Otherwise,
the address of the character following the
.L =
is returned.
.SH SEE ALSO
.IR printenv (1),
.IR environ (5), 
.IR exec (2)
.SH BUGS
.I Getenv
ignores shell functions; see 
.IR sh (1).
