.TH GETLOGIN 3
.CT 2 secur
.SH NAME
getlogin \(mi get login name
.SH SYNOPSIS
.B char *getlogin()
.SH DESCRIPTION
.I Getlogin
returns a pointer to
the login name
as set by
.IR setlogname ;
see
.IR getuid (2).
.PP
It is preferable, but less portable, to call
.IR getlogname ;
see
.IR getuid (2).
.SH FILES
.TP
.F /etc/utmp
.SH "SEE ALSO"
.IR getpwent (3), 
.IR getgrent (3), 
.IR utmp (5), 
.IR getuid (2)
.SH DIAGNOSTICS
Zero is returned if the name could not be found.
.SH BUGS
The return values point to static data
whose content is overwritten by each call.
