.TH INTRO 3
.SH NAME
intro \(mi introduction to library functions
.SH SYNOPSIS
.nf
.B #include <libc.h>
.PP
.B #include <stdio.h>
.PP
.B #include <math.h>
.fi
.SH DESCRIPTION
This section describes functions that may be found
in various libraries, other than the system calls
described in section 2.
Functions are divided into various libraries distinguished
by the section number at the top of the page:
.TP 
(3)
These functions, together with those of section 2 and those
marked (3S) and (3M), constitute library
.I libc,
which is automatically loaded by the C compiler
.IR cc (1)
and the Fortran compiler
.IR f77 (1).
The same functions appear also in
.IR libC,
which is automatically loaded by the C++ compiler; see
.IR c++ (1).
The link editor
.IR ld (1)
searches this library under option
.BR \-lc 
.RB ( -lC
for 
.IR libC ).
Declarations for some of these functions may be obtained
from include files indicated on the appropriate pages.
Other declarations can be found in
.FR <libc.h> .
.TP
(3F)
These functions are in the Fortran library,
.I libF77,
automatically loaded by the Fortran compiler, and searched
under option
.B -lF77
of the link editor.
.TP
(3M)
These functions constitute the math library, part of
.I libc.
(On some other systems they must be loaded by
.BR -lm ).
Declarations for these functions may be obtained from
the include file
.FR <math.h> .
.TP
(3S)
These functions constitute the
`standard IO package'
(see
.IR stdio (3))
part of
.I libc
already mentioned.
Declarations for these functions may be obtained from
the include file
.FR <stdio.h> .
.TP
(3X)
Various
specialized libraries have not been given distinctive
captions.
Files in which such libraries are found are named
on appropriate pages.
.TP
(3+)
C++ functions in
.I libC
that are not in
.I libc.
.SH FILES
.TP
.F /lib/libc.a
.SH SEE ALSO
.IR stdio (3),
.IR nm (1), 
.IR ld (1), 
.IR cc (1),
.IR c++ (1), 
.IR f77 (1), 
.IR intro (2)
.SH DIAGNOSTICS
Functions in the math library (3M) may return
conventional values when the function is undefined for the
given arguments or when the value is not representable.
In these cases the external variable
.I errno
(see
.IR intro (2))
is set to the value
.B EDOM
or
.BR ERANGE ,
defined in
the include file
.FR <math.h> .
