.TH SINH 3M
.CT 2 math
.SH NAME
sinh, cosh, tanh \(mi hyperbolic functions
.SH SYNOPSIS
.nf
.B #include <math.h>
.PP
.B double sinh(x)
.br
.B double x;
.PP
.B double cosh(x)
.B double x;
.PP
.B double tanh(x)
.B double x;
.fi
.SH DESCRIPTION
These functions compute the designated hyperbolic functions
for real arguments.
.SH DIAGNOSTICS
.I Sinh
and
.I cosh
return a huge value of appropriate sign
when the correct value would overflow
and set
.I errno
to
.LR EDOM .
