.TH SWAB 3
.CT 2 data_man
.SH NAME
swab \(mi swap bytes
.SH SYNOPSIS
.nf
.B swab(from, to, nbytes)
.B char *from, *to;
.fi
.SH DESCRIPTION
.I Swab
copies
.I nbytes
bytes pointed to by
.I from
to the position pointed to by
.I to,
exchanging adjacent even and odd bytes.
It is useful for carrying binary data between
machines with different byte orders.
.I Nbytes
should be even.
