.TH SYSTEM 3
.CT 2 proc_man
.SH NAME
system \(mi issue a shell command
.SH SYNOPSIS
.nf
.B system(string)
.B char *string;
.fi
.SH DESCRIPTION
.I System
causes the command
\fLsh -c \fIstring\fR
to be executed.
The current process waits until the shell has
completed, then returns the exit status of the shell.
.SH "SEE ALSO"
.IR popen (3),
.IR exec (2), 
.IR fork (2)
.SH DIAGNOSTICS
Exit status 127 indicates the shell couldn't be executed.
