.TH APSEND 1 
.CT 1 writing_output comm_dev
.SH NAME
apsend \- send troff output to phototypesetter
.SH SYNOPSIS
.B apsend 
[
.I options
]
[
.I file ...
]
.SH DESCRIPTION
.I Apsend
sends
.IR troff (1)
output from the named files or from the standard input
to the Murray Hill computer center for high-quality typesetting.
.PP
The options, which need only be spelled far enough to be unique, are
.TF comment=xx
.TP
.BI account= xx
comp center account number (default from password file)
.PD
.TP 
.BI bin= xx
comp center bin number (default from password file)
.TP 
.BI mailto= xx
mailing instructions, up to 28 characters, instead of comp center bin
.TP 
.BI comment= xx
up to 30 characters, for
.F APSLOG
file entry (default value is
.I file
or
.LR pipe.end )
.TP 
.BI device=imagen
Print on laser printer instead of phototypesetter.
.SH FILES
.TF /usr/lib/apsend/*
.TP
.F /usr/lib/apsend/*
.TP
.F APSLOG
record of apsend activity
.SH SEE ALSO
.IR troff (1), 
.IR lp (1),
.IR font (5)
.SH BUGS
Do not be misled by the historical name of this program.
The correct 
.I troff
device selection is
.BR -Tpost ,
which is fortunately the default.
