.TH CB 1 
.CT 1 prog_c writing_output
.SH NAME
cb \- C program beautifier
.SH SYNOPSIS
.B cb
[
.I option ...
]
[
.I file ...
]
.SH DESCRIPTION
.I Cb
reads C programs either from the named
.I files
or from the
standard input
and writes them
on the standard output with spacing and indentation
that displays the structure of the code.
The options are:
.TP
.B -s
Place newlines as in
Kernighan and Ritchie.
(Original newlines are preserved by default.)
.TP
.B -j
Join split lines.
.TP
.BI -l " leng"
Split lines that are longer than
.I leng,
120 by default.
.SH "SEE ALSO"
.IR pr (1), 
.IR troff (1), 
.IR lp (1),
.IR font (6)
.br
B. W. Kernighan and D. M. Ritchie,
.I "The C Programming Language,"
Prentice-Hall, 1988.
.SH BUGS
Punctuation hidden in
preprocessor statements causes
.I cb
to make indentation errors.
