.TH DOCGEN 1 
.CT 1 writing_aids
.SH NAME
docgen \- generate a document from a script
.SH SYNOPSIS
.B docgen
[
.I option  ...
]
[
.I ofile
]
.SH DESCRIPTION
.I Docgen
guides interactive preparation of standard documents
according to canned scripts and
places the output in
.I ofile.
The output typically takes the form of
.IR troff (1)
input.
These options invoke standard scripts:
.TP
.B -mcs
(default) Bell Labs cover sheet; output (\c
.F temp.cover
by default)
may be typeset thus: 
.L "troff temp.cover"
.TP
.B -ms
documents using the macro package
.IR ms (6);
output
.RF ( temp
by default) may be typeset thus:
.L "troff -ms temp"
.TP
.B -mm
similarly for the MM macro package of System V
.PP
Other options are:
.TP
.BI -f " file"
take script from 
.I file
.TP
.B -v
(verbose) print document as it is generated
.TP
.B -d
(debug) print information about the script
as it is read
.PP
The reference tells how to construct scripts.
.SH FILES
.F /usr/lib/docgen/*
scripts
.br
.F temp.cover
.br
.F temp
.SH "SEE ALSO"
.IR troff (1), 
.IR ms (6), 
.IR mcs (6)
.SH BUGS
Not all document types are implemented.
