.TH GETUID 1
.CT 1 proc_man secur
.SH NAME
getuid, id \(mi get user identity
.SH SYNOPSIS
.B getuid
[
.B -
]
[
.I arguments
]
.PP
.B id
.SH DESCRIPTION
.I Getuid
prints on its standard output information about its invoker,
based on the effective user id, as presented in the password file.
With no arguments,
.I getuid
prints the login id of its invoker.
Arguments select which information to print:
.IP
.TF passwd
.TP
.B user
login id
.TP
.B group
group id
.TP
.B passwd
encrypted password
.TP
.B uid
numerical user id
.TP
.B gid
numerical group id
.TP
.B acct
comp center account number
.TP
.B bin
comp center output bin
.TP
.B home
home directory
.TP
.B shell
default shell
.PD
.PP
If the optional
.B -
or more than one argument is present,
the information is displayed in the form
.IP
user=name
.LP
as suitable for setting environment variables in the shell.
.PP
.I Id
prints the effective userid and groupid
and the login name.
The userid and groupid are printed numerically and, if
possible, textually.
.SH FILES
.TP
.F /etc/passwd
.TP
.F /etc/group
.SH "SEE ALSO"
.IR who (1), 
.IR getuid (2), 
.IR passwd (5), 
.IR newgrp (1)
.SH BUGS
.I Getuid
reports the default group for the user,
not the current effective group id.
.br
The login id reported is the first one in the password file with
the correct numerical user id, not necessarily the login
for the current session.
