.TH HANG 1
.CT 1 proc_man debug_tune
.SH NAME
hang \(mi start a process in stopped state
.SH SYNOPSIS
.B hang
.I command
.SH DESCRIPTION
The given command is executed, but stopped before 
.B main()
is called so that
the process can be picked up by a debugger.
To ensure that breakpoints may be set, the process does not share its text.
.SH SEE ALSO
.IR pi (9.1), 
.IR kill (1)
