.TH IMSCAN 1 "arend"
.CT 1 graphics
.SH NAME
imscan \(mi scan greyscale images
.SH SYNOPSIS
.B imscan
[
.BI -s N
]
[
.BI -l N
]
.I file
.SH DESCRIPTION
.I Imscan
digitizes an image with an Imagitex grey-scale scanner
and places the result in the named file in the form of
.IR picfile (5).
The options are
.TP
.BI -s N
Set a scale factor 
.RI 1\(<= N \(<=9,
default 4.
With scale factor
.I N
the image is subsampled: only 1 out of every
.I N\(muN
pixels is stored. 
A larger scale factor, therefore, produces a smaller image.
.TP
.BI -l N
Use lens focal length
.I N,
where
.I N
is either 5 or 8 (default).
The 8-inch lens scans images at 480 dots per inch.
The 5-inch lens scans at 754 dots per inch.
.SH "SEE ALSO"
.IR cscan (1),
.IR pico (1),
.IR qsnap (1),
.I mugs
in
.IR face (9.7),
.IR picfile (5)
.SH BUGS
It is hard to get more than 2000 pixels per scanline reliably.
For large originals, higher scale factors work better than 
smaller ones.
