.TH MKDIR 1
.CT 1 dirs
.SH NAME
mkdir \(mi make a directory
.SH SYNOPSIS
.B mkdir
.I dirname ...
.SH DESCRIPTION
.I Mkdir
creates specified directories
in mode 777, subject to masking by
.IR umask (2).
Standard entries,
.RB ` . ',
for the directory itself,
and
.lg 0
.RB ` .. '
.lg 1
for its parent, are made automatically.
.PP
.I Mkdir
requires write permission in the parent directory.
.SH "SEE ALSO"
.IR rm (1)
.IR cd
in
.IR sh (1)
.SH DIAGNOSTICS
.I Mkdir
returns exit code 0 if all directories were successfully made.
Otherwise it prints a diagnostic and returns nonzero.
