.TH NICE 1
.CT 1 proc_man
.SH NAME
nice, nohup \(mi run commands at low priority or immune to hangup
.SH SYNOPSIS
.B nice
[
.BI - number
]
.I command
[
.I argument ...
]
.PP
.B nohup
.I command
[
.I argument ...
]
.SH DESCRIPTION
.I Nice
executes
.I command
with low scheduling priority.
If the
.I number
argument is present, the priority is incremented (higher
numbers mean lower priorities) by that amount up to a limit of 19.
The default
.I number
is 10.
.PP
The super-user may run commands with
priority higher than normal
by using a negative
.I number,
e.g.
.LR --10 .
.PP
.I Nohup
executes
.I command
immune to hangup and terminate signals from the controlling terminal.
The priority is incremented by 5.
.PP
Any output not explicitly redirected is appended to
the file
.F nohup.out
in the current directory.
.SH FILES
.FR nohup.out
default destination for standard output and standard error
.SH "SEE ALSO"
.IR nice (2)
.SH DIAGNOSTICS
.I Nice
returns the exit status of the subject command.
.SH BUGS
Quoted
.I arguments
don't work right in all cases.
The difficulty may be avoided by quoting the
.I command,
with arguments in inner quotes.
