.TH P 1
.CT 1 comm_term
.SH NAME
p, pg, more \(mi paginate
.SH SYNOPSIS
.B p
[
.BI - number
]
[
.I file ...
]
.SH DESCRIPTION
.I P
copies its standard input, or the named files if given,
to its standard output,
stopping at the end of every 22nd line, and between files,
to wait for a newline from the user.
The page size may be set by
saying (for example)
.IP
.L p -60
.PP
While waiting for a newline,
.I p
interprets some commands:
.TP
.B -
Reprint last page. 
.L --
reprints the second last page, etc.
.TP
.B !
Pass the rest of the line to the shell as a command.
.TP
.B q
Quit.
.PP
.I Pg
and
.I more
are synonyms for
.I p.
.SH BUGS
Because of limited storage,
.I p
can't back up too far.
.br
.I Pg
and 
.I more
exist only to placate old programs that call paginators.
