.TH PRINTENV 1
.CT 1 shell
.SH NAME
printenv \- print environment
.SH SYNOPSIS
.B printenv
[
.I name
]
.SH DESCRIPTION
With no arguments,
.I printenv
places the strings of the environment, described in
.IR environ (5),
on the standard output one per line.
.PP
If a
.I name
is specified, its value is retrieved from the environment
and printed.
.SH SEE ALSO
.IR sh (1),
.IR rc (1),
.IR environ (5),
.IR getenv (3)
.SH DIAGNOSTICS
Exit status 1 is returned when a specified
.I name
is not present in the environment.
.SH BUGS
The
.I name
feature cannot handle functions.
