.TH RANDOM 1
.CT 1 files games
.SH NAME
random, fortune \- sample lines from a file, return cookies
.SH SYNOPSIS
.B random
[
.B -e
]
[
.I n
]
.PP
.B /usr/games/fortune
[
.I file
]
.SH DESCRIPTION
.I Random
reads the standard input and copies each line to the
standard output with probability
.RI 1/ n.
The default value of
.I n
is 2.
.PP
Option
.B -e
writes no output and returns a random exit code in the
range
.RI [0, n \-1].
.PP
.I Fortune
prints a one-line aphorism chosen at random.
If a
.I file
is specified, the saying is taken from that file;
otherwise it is selected from
.FR /usr/games/lib/fortunes .
.SH FILES
.F /usr/games/lib/fortunes
.br
.F /usr/games/lib/fortunes.index
fast lookup table, maintained automatically
.SH BUGS
Successive results of option
.B -e
are highly correlated if
.I random
is called more than once per second.
