.TH SLEEP 1
.CT 1 proc_man
.SH NAME
sleep \- suspend execution for an interval
.SH SYNOPSIS
.B sleep
.I time
.SH DESCRIPTION
.I Sleep
suspends execution for
.I time
seconds.
.SH EXAMPLES
.TP
.L (sleep 100; command)&
Execute a command
100 seconds hence.
.PP
.EX
while :
do
	command
	sleep 30
done
.EE
.ns
.IP
Repeat a command every 30 seconds.
.SH "SEE ALSO"
.IR alarm (2), 
.IR sleep (3)
