.TH STRIP 1
.CT 1 lib_obj
.SH NAME
strip \- remove symbols and relocation bits
.SH SYNOPSIS
.B strip
[
.B -s
]
[
.B -g
]
[
.B -v
]
.I file ...
.SH DESCRIPTION
.I Strip
removes the symbol
table and relocation bits ordinarily attached to the output
of the assembler and loader.
This saves space and hampers debuggers.
Option
.B -s
of
.IR ld (1)
does the same thing.
The options are
.TP
.B -s
Squeeze the symbol table by removing duplicate information.
.TP
.B -g
Delete line-number information, thus negating the
effect of
.LR "cc -g" .
Implies
.BR -s .
.TP
.B -v
Print size information.
.SH FILES
.F shrink?
temporary file
.SH "SEE ALSO"
.IR cc (1), 
.IR ld (1)
