.TH TABS 1
.CT 1 comm_term
.SH NAME
tabs \- set terminal tabs
.SH SYNOPSIS
.B tabs
[
.BI + num
]
[
.BI -T term
]
.SH DESCRIPTION
.I Tabs
sets the tabs on a variety of terminals.
.I Term
is a name given in
.IR term (6).
The name may also be supplied by the environment variable
.LR TERM .
.PP
The
.BI + num
option offsets the left margin
.I num
positions.
.SH SEE ALSO
.IR stty (1), 
.IR term (6), 
.IR tset (A)
