.TH TAPE 1
.CT 1 comm_dev
.SH NAME
tape, mt \- identify and manipulate magnetic tape
.SH SYNOPSIS
.B tape
.PP
.B mt
[
.B -t
.I tapename
]
.I command
[
.I count
]
.SH DESCRIPTION
.I Tape
experiments with the magnetic tape drive and reports
under which device name the tape mounted there can be read,
how many files and records there are, and how big the records are.
.I Mt
applies a
.I command
to the named tape drive (default
.FR /dev/nrmt1 )
.I count
times (default 1).
The
.I commands
are
.TF offline
.TP
.B eof
write end-of -file mark
.PD0
.TP
.B fsf
forward space file
.TP
.B fsr
forward space record
.TP
.B bsf
backspace file
.TP
.B bsr
backspace record
.TP
.B rewind
rewind
.TP
.B offline
rewind and take off line
.PD
.SH FILES
.F /dev/nrmt1
.SH SEE ALSO
.IR mt (4), 
.IR dd (1)
