.TH UL 1
.CT 1 comm_term
.SH NAME
ul \- print underlines on screen terminals
.SH SYNOPSIS
.B ul
[
.B -i
]
[
.B -t
.I terminal
]
[
.I file ...
]
.SH DESCRIPTION
.I Ul
replaces backspaced, overstruck underscores by control sequences suitable
for the terminal given by the environment variable
.L TERM
or by option
.BR -t .
It reads from the standard input or the named files and
writes on the standard output.
Option
.B -i
represents underlining by a separate line of 
.L -
characters.
.SH SEE ALSO
.IR column (1)
