CC=3cc
CFLAGS=-g

all:	 dtoc showbits view finv

dtoc:	dtoc.c
	$(CC) $(CFLAGS) -o dtoc dtoc.c

finv:	finv.c
	$(CC) $(CFLAGS) -o finv finv.c

showbits:	showbits.c
	$(CC) $(CFLAGS) -o showbits showbits.c

view:	view.c
	$(CC) $(CFLAGS) -o view view.c
