.TH REBECCA 9.1 
.SH NAME
rebecca \- editor for digitized images
.SH SYNOPSIS
.B rebecca
file
.SH DESCRIPTION
.I Rebecca
is an interactive retouching tool for digitized grayscale images.
The argument given must be a 262144 byte file containing
a headerless 512x512 black&white digitized image.
Example (read only) files are on kwee in directory /t0/face/512x512x8,
and on arend in /usr/snet/Faces.
.LP
All editing options in
.I rebecca
are implemented with "floating instruments."
These instruments (except the image box and the grey-scale below
it) can be dragged to different locations by clicking button 2
at them and, while holding button 2 down, moving to a new location.
They cannot be placed on top of the image or the grey scale.
.LP
.B Resolution
.IP
The tick mark on the long rectangular bar
can be moved up or down with button 1.
Upon selection the current resolution is printed
to the right of the bar.
The resolution is always a power of 2 between 2 and 512
low numbers mean high resolutions (pixels per square displayed).
.LP
.B Grid
.IP
Click button 1 at the circular button to toggle the grid.
Turning on the grid is useful sometimes to see how
fast a screen update is proceeding: it eats away the grid.
.LP
.B Write
.IP
Write the file on the host by clicking button 1 at the box labeled 'write'.
The write box has a '*' if a change was made to
the file since it was last written.
.LP
.B "Runlength encoding"
.IP
Clicking button 1 at this box toggles transmission mode between
runlength encoding and unencoded data.
Runlength encoding can optimize speed of downloads in some cases.
.LP
.B Reopen
.IP
Selecting this instrument cancels any changes made to the file
since the last time it was written. It invalidates the image cache
and reads the file back in. It is an "undo" operation.
.LP
.B Move/Pan
.IP
Click button 1 at one of the 5 areas of the tilted square box.
Selecting the middle will reset the display to an unzoomed
full size picture. Selecting
left, right, up, or down will move (pan) 1/4 screen in the
corresponding direction. (This is useful only when you selected
'zoomed' before.)
.LP
.B "Zoom/Unzoom"
.IP
Click button 1 at Z (zoom) or U (unzoom).
Z prompts with a square box that you can position on the area
of the picture you want to zoom into and inspect at full resolution.
If you click button 1, before you confirm the selection, the sides
of the box are halfed. Clicking button 2 doubles them.
Clicking button 3 confirms the selection and performs the zoom.
Any combination of two buttons cancels the zoom.
.LP
.B Paint
.IP
Click button 1 at the box labeled "+ = -".
Selecting "+" enables incremental painting (add grey values to pixels).
Selecting "=" gives absolute painting (assigning values).
And selecting "-" gives decremental painting (subtracting values).
.IP
Click button 1 at a pixel location to apply the paint
Click button 3 to sweep a rectangle to paint all pixels within it
Clicking button 2 at the paint box cancels the paint mode
.IP
Select a paint value (default is white) by
clicking button 2 at the grey scale ruler at the bottom
of the screen. Equivalently you can pick up a grey value by clicking
button 2 at any pixel in the image displayed.
.LP
.B Smearing
.IP
Another standard paint option is independent of
the paint box mode: pointing at a pixel and clicking button
1 and 2 simultaneously will average that pixel with the
surrounding 8 pixels (most useful when zoomed in to pixel level).
Typical usage: apply some white or black paint with the paint box,
then smear it using button 1&2.
.LP
.B Probe
.IP
Click button 1 at the probe box (labeled "P: ").
Point at a pixel in the image. Three values will be printed in
the probe box: the x and y coordinate and the greyscale value of the pixel.
.LP
.B Contrast
.IP
Move the left end or right end of the line under the
grey scale bar around to expand or compress the grey-scale.
It works like a look-up table. Only the appearance of the
picture on the display will change, not the image file itself.
.LP
.B "Rubber Sheet"
.IP
Selecting the box named "sheet"
prompts for a rectangle. Sweep out the rectangle over an
area you want to copy, stretch, or in any way change in
size. After sweeping the rectangle reposition the corners
by dragging them to new locations with button 1.
Confirm the selection with button 3.
The update itself may take a while. Meanwhile, all other edit
remain selectable (you can "edit ahead").
.SH "SEE ALSO"
pico(1), flicks (9.1), pvmon(9.1)
