LIB=./libB.a
CFLAGS=-O -I.
#
#	EXECUTABLE  FILE DEPENDS ON THE ARCHIVE FILE
#
 bite: $(LIB)
# The following commented out line can be inserted for Berkley VMUNIX V4.1
#	ranlib $(LIB)
	cc -i -s -o bite $(LIB) -lm
#
#	THE ARCHIVE DEPENDS ON EACH MEMBER ".o" FILE WHICH AUTOMATICALLY
#	DEPEND ON THEIR CORRESPONDING ".c" FILES
#
 .PRECIOUS: $(LIB)

 $(LIB): $(LIB)(basic.o) $(LIB)(bed.o) $(LIB)(encode.o) \
$(LIB)(dim.o) $(LIB)(load.o) $(LIB)(save.o) \
$(LIB)(no_op.o) $(LIB)(pause.o) $(LIB)(list.o) \
$(LIB)(lnpars.o) $(LIB)(fetch.o) $(LIB)(run.o) \
$(LIB)(common.o) $(LIB)(let.o) $(LIB)(if.o) \
$(LIB)(print.o) $(LIB)(input.o) $(LIB)(evalx.o) \
$(LIB)(evals.o) $(LIB)(chr.o) $(LIB)(ext.o) \
$(LIB)(left.o) $(LIB)(right.o) $(LIB)(string.o) \
$(LIB)(str.o) $(LIB)(up-lo.o) \
$(LIB)(len.o) $(LIB)(val.o) $(LIB)(asc.o) \
$(LIB)(class.o) $(LIB)(expunge.o) \
$(LIB)(variable.o) $(LIB)(error.o) $(LIB)(goto.o) \
$(LIB)(isthere.o) $(LIB)(strcat.o) $(LIB)(stop.o) \
$(LIB)(gosub.o) $(LIB)(for.o) $(LIB)(atof1.o) \
$(LIB)(clear.o) $(LIB)(delete.o) $(LIB)(new.o) \
$(LIB)(put.o) $(LIB)(update.o) $(LIB)(cover.o) \
$(LIB)(corleft.o) $(LIB)(sub.o) $(LIB)(getdims.o) \
$(LIB)(random.o) $(LIB)(getfnam.o) $(LIB)(f.o) \
$(LIB)(avars.o) $(LIB)(svars.o) $(LIB)(reseq.o) \
$(LIB)(savars.o) \
$(LIB)(sing.o) $(LIB)(equal.o) \
$(LIB)(sysls.o) $(LIB)(sysrm.o) $(LIB)(bsys.o) \
$(LIB)(chksec.o) \
$(LIB)(old.o) $(LIB)(bfiles.o) $(LIB)(bseek.o) $(LIB)(copen.o) \
$(LIB)(read.o) $(LIB)(on.o) $(LIB)(minus.o) \
$(LIB)(iprintf.o) $(LIB)(call.o) $(LIB)(postb.o) \
$(LIB)(pathopen.o) $(LIB)(belse.o) $(LIB)(untilcod.o) \
$(LIB)(auto.o) $(LIB)(more.o) $(LIB)(fact.o) $(LIB)(rand.o)
#
#	MANY OF THE ".o"  FILES DEPEND ON A HEADER FILE
#
#$(LIB)(atof1.o) $(LIB)(avars.o) $(LIB)(svars.o) \
#$(LIB)(basic.o) $(LIB)(bed.o) $(LIB)(bfiles.o) \
#$(LIB)(bsys.o) $(LIB)(class.o) $(LIB)(clear.o) \
#$(LIB)(common.o) $(LIB)(copen.o) $(LIB)(corleft.o) \
#$(LIB)(cover.o) $(LIB)(delete.o) $(LIB)(dim.o) \
#$(LIB)(encode.o) $(LIB)(equal.o) $(LIB)(error.o) \
#$(LIB)(evalx.o) $(LIB)(evals.o) $(LIB)(chr.o) \
#$(LIB)(ext.o) $(LIB)(len.o) $(LIB)(expunge.o) \
#$(LIB)(f.o) $(LIB)(fetch.o) $(LIB)(for.o) \
#$(LIB)(getdims.o) $(LIB)(getfnam.o) $(LIB)(gosub.o) \
#$(LIB)(goto.o) $(LIB)(if.o) $(LIB)(input.o) \
#$(LIB)(iprintf.o) $(LIB)(isthere.o) $(LIB)(let.o) \
#$(LIB)(list.o) $(LIB)(lnpars.o) $(LIB)(load.o) \
#$(LIB)(minus.o) $(LIB)(new.o) $(LIB)(no_op.o) \
#$(LIB)(old.o) $(LIB)(on.o) $(LIB)(pause.o) \
#$(LIB)(print.o) $(LIB)(put.o) $(LIB)(random.o) \
#$(LIB)(read.o) $(LIB)(reseq.o) $(LIB)(run.o) \
#$(LIB)(save.o) $(LIB)(sing.o) $(LIB)(stop.o) \
#$(LIB)(strcat.o) $(LIB)(sub.o) $(LIB)(update.o) \
#$(LIB)(variable.o) $(LIB)(call.o) $(LIB)(postb.o) \
#$(LIB)(pathopen.o) $(LIB)(belse.o) $(LIB)(untilcod.o) \
#$(LIB)(auto.o) $(LIB)(more.o): bas.h
