.TH 11 8
.CT 1 prog_c
.SH NAME
11as, 11cc, 11ld, 11nm, 11ranlib, 11reloc, 11size, 11strip \- pdp11 support
.SH DESCRIPTION
These programs do cross-compiling and related support
functions for the DEC PDP-11 family of computers.
Their descriptions correspond closely with those of
similarly named programs in Section 1 of this manual.
.SH FILES
.F 11a.out
output file
