.TH AC 8
.CT 1 sa_nonmortals
.SH NAME
ac \- login accounting
.SH SYNOPSIS
.B /etc/ac
[
.I option ...
]
[
.I person ...
]
.SH DESCRIPTION
.I Ac
prints the total connect time
recorded in the accounting file,
.FR /usr/adm/wtmp .
If
.I persons
are named, only those login names are considered.
The options are
.TP
.BI -w " file"
Use
.I file
instead of 
.FR /usr/adm/wtmp ;
.L -
means the standard input.
.TP
.B -p
Print total connect time for each
user.
.TP
.B -d
Print totals for each day.
.PP
The accounting file
.F /usr/adm/wtmp
is maintained by
.I init 
and
.IR login (8),
provided it exists.
To start accounting, create it with length 0.
When accounting is turned on, the file grows without limit.
It is prudent periodically
to process the data and truncate the file.
.SH FILES
.F /usr/adm/wtmp
.SH "SEE ALSO"
.IR init (8), 
.IR sa (8), 
.IR login (8), 
.IR utmp (5), 
.IR who (1)
