.TH CHOWN 8
.CT 1 sa_nonmortals secur
.SH NAME
chown \- change owner or group
.SH SYNOPSIS
.B /etc/chown
.IB owner , group
.I file ...
.SH DESCRIPTION
.I Chown
changes the owner of the
.I files
to
.I owner
and the groupid to
.IR group .
Either
.I owner
or
.I group
may be omitted
to leave the owner or groupid unchanged.
.PP
.I Owner
may be either a decimal userid or
a login name found in
.FR /etc/passwd .
.I Group
may be either a decimal groupid or
a group name found in
.FR /etc/group .
.PP
The owner of a file
may change its group
to that of the current process.
Other changes are restricted to the super-user.
.SH FILES
.F /etc/passwd
.br
.F /etc/group
.SH "SEE ALSO"
.I chown
in
.IR chmod (2),
.IR passwd (5), 
.IR chmod (1),
.IR chdate (1)
