.TH SHOWQ 8
.CT 1 sa_nonmortals
.SH NAME
showq \- status of stream input/output system
.SH SYNOPSIS
.B /etc/showq
[
.B "-v -V -s -m
]
[
.I system
]
[
.I mem
]
.SH DESCRIPTION
.I Showq
reports connectivity and contents of I/O streams.
By default, it lists the maximum number of stream blocks
(of various sizes) ever used, then each stream and the queue modules
in each stream, and then blocks that are unaccounted for (not on any
queue or the free list).
.PP
By default, the system namelist is
.B /unix
and the place the streams are kept is
.BR /dev/mem .
.PP
The options are:
.TP
.B -v
Verbose.
Show more, in particular the contents of data and control blocks on each queue.
.TP
.B -V
Very verbose.
Show all blocks on every queue instead of giving up after a while.
.TP
.B -s
Silent.
Examine queues for consistency, printing only a summary.
.TP
.B -m
Missing.
Show the contents of missing blocks.
(Perhaps this will give a clue about who lost them.)
.SH FILES
.F /unix
.br
.F /dev/mem
.SH SEE ALSO
.IR stream (4),
.IR netstat (8)
.br
.IR mesgld (4)
for a list of message types
