.TH SYNC 8
.CT 1 sa_nonmortals
.SH NAME
sync, update \- update disk file systems
.SH SYNOPSIS
.B sync
.PP
.B /etc/update
.SH DESCRIPTION
.I Sync
executes the
.IR sync (2)
system primitive,
to suggest that all disk writes be completed soon.
It is wise to call
.I sync
before halting the system.
.PP
.I Update
calls
.IR sync (2)
every 30 seconds,
so that file systems
are fairly well up to date
if the system crashes.
It should be run once
from
.IR rc (8).
.SH "SEE ALSO"
.IR sync (2), 
.IR reboot (8)
