.TH BITSHIP 1 " "
.SH NAME
bitship \- convert file to or from visible representation
.SH SYNOPSIS
.B bitship
[
.B \-a
|
\-b
]
.SH DESCRIPTION
.I Bitship \-a
pipes an arbitrary file into a visible ASCII-95 representation.
.I Bitship \-b
performs the inverse transformation. If you are sending a file to
someone for the first time, you should probably include a copy of
the source code.
.SH FILES
/usr/src/cmd/bitship.c
.SH DIAGNOSTICS
"Usage:..." in case of an error in the command line.
.SH BUGS
There is no error correction. Illegal characters in a "visible" file
produce garbage.
