.TH BMD08V I
.UC
.SH NAME
bmd08v \- Analysis of Variance
.SH SYNOPSIS
.B bmd08v
.SH DESCRIPTION
.I Bmd08v
performs analysis of variance for any hierarchical
design with equal cell sizes.
This includes the nested, partially nested and partially crossed,
and fully crossed designs.
Separate analyses may be performed on several dependent
variables simultaneously.
.I Bmd08v
takes its input from the standard input and writes its results on
the standard output.
All bmd control cards must have the identifying field in
upper case (eg. PROBLM, INDEX, FINISH, etc.).
One important departure from previous
versions concerns the variable format card \-
it is no longer necessary! If you specify 0 for
the number of variable format cards, the data will
be assumed to be in "free format" \- items
separated by blanks or commas.
.SH EXAMPLES
In the first example,
.I data
contains the bmd control cards and the
input data.
Output is directed to the standard output.
.sp
bmd08v <data
.sp
In the second example,
.I prefix
contains the initial bmd control cards,
.I data
contains the input data, and
.I finish
contains the FINISH card
(many users prefer not to contaminate their data files).
Output is directed to file
.BR output .
.sp
cat prefix data finish | bmd08v >output
.SH FILES
/tmp/1?????	temporary file
.br
/tmp/2?????	temporary file
.SH "SEE ALSO"
BMD User's Guide, /usr/doc/bmd08v
.SH BUGS
Temporary files are not always scratched.
