.TH FSTAT 1 
.SH NAME
fstat \- file status
.SH SYNOPSIS
.B /etc/fstat
[
.B \-u
user ] [
.B \-p
pid ] [
.B \-f
filename ]
.SH DESCRIPTION
.I Fstat
identifies open files.
A file is considered open if a process has it open,
if it is the working directory for a process,
or if it is an active pure text file.
Under default options,
.I fstat
reports on all open files.
.PP
Options:
.TP 6
.B  \-u
Report all files open by a specified user.
.TP 6
.B  \-p
Report all files open by a specified process id.
.TP 6
.B  \-f
Restrict reports to the specified file.
If the file is a character special file,
.I fstat
additionally reports on any open files on that device,
treating it as a mounted file system.
.dt
.SH "SEE ALSO"
ps(1), pstat(8)
.SH DIAGNOSTICS
Yet to be determined.
.SH BUGS
.I Fstat
tries to be clever if you elide the
.B \-u ,
.B \-f ,
or
.B \-p
flags for the argument.  Like any expert system, it is sometimes wrong.
