.TH INSTALL 8 bowell
.SH NAME
install \- place files in their proper homes
.SH SYNOPSIS
.B /etc/install
[
.B \-c
] [ \-s ]
file dest
.SH DESCRIPTION
.I Install
moves or copies the
.I file
to 
.I dest.
If 
.I dest 
is a directory, the file is installed in the directory.
Its main use is in makefiles subsidiary to the primary source directory /src.
.PP
Option 
.B \-c
causes the file to be copied, otherwise it is moved.
Option 
.B \-s
invokes 
.IR strip (1)
on the file first.
.PP
If possible, the group and owner of
.I dest
are changed to `bin'.
.SH BUGS
Only one option can appear.
