.TH IREAD 3
.SH NAME
iread \- insistent read
.SH SYNOPSIS
.B read(fildes, buf, n)
.B char *buf;
.SH DESCRIPTION
.I Iread,
like
.IR read (1),
reads
.I n
bytes from the file associated with the given file descriptor
into the block of store beginning at
.I buf.
.I Iread,
however, always places exactly
.I n
bytes in
.I buf,
unless 
.I read
would return 0.
.PP
.I Iread
returns the number of bytes placed in
.I buf,
which is an integer in the range 
.RI 0- n.
.SH DIAGNOSTICS
.I Iread
returns \-1 for an error; see
.IR read (1).
.SH SEE ALSO
read(2)
