.TH LSH 9.9
.SH NAME
lsh \- create layers and run shell commands
.SH SYNOPSIS
.B lsh
[<file] [>file]
.br
.SH DESCRIPTION
.I Lsh
runs under
.IR mpx (1)
and reproduces a specified setup of layers.
Each line of the standard input is of the form:
.IP
x0 y0 x1 y1 shell-command
.PP
For each line
.I Lsh
creates a layer whose diagonal spans the points
.RI ( x0,y0 )
and
.RI ( x1, y1 ),
where (0,0) is the upper left corner of the screen and (800,1024) is the
lower right.
If a shell-command is given, it is executed in that layer.
.PP
The standard output gives the coordinates of each layer that already exists and
its downloaded object file, if any.
This provides coordinates for an input script to duplicate
a handmade setup.
.SH BUGS
Standard input cannot be the keyboard.
