.TH NEWSCHECK 1
.SH NAME
newscheck \- check to see if user has news
.SH SYNOPSIS
newscheck [yne] [readnews options]
.SH DESCRIPTION
.I newscheck
reports to the user whether or not he has news.
.TP 10
.B y
Reports "There is news" if the user has news to read.
.TP 10
.B n
Reports "No news" if their isn't any news to read.
.TP 10
.B e
Executes
.I readnews(1)
if there is news.
.PP
If there are no options,
.B y
is the default.
.SH FILES
.PD 0
.TP 25
/usr/lib/news/active
Active newsgroups
.TP 25
~/.newsrc
Options and list of previously read articles
.SH SEE ALSO
readnews(1),
inews(1)
