.TH READSLOW 1
.SH NAME
readslow \- watch a growing file
.SH SYNOPSIS
.B readslow
[
.B \-e
]
[ file ]
.SH DESCRIPTION
.I Readslow
copies the contents of the
.I file
(standard input by default)
to the standard output.
Upon reaching an apparent end of file, it
tries periodically to read further, thus letting
you watch the progress of a file that another process
is writing into.
Option
.B \-e
causes readslow to begin at the present end of the
.I file.
.SH SEE ALSO
tail(1)
