.TH UNAME 3
.SH NAME
uname \- get name of current system
.SH SYNOPSIS
.B #include <sys/utsname.h>
.PP
.B int uname (name)
.br
.B struct utsname \(**name;
.SH DESCRIPTION
.I Uname\^
stores
information identifying the current
system in the structure pointed to by
.IR name .
.PP
.I Uname\^
uses the structure
defined in \f3<sys/utsname.h>\fP whose members are:
.PP
.RS
char	sysname[9];
.br
char	nodename[9];
.br
char	release[9];
.br
char	version[9];
.RE
.PP
.I Uname\^
returns
a null-terminated character string naming the current
system in the character array
.IR sysname .
Similarly,
.I nodename\^
contains the name that the system is known by on a communications
network.
.I Release\^
and
.I version\^
further identify the operating system.
Upon successful completion, a non-negative value is returned.
.SH FILES
/etc/whoami
.SH DIAGNOSTICS
If the routine fails, \-1 is returned and
.I errno\^
is set to indicate the error.
