.TH UUREC 1
.SH NAME
uurec \- receive processed news articles via mail
.SH SYNOPSIS
uurec
.SH DESCRIPTION
.I uurec
reads news articles on the standard input sent by
.I sendnews(1),
decodes them, and gives them to
.I inews(1)
for insertion.
.SH SEE ALSO
inews(1),
readnews(1),
recnews(1),
sendnews(1),
newscheck(1)
