install:
	cp uucproute smtproute rewrite /usr/lib/upas/
	-chown bin /usr/lib/upas/smtproute /usr/lib/upas/rewrite
	-chgrp bin /usr/lib/upas/smtproute /usr/lib/upas/rewrite
	chown 775 /usr/lib/upas/smtproute
