.TH DIMPRESS 1 local
.SH NAME
dimpress \- Imagen printer filter
.SH SYNOPSIS
.B dimpress
[ option ] ... [ file ] ...
.SH DESCRIPTION
.I Dimpress
prints
.I files
created by
.IR troff (1)
on any printer that accepts the Impress graphics and page layout
language.
If no
.I file
is mentioned, the standard input is printed.
The following options are understood.
.TP 1.0i
.BI \-o list
Print pages whose numbers are given in the comma-separated
.IR list .
The list contains single numbers
.I N
and ranges
.IB N1 \- N2.
A missing 
.I N1
means the lowest-numbered page, a missing
.I N2
means the highest.
.TP 1.0i
.B \-t
Direct output to the standard output instead of the printer.
.TP 1.0i
.BI \-x num
Leave a margin
.I num
inches from the left side edge of the paper.
.TP 1.0i
.BI \-y num
Leaves a margin
.I num
inches down from the top of the page.
Negative values for
.I num
are allowed and often useful, especially to get macro generated
cut marks off the page.
.TP 1.0i
.BI \-l
Print the job in landscape mode.
.TP 1.0i
.BI \-p num
Set the horizontal and vetical step sizes for graphics to
.I num
pixels.
If Impress graphics commands are used for drawing this option
will only affect splines.
.TP 1.0i
.BI \-P num
Use
.I num
as the pixel diameter of the Impress graphics pen.
Only useful when Impress graphics commands are being used.
.TP 1.0i
.BI \-T name
Generate output to be printed on the target printer
.I name.
The printers currently supported are:
.RS 1i
.TP .5i
.PD 0
.B i300
Imagen 8/300
.TP .5i
.B i480
Imagen 5/480
.TP .5i
.B i10
Imagen Imprint-10 using rasti10 raster files
.TP .5i
.B i240
Imagen Imprint-10 using rasti240 raster files
.RE
.PD 1
.IP
By default the output printer is assumed to be
.I i300.
Although
.I i10
and
.I i240
select the same target printer, namely the Imprint-10,
the raster tables used for character generation will be
found in different directories.
.TP 1.0i
.BI \-F dir
Use
.I dir
as the
.I troff
font directory.
.TP 1.0i
.BI \-B dir
Use
.I dir
as the raster table directory.
When processing a
.I file
generated by
.I troff
for printing on device xxx
.I dimpress
will first look for the binary font directory devxxx
in the raster table directory.
If it's not found there the devxxx directory in
.I troff's
font directory will be used.
.TP 1.0i
.BI \-R name
Use raster tables generated for device
.I name
when printing
.I file.
By default
.I dimpress
will attempt to use the target printer's raster files.
.TP 1.0i
.BI \-f file
Read resident font information from
.I file
which is located in directory /usr/lib/raster/RESIDENT.
By default
.I dimpress
looks for a file in that directory that has the same
name as the target printer.
Useful if several otherwise identical printers
support different sets of resident fonts.
.PP
The
.I files
should be prepared by
.I troff.
Best results will almost certainly be obtained only when
.I troff
and
.I dimpress
agree on the target printer.
.SH FILES
/tmp/dimp*
.br
/usr/lib/font/dev*/*
.br
/usr/lib/raster/rast*
.br
/usr/lib/raster/RESIDENT/*
.br
.SH SEE ALSO
troff(1), tc(1), troff(5), daps(1)
.\"	@(#)daps.1	1.1 of 12/17/82
