char *helpstrs[] = {
	"AUTO [ON|OFF]",
	"CUE time",
	"EDIT OFF",
	"FRAME [ON|OFF]",
	"HELP",
	"EDIT SET in_time out_time channels",
	"EDIT GO",
	"INSERT time [nframes=1]",
	"LOOP tbegin tend frames/s",
	"PLAY",
	"PREROLL TIME time",
	"REC",
	"REC STEP",
	"REMOTE [frame|str]",
	"REMOTE system prog [relay]",
	"REMOTE system prog [relay]",
	"SET TIME [T1|TCR] time",
	"SHOOT start nframes",
	"SLEEP NUMBER",
	"SNAP [nframes=1]",
	"STANDBY OFF",
	"STATUS",
	"STATUS STATUS",
	"STEP [FWD|REV]",
	"STILL time",
	"STILL MODE [ON|OFF]",
	"STOP",
	"TIME timertype",
	"TIME MODE [T1|T2|TCR]",
	"VIEW tbegin tend",
	"WAIT",
	0
};
