BUILTINS=
CFLAGS=-N -I. -I/usr/include -A -A -DBIGEND -DV10 -DNEEDPROTO -DLOG='"/tmp/u9fs.log"'

u9fs:	u9fs.o conv.o memmove.o mfmt.o mkfile
	lcc -o u9fs u9fs.o conv.o memmove.o mfmt.o

%.o:	%.c  u.h libc.h 9p.h
	lcc -c $CFLAGS $stem.c
