#!/v/bin/sh
PATH=/v/bin:/bin:/usr/bin
cd /netlib/f2c
args=`./F2cargs $2 2>/dev/null`
echo -e -n "*==netlib/f2c $args $1 `date`==\n*" 2>&1 >> In
time ./Netlib.f2c $args < $2 2>> In
cat $2 >> In
# echo "Sorry, f2c has been turned off temporarily." 2>&1
# echo "It was too much CPU load for our gateway." 2>&1
rm -f $2
