.TH SYNC 2
.CT 2 sa
.SH NAME
sync \- force writing of system buffers
.SH SYNOPSIS
.B void sync()
.SH DESCRIPTION
.I Sync
schedules all information in
memory that should be on disk or other block media to be written out.
This includes modified super-blocks,
modified inodes, and delayed block I/O.
.PP
It should be used by programs which examine a file system,
for example
.IR icheck (8).
It is highly recommended before a shutdown or reboot.
.SH "SEE ALSO"
.IR sync (8)
.SH BUGS
The writing, although scheduled, is not necessarily
complete upon return from
.IR sync .
