.TH SYSCALL 2
.CT 2 misc
.SH NAME
syscall \(mi indirect system call
.SH SYNOPSIS
.B "int syscall(number, arg, ... )"
.SH DESCRIPTION
.I Syscall
performs the system call with the specified
.I number
and arguments and returns its result.
The numbers may be found in the system source.
.SH BUGS
The simulation fails for system calls
such as
.IR pipe (2),
which return multiple values.
