BUILTINS =
CC = lcc
#g = -g
g =
%.o: %.c efix.h
	$CC -c $g $stem.c
%.O: %.c efix.h
	cyntax -c $stem.c

both:V: ../Efix ../cpt

../Efix: main.o process.o
	$CC $g $prereq -o $target

../cpt: cpt.c
	$CC $g $prereq -o $target

clean:
	rm -f *.o
