/*
 * Glenn Fowler
 * AT&T Bell Laboratories
 *
 * file to string vector support
 */

extern void	free();

/*
 * free a string vector generated by vecload()
 *
 * retain!=0 frees the string pointers but retains the string data
 * in this case the data is permanently allocated
 */

void
vecfree(vec, retain)
register char**	vec;
int		retain;
{
	if (vec)
	{
		if (*(vec -= 2) && !retain) free(*vec);
		free(vec);
	}
}
